### ISSUE TITLE
When is this happening?

### ISSUE THREAD

**Issue by paulschwarz** [krasimir/navigo#1]

**Comment by krasimir** [comment]
Sorry @paulschwarz ... I've been really busy last few weeks. I'll try pushing this repo forward next couple of days.

**Comment by bradoyler** [comment]
I'm also interested ;)

**Comment by krasimir** [comment]
@paulschwarz @bradoyler I think I wrapped up the project. Here is an [official page](http://work.krasimirtsonev.com/git/navigo/testing/). There is test suite (in node + browser) and everything
