### ISSUE TITLE
Current state / statechange

### ISSUE THREAD

**Issue by zirafa** [krasimir/navigo#10]
- Is there a way to retrieve the current route state? History.state appears null...
- Similarly, is there an event handler for route changes? Something triggers when the state changes, like routestatechange or something?

**Comment by krasimir** [comment]
> Is there a way to retrieve the current route state? History.state appears null...

You may use `router._cLoc()`. I have to provide for an API for this but for the time being you may use this internal function to retrieve the current URL.

 > Similarly, is there an event handler for route changes? Something triggers when the state changes, like routestatechange or something?

That's actually the main funcationality of Navigo. It calls a handle once the route is changed. The second argument of `on` method is the handler that you are searching for. Or maybe you are searching for a general one that is triggered separately. If yes, there is no such API right now.

**Comment by zirafa** [comment]
Thanks. Yes I was curious if there was a general one triggered separately anytime navigo matches a route (different than creating a default/wildcard route). Something similar to hashchange would be nice. For now, I suppose I can get around this by calling the same function in every defined route. My use case is I'm trying to bind the route state to a DOM element (menu links).

**Comment by krasimir** [comment]
I see. Anyways, it's a nice idea. I'll add it to the TODO list.
