### ISSUE TITLE
route matching

### ISSUE THREAD

**Issue by cultulhul** [krasimir/navigo#103]
router.on({'tracks': function () {
		       console.log('tracks');
	}
});`

`router.on({'artist/:id/tracks':` function (params) {
			console.log('artist/' + params.id + '/tracks');
		}
	});

when the two routes are placed like this the second route is not marching it matches the first route it only works properly when the second route is on top

**Comment by krasimir** [comment]
@cultulhul unfortunately the order of routes' addition matter in Navigo. The matching is based on regular expression so whatever matches first it wins. What I'm saying is that that's not a bug but an expected behavior.

**Comment by cultulhul** [comment]
ok thanks for clearing it up
