### ISSUE TITLE
adding hooks in multiple router setup

### ISSUE THREAD

**Issue by flowen** [krasimir/navigo#105]
hi! Thanks for the minimalist router, I love it. This might be a bit of a newbie question, but I'm unsure how to add the hooks if I setup the code with multiple routes. Also I wonder if it's possible to overrule specific hooks per route in this setup. For example I want to add a showLoader function for all the routes except 404.

**Comment by krasimir** [comment]
Hello @flowen,

actually the hooks are added per route. For example:
```js
router.on(
  '/user/edit',
  function () {
    // show user edit page
  },
  {
    before: function (done) {
      // doing some async operation
      done();
    },
    after: function () {
      console.log('Data saved.');
    }
  }
);
```

And because they are just functions you may extract them to a function definition:
```js
var beforeHook = function (done) { ... };
var afterHook = function () { ... };

router.on(
  '/something',
  function () { ... },
  { before: beforeHook, after: afterHook }
);

router.on(
  '/else',
  function () { ... },
  { before: beforeHook, after: afterHook }
);
```

That way you may create single hook for all your routes and define a specific one for 404 pages.

**Comment by flowen** [comment]
alright, thank you for the answer!
