### ISSUE TITLE
Relative url navigation issue

### ISSUE THREAD

**Issue by martonx** [krasimir/navigo#106]
Hi,

If I use relative url-s in anchors like: `<a href="./" data-navigo>Back</a>` and my url is http://mydomain.com/admin/settings/create then this link should navigate back to http://mydomain.com/admin/settings

Is it possible to use navigo with these kind of relative urls?

**Comment by martonx** [comment]
I did a pull request for better handling relative urls in navigo. https://github.com/krasimir/navigo/pull/109

**Comment by krasimir** [comment]
4.6.1. released containing the fix from #109.

**Comment by martonx** [comment]
Big-big THANK YOU!
