### ISSUE TITLE
feature request 

### ISSUE THREAD

**Issue by cultulhul** [krasimir/navigo#107]
i would like to request a hook that runs when you are about to navigate away from a route regardless of the route your navigating to

**Comment by krasimir** [comment]
Is it possible to use the `before` hook and simply apply same function to all the routes?

**Comment by cultulhul** [comment]
yes it is but its not convenient it only needs to run on two routes and they might be some use cases for others were its not possible to do it that way

**Comment by krasimir** [comment]
Ok, I'll think about `beforeAll` and `afterAll` hooks.

**Comment by cultulhul** [comment]
Ok, i think a hook that runs when you are about to navigate away from a route would also also be needed in cases were you have many routes that need the to run code specific to them, a beforeAll would involve too many checks to see what is the current route

**Comment by krasimir** [comment]
Well isn't it `you are about to navigate away` means you are about to enter another one. So `beforeAll` is de-facto what we need.

**Comment by cultulhul** [comment]
they are similar but i think their is a need for both  a beforeAll hook would be great in scenarios were the code you want to run applies to all routes, if you have many routes that have code specific to them a onLeave hook makes more sense eg in a single page app where the their are many different event listener tied to the html of the specific routes using a beforeAll to remove them would involve checking to see what route your on first while using a onLeave hook you could just remove then as the code will only run on the specific route

**Comment by asmer** [comment]
I wanna beforeAll and afterAll for common operations too. I will be grateful for that feature :)

**Comment by krasimir** [comment]
4.8.0 version released. It contains [generic hooks](https://github.com/krasimir/navigo#generic-hooks) + [leave hook](https://github.com/krasimir/navigo#hooks).

P.S.
Sorry for the delay @asmer @cultulhul
