### ISSUE TITLE
Parameters

### ISSUE THREAD

**Issue by tomhooijenga** [krasimir/navigo#11]
It took me while to figure out how to use one parameter as the url. My root url is `http://localhost:43088/test-page`
```js
router.on(':slug', function (slug) {
// slug is "http:"
});
```
When the parameter is not the first thing, it works like it should: 
`http://localhost:43088/example/test-page`
```js
router.on('/example/:slug', function (slug) {
// slug is "test-page"
});
```
This can be fixed with a custom regex `/([\w-]+)$/` (Anything [a-zA-Z_-] at least once untill the end of the string)
A better solution would be to exclude the root from the matching process.

**Comment by krasimir** [comment]
Good point :+1: I'll try fixing this next few days.

**Comment by krasimir** [comment]
@tomhooijenga can you please confirm that the new  `1.1.1` version works as expected. On http://work.krasimirtsonev.com/git/navigo/about if we run
```js
router._routes = [];
router.on(':slug', function (params) {
  console.log(params);
});
```
we'll get
```js
Object {slug: "about"}
```

**Comment by Aurelsicoko** [comment]
Hi, first of all thanks for you awesome work! 

I had the same issue, when I run the code below, I get :
```javascript
Object {slug: "http:"}
```

**Comment by krasimir** [comment]
@Aurelsicoko can you please create a page that reproduces the issue or paste your code here.

**Comment by Aurelsicoko** [comment]
@krasimir I have a similar code like @tomhooijenga.

```javascript
var router = new Navigo(root = null, useHash=false);

router.on('/experience/:match', function (params) {
  // It's ok.
  // Object {match: "1234"}
});

router.on('/experience', function (params) {
  // It's ok.
});

router.on('/team/:eleven', function (params) {
  // It's ok.
  // Object {eleven: "1234"}
});

router.on(':match', function (params) {
   // It's NOT ok.
   // Object {match: "http:"}
   // I except `Object {match: "1234"}` when I request this URL `http://localhost/1234`
});
```

PS : I downloaded the minified version available [here](https://raw.githubusercontent.com/krasimir/navigo/master/lib/navigo.min.js).

**Comment by krasimir** [comment]
@Aurelsicoko sorry but I'm not able to reproduce the problem. I'm using the same file as you. Here is what my test is made of:

`.htaccess` file:
```
Options +FollowSymLinks
IndexIgnore */*
RewriteEngine On

RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^(.*)$ index.php
```

`index.php` file:
```
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Document</title>
</head>
<body>
  <script src="http://home.dev/Krasimir/_tests/navigo/navigo.min.js"></script>
  <script>
    var router = new Navigo('http://home.dev/Krasimir/_tests/navigo', false);

    router.on('/experience/:match', function (params) {
      console.log('/experience/:match', params);
    });
    router.on('/experience', function (params) {
      console.log('/experience', params);
    });
    router.on('/team/:eleven', function (params) {
      console.log('/team/:eleven', params);
    });
    router.on(':match', function (params) {
       console.log(':match', params);
    });
  </script>
</body>
</html>
```

If you want to use the same files you should amend the paths since they point to my local env. The result trying `http://home.dev/Krasimir/_tests/navigo/1234` is:
![image](https://cloud.githubusercontent.com/assets/528677/15384862/573388e6-1da6-11e6-92cd-2d1bb8bc31b2.png)

**Comment by Aurelsicoko** [comment]
@krasimir: Thanks for your help! I forgot to spend the root parameter in the navigo constructor... That was my mistake.

**Comment by krasimir** [comment]
👍
