### ISSUE TITLE
Regex not matching route when querystring is present

### ISSUE THREAD

**Issue by janetha** [krasimir/navigo#112]
For example, the url is http://something.com/mypage/?q=blah
`Navigo.FOLLOWED_BY_SLASH_REGEXP = '(?:\/$|$)';`
is not able to match 'mypage' as my route.

My question is, is there any consequences if I change the _cLoc from
`return clean(window.location.href); `
to
`return clean(window.location.pathname);`

So far I haven't encountered any problems with it.  Or can anyone provide a regex that can match url with querystring?  I was having a hard time coming up with one.

**Comment by krasimir** [comment]
@janetha what are your route definitions?

**Comment by janetha** [comment]
I chose not to to use hash

```
router = new Navigo(null, false);
    router.on({
        'zipcode': function () {
            $('button').click(function(){
                 var z = $('input').val();
                 router.navigate('/nextpage/?zipcode=' + z);
            });
        },
        'nextpage': function () {
            //get zipcode in url and do something
        },
```

The regex '(?:\/$|$)' won't match the entire url http://something.com/nextpage?zipcode=10001 but would match if there is no querystring http://something.com/nextpage/

**Comment by janetha** [comment]
Never mind. I understand now that for my scenario, I should really use hash. Thanks for this great library.
