### ISSUE TITLE
Issues with before hook and History state push when resolving same route several times

### ISSUE THREAD

**Issue by pwrinc** [krasimir/navigo#115]
I did figure out some strange non expected behavior when resolving the same path several times in sequence.

Using navigo release 4.6.0

Consider following router configuration:
```javascript
let router = new Navigo(null);

router.on(
  '/page1',
  function () {
    console.log('Navigate to /page1');
  }
);
```

### Scenario 1
When resolving route `/page1` multiple times in sequence (e.g. 3 times) by either clicking a link `<a href='/page1' data-navigo>` several times or calling
```javascript
router.navigate('/page1');
router.navigate('/page1');
router.navigate('/page1');
```
The route handler is called only once (which is correct behaviour). Thus `Navigate to /page1` is only called once after the route changes the first time. In contrast each time the `router.navigate()` is called/link is clicked a history item is added to browser history by calling `history.pushState()`. So in that case I would expect `history.pushState()` is only called once at the first resolve for this route instead of three times.

### Scenario 2:
When adjusting route above to add before hook like
```javascript
before: function (done) {
  console.log('Before hook for /page1');
  done(false);
}
```
The browser console outputs `Before hook for /page1`. Navigo prevents calling the resolve function for this root. Thus `Navigate to /page1` is not written to console. Although this should prevent route change a new history item is pushed by calling `history.pushState()`. The expected behavior would be to stop route handleing wen before handler calls `done(false)` and thus prevent browser history (and addressbar) to be changed.

**Comment by krasimir** [comment]
Here's the function that manages the hooks:
```js
function manageHooks(handler, route, params) {
  if (route && route.hooks && typeof route.hooks === 'object') {
    if (route.hooks.before) {
      route.hooks.before((shouldRoute = true) => {
        if (!shouldRoute) return;
        handler();
        route.hooks.after && route.hooks.after(params);
      }, params);
    } else if (route.hooks.after) {
      handler();
      route.hooks.after && route.hooks.after(params);
    }
    return;
  }
  handler();
};
```
So, we have `if (!shouldRoute) return;` which shouldn't allow the routing to happen if you call `before` hook with a `false` value. Can you come with a test case that reproduces your situation.

**Comment by pwrinc** [comment]
I think the bug is caused in the [Navigo.navigate()](https://github.com/krasimir/navigo/blob/master/src/index.js#L186) method in line 186. There you call history api to replace or push new state before calling resolve() in the next line:

    navigate: function (path, absolute) {
      var to;

      path = path || '';
      if (this._usePushState) {
        to = (!absolute ? this._getRoot() + '/' : '') + path.replace(/^\/+/, '/');
        to = to.replace(/([^:])(\/{2,})/g, '$1/');
        history[this._paused ? 'replaceState' : 'pushState']({}, '', to); // This causes history modifiaction
        this.resolve(); // manageHooks() method is called in resolve() method. So this is done AFTER history modification
      } else if (typeof window !== 'undefined') {
        path = path.replace(new RegExp('^' + this._hash), '');
        window.location.href =
          window.location.href
            .replace(/#$/, '')
            .replace(new RegExp(this._hash + '.*$'), '') + this._hash + path;
      }
      return this;
    }

If think the history modifiaction should be part of the `resolve()` method and should be suppressed if `shouldRoute = false` in the `manageHooks()` method.

**Comment by krasimir** [comment]
Just released `4.7.4`. There's no `resolve` in there anymore. Here's my thinking: 
* I agree that the there shouldn't a history entry if `shouldRoute = false`
* The way of how Navigo works is
```
       Listening for changes in the URL (1)
--> A change happen via navigate method (2)
       Navigo triggers resolve and checks hooks (3)
```
Indeed there was a bug. That `resolve` shouldn't be in the `navigate` method. It should be called only because the actual path/URL in the browser is changed.
* By design Navigo reacts only on URL changes and I really believe in that.

I see your point and indeed seems logical. However Navigo needs an update in order to continue with `resolve` and processing hooks. Otherwise it sounds like "Here's the URL that I want to set. Now analyze it, find a match and run the hooks but don't change the URL yet". What I'll suggest is to make your checks before calling `navigate` on the first place.

**Comment by jgdreyes** [comment]
@krasimir I'm coming into this late, but hopefully you can answer my question.  I was using a version prior to this that relied on `.navigate()` to call `.resolve()`.

For this newer version, when I call Navigate and the router *is not paused* do I need to call `.resolve()` manually?

**Comment by krasimir** [comment]
@jgdreyes interesting. Let me investigate. I may introduced a bug with those latest changes.

**Comment by krasimir** [comment]
@jgdreyes sorry for taking so long. Please use `5.0.1` version. it fixes the `navigate` method. You don't have to call `resolve` manually.

**Comment by VeXell** [comment]
@krasimir After this issue simple routers do not work (without any hooks) and i should execute resolve manually.
`executeController(controller, routeParameters) {
        this.trigger('before-change', [true]);

        let queryParameters = this._getQueryParameters();
        let parameters = _.extend({}, routeParameters, queryParameters);

        this._initController(controller, parameters);

        return true;
    }

    _appendRoutes() {
        router.on('/select-city/:cityId', (parameters) => this.executeController(CitySelectController, parameters));
        router.on('/select-city', (parameters) => this.executeController(CityIndexController, parameters));

        router.on('/schedule/:filmId', (parameters) => this.executeController(ScheduleController, parameters));

        router.on('/list/:when', (parameters) => this.executeController(HomeController, parameters));
        router.on('/', (parameters) => this.executeController(HomeController, parameters));

        router.notFound(() => this.executeController(Home404Controller));
    }`

**Comment by krasimir** [comment]
@VeXell glad that it works. I indeed made a bad release :)
