### ISSUE TITLE
Feature Request: Replace current history entry instead of pushing one in Navigo.navigate()

### ISSUE THREAD

**Issue by JonasTaulienSolutions** [krasimir/navigo#121]
Hey Krasimir,

## Feature Description
I would like to be able to replace the current history entry instead of appending one when using the navigate method.
The signature of the navigate method could be changed to `function(path, absolute, replace)`. If `replace` is set to `true`, then the current history entry will be replaced with the new one, meaning the user won't be able to use the back button to navigate to it. This is exactly the behaviour of the [Location.replace()](https://developer.mozilla.org/en-US/docs/Web/API/Location/replace) function.
If the `replace` parameter is set to `false`, which is the default, the behaviour remains unchanged.

## Why?
I'm currently only using the router for providing me with the current article name, that has to be shown on the page. (e.g. for calling a handler with `overview/getting-started` as parameter when `[path-to]/index.html#overview/getting-started` gets opened).
This way, I do not have to change the router when a new article is added. But it also could be, that the user requests an article, that is not present, like `overwiew/gettingstarted`. The function that is responsible for loading an article will call a callback, when an article could not be loaded. In this callback I call `Navigo.navigate()` with `'not-found'` as parameter, so the handler for loading the article gets dispatched.
My Navigo-configuration looks like this:
```js
var navigo = new Navigo(null, true, hash);
navigo.on(/#(.*)/, function(article){
  switchArticle(article, function(){
      navigo.navigate('not-found');
  });
});
```

But this means, that one can't go back in browser history after beeing redirected to the not-found page, because Navigo first pushes `overview/gettingstarted` and then `not-found` to the history. When the user then goes back in history, he lands on `overview/gettingstarted` and then gets redirected to `not-found` instead to the page, on which the user was before he tried to open `[path-to]/index.html#overview/gettingstarted`.
That's why I would like to execute
```js
      navigo.navigate('not-found', false, true);
```
or for example (which is more verbose)
```js
      navigo.redirect('not-found');
```
which executes the described behaviour.

I don't want to steal your time, so when this feature is too complex to implement, or you just don't want it, just say it and I'll refactor my configuration and add an router-entry for every article and use the Navigo.notFound() method. This way I would loose a bit of flexibility but thats also okay :)

I'm also open for a work around, that does not require changes in Navigo.

Thanks in advance :)

**Comment by krasimir** [comment]
Hey @JonasRudolph,

first of all sorry for the late response. Interesting case. I'm looking the code now and I'm seeing this:
```js
history[this._paused ? 'replaceState' : 'pushState']({}, '', to);
```
did you consider using [`pause`](https://github.com/krasimir/navigo#pausing-the-router) API.

If that doesn't help, I'm happy to add one more parameter to `navigate` and use `replaceState` instead of `pushState`. If we have to fix the hash based version of the router then this will be a little bit more work.

**Comment by andrejpavlovic** [comment]
It looks like for pushState that the code would work, but for hash, it seems it always does a full replace.
https://github.com/krasimir/navigo/blob/e8674ba8b305a8793360525c4247aec12f954be6/src/index.js#L186-L189

See https://stackoverflow.com/questions/2305069/can-you-use-hash-navigation-without-affecting-history for more info.

**Comment by krasimir** [comment]
With the upcoming v8.0.0 I accidentally fulfilled the main question here

>  I would like to be able to replace the current history entry instead of appending one when using the navigate method.
The signature of the navigate method could be changed to function(path, absolute, replace). If replace is set to true, then the current history entry will be replaced with the new one, meaning the user won't be able to use the back button to navigate to it. This is exactly the behaviour of the Location.replace() function. If the replace parameter is set to false, which is the default, the behaviour remains unchanged.

The `navigate` now accepts a second argument that has `historyAPIMethod` field. For example:

```js
router.navigate('/foo/bar', { historyAPIMethod: 'replaceState' });
```

which by default is `pushState`.

If you wanna try the new version you can install it via `yarn add navigo@beta`. Not officially published yet.
