### ISSUE TITLE
URL params not working on root

### ISSUE THREAD

**Issue by stoem** [krasimir/navigo#122]
I'm new to navigo so please excuse if this is a false alarm.

I'm trying to pick up and process URL parameters. My code is as follows:
`
var router = new Navigo(null, false);
router.on({
		'/members': function (params, query) {
			console.log("/members route triggered");	
	}
})
.resolve();`

This works fine when I navigate to /members in the browser but fails to fire as soon as I add any kind of GET parameter and load it via the browser.

If I go to the console and test via router.resolve("/members?b=s") then the route fires and query params are available.

**Comment by krasimir** [comment]
Hey,

that's interesting. In theory should work. Here're some questions to clarify the situation:
* Is it like you are refreshing the page with `/members?something=here` or you just add the parameter and hit Enter
* That shouldn't be the case but are you sure that your server forwards that request (with the GET parameter) to the same html page where navigo runs

**Comment by stoem** [comment]
I navigate in my browser to /members, it loads. I can see the routing firing. We use navigo to check the route and make an AJAX call to feed data to a datatable on the page. 

I then manually add /members?something=here to the URL to test it. I add it, hit return. Route doesn't fire. I refresh, still doesn't fire. 
I need this because links from other pages will send this param. 

Param or not, both routes load the same members/index page...

**Comment by stoem** [comment]
I tested my URL in extractGETParameters of navigo - it returns the expected result.
So that part works but that doesn't explain why the route does not fire. If there's a bug it'll be in that area.

**Comment by krasimir** [comment]
Sorry. One last thing, what's your browser?

**Comment by stoem** [comment]
I've only tested in Chrome so far.

**Comment by krasimir** [comment]
@stoem can you please try the latest 4.7.1 version. That was a bug and should be fixed now.

**Comment by stoem** [comment]
Thanks, this works now.

**Comment by itsgracian** [comment]
i follows documentation but i don't how can i get params from url? @krasimir

**Comment by krasimir** [comment]
@itsgracian this is the section that you are searching for https://github.com/krasimir/navigo#parameterized-urls

**Comment by itsgracian** [comment]
@krasimir  thank you
