### ISSUE TITLE
Example with page transitions?

### ISSUE THREAD

**Issue by kokujin** [krasimir/navigo#123]
Can someone point me to a link of an example with page transitions? Thanks

**Comment by krasimir** [comment]
Hey @kokujin,

Navigo itself doesn't have the concept about page control. I mean the library doesn't decide what will be rendered on the screen so you may do a page transitions but that's not part of Navigo. I'll be glad to see an example for that tho. You may be also interested in [hooks](https://github.com/krasimir/navigo#hooks). The `before` hook ones allow you to pospone the route switching.
