### ISSUE TITLE
Shows 404 error on browser refresh

### ISSUE THREAD

**Issue by iiison** [krasimir/navigo#127]
Hi, browser shows 404 error if it is refreshed on any route which is handled at Front-End level. I know one solution is to handle this situation is at server level, by redirecting to `/` and then routes will be calculated at FE. But I want to handle this issue at Front-End level, how react-router does.

**Comment by krasimir** [comment]
Hm ... I'm not sure that even `react-router` will handle that. If you don't forward all the requests to your index file then you are not opening a page that contains Navigo. The 404 Not found is the proper response from your server. Or in other words without a server-side forwarding to a single file you can't make a client-side routing works.

**Comment by iiison** [comment]
Right, my bad, you have to handle that case via webpack in dev-server by changing `historyApiFallback` flag to true.
