### ISSUE TITLE
Routing is too greedy

### ISSUE THREAD

**Issue by jpeltoniemi** [krasimir/navigo#128]
Consider route `/:moduleName/`

I'd expect it to match only one-part urls like `/users/` or `/things/` but instead it matches every url with at least one level.

So, with that route this url `/rock/paper/scissors/` gives me `{moduleName: 'scissors'}` while the expected result is to not match at all.

As `/:moduleName/:pageName` with the url `/rock/paper/scissors` gets parsed to `{moduleName: 'paper', pageName: 'scissors'}`, I'd say it doesn't care where the route matches the url.

**Comment by krasimir** [comment]
This issue made me rethink how Navigo handles routes. The route matching is based on regular expressions and one of them was not quite ok. That's now fixed as part of this latest release. However, these updates change how Navigo uses the registered routes so it may be a breaking change. I bumped the major version. So @jpeltoniemi can you please try with the latest 5.0.0.

**Comment by jpeltoniemi** [comment]
Sorry, I was in a hurry and couldn't wait, so I improvised my own router and as it seems to do its job pretty well, I can't really afford to spend time on Navigo anymore :/

**Comment by krasimir** [comment]
Fair enough 👍
