### ISSUE TITLE
New getLinkPath function is a breaking change

### ISSUE THREAD

**Issue by tnguyen14** [krasimir/navigo#129]
Hi, this change https://github.com/krasimir/navigo/commit/c54d0eb4b018b90d6d15023b041419c7b76e849f just broke my site. This is due to the fact that `link.pathname` is different from `link.getAttribute('href')`.

I have the site lives in a subpath, i.e. `mysite.com/app`. Each link in the app is a relative link, for example `<a href="search">` will point to `mysite.com/app/search`.

With this change, `getLinkPath` now returns `/app/search`, causing the new history state to be `mysite.com/app/app/search` instead. 

I wasn't aware of this breakage because this was released as a minor instead of major version.

**Comment by tnguyen14** [comment]
Actually, it was this change that caused this https://github.com/krasimir/navigo/pull/109/files

It changed `getAttribute('href')` to `link.pathname`.

**Comment by krasimir** [comment]
@tnguyen14 sorry for the late reply. That was discussed before indeed. I believe that the router should use `link.pathname` because it is covering more edge cases then `getAttribute('href')`. However, at the same time I think this should be in the control of the developers. There's a way to overwrite it:
```
var router = new Navigo();
router.getLinkPath = function (link) {
  return link.pathname;
}
```
Let me know if that works for you.

**Comment by tnguyen14** [comment]
I will try that workaround later. However, there are a couple of issues I'd like to raise here:
1. Even if this is a better change, as it is a breaking change, it should be in a major version to respect semver.
2. It might cover more edge case, but clearly it doesn't cover the case where the site lives at a subpath, instead of the main domain path. If you're keeping with this change, perhaps there should be a way to configure it so it'd respect that.

**Comment by krasimir** [comment]
1. I absolutely agree with that. Note taken.
2. The constructor of Navigo accepts two parameters the first one of which is the root path of your app. That's the place where you have to say `mysite.com/app/search`. Otherwise Navigo makes assumptions of your root and pics `app/search` as a root.
