### ISSUE TITLE
JSBin example cannot find navigo.js lib file

### ISSUE THREAD

**Issue by peterdenev** [krasimir/navigo#13]
In JSBin example the navigo.js lib points to [http://work.krasimirtsonev.com/git/navigo/navigo.js](http://work.krasimirtsonev.com/git/navigo/navigo.js) and may be your htaccess redirect the url. 
Just can swich it to [http://krasimir.github.io/navigo/lib/navigo.js](http://krasimir.github.io/navigo/lib/navigo.js)

**Comment by krasimir** [comment]
Fixed. Thanks.
