### ISSUE TITLE
Not work with port in url like http://localhost:8080

### ISSUE THREAD

**Issue by scano** [krasimir/navigo#131]
I try to run your router in a localhost on por 8080 and doesn't work.
Also, I have tried your example with the same result.
Only 404 errors.

I'm using the url http://localhost:8080 and the latest version of the Navigo

My setup:
```html
<html>
.....

<script>
var router = new Navigo();
router.on({
    'page1': function() {
        alert("page1");
    },
    'page2/:gid': function(param){
        alert(param.gid);
    },
    '': function(){
        //alert('home');
    }
    })
    .notFound(function(){
        alert('404');
    })
    .resolve();
</script>

...
<a href="page1" data-navigo>Page1</a>
<a href="page2/xxxxxx" data-navigo>Page1</a>
...
</html>
```
Any idea?

Thanks in advance

**Comment by krasimir** [comment]
@scano what kind of server you use? Are all of your requests going to the same page above. The client-side routing requires that the server forwards every request to a single html file (the above one).

By `doesn't work` do you mean that you click the links and nothing happens. About the 404 errors, is it like you are opening `/page1` or something different then `/` and you see 404?

**Comment by scano** [comment]
@krasimir Yes, Chrome shows a 404 error. 
I'm using a simple http from npm (https://www.npmjs.com/package/http-server) 
Looks like the router not intercept the href.
The same example works fine with Page.js (https://visionmedia.github.io/page.js/) 

Thanks for your time and work,
Regards.
