### ISSUE TITLE
Subrouting

### ISSUE THREAD

**Issue by nschurmann** [krasimir/navigo#132]
For example, i have a route `/dashboard` that will render a sidebar and a top navbar, and everything inside that route, IE: `/dashboard/products` will be rendered as a children of the parent view. Is there a way to achieve this?, if you have an example with just plain javascript will be awesome :)

Amazing library!

**Comment by krasimir** [comment]
@nschurmann I see your point. Unfortunately the idea of Navigo is to deal only with the routing. It shouldn't know about content. What I'll suggest is to have dedicated functions for managing the content. For example:

```js
function renderLayout(content) {
  renderSidebar();
  renderNav();
  render(content);
}
router.on('dashboard/products', function () {
  renderLayout(ProductsPage);
});
router.on('dashboard', function () {
  renderLayout(EmptyPage);
});
```

**Comment by nschurmann** [comment]
Seems great!, btw @krasimir i'm trying to figure out a way to do a rendering based on components but doing only VanillaJS, right now i have something like:

```
function component() {
  const element = document.createElement('div')
  element.innerHTML = 'The children of the components'

  return element
}

// ... somewhere in the app
document.body.appendChild(component())
```

The main purpose is to do a component based development with vanillaJS but i want to render the components only if the state of it changed (i know is very like react, but i want to do it without react and only vanillaJS), also i know that this is very far away from the scope of this repo but still i will lose nothing if i ask you :D

**Comment by krasimir** [comment]
@nschurmann I tried dealing with similar challenges when I was working on [absurdjs](https://github.com/krasimir/absurd). There are two really difficult things to achieve:
* dealing with cascade changes if the state is spread between multiple components
* proper/smart rendering where you batch multiple changes into a single rerender

Kudos for playing with VanillaJS. It is always fun. In some cases where your project is small and has a short-life that approach works :)

**Comment by krasimir** [comment]
I'll this close the issue @nschurmann. Feel free to reopen it or continue comment on it about other topics :)
