### ISSUE TITLE
.navigate results in duplicate routing

### ISSUE THREAD

**Issue by lesansley** [krasimir/navigo#133]
Hi,
I have set my router to:
`router = new Navigo(rootUrl, false)`
and my routing table is:
```
router.on ({  
       '/recover': function () {  
	       setPage('Recover');  
	},  
	'/recover/:view': function (params) {  
	      displayView({view: params.view});  
	}  
})
```
When I call `.navigate` on some (but not all) pages the page is routed twice so that in my history I end up with:
**rootUrl/recover/success
rootUrl/recover/resend#
rootUrl/recover/resend
rootUrl/recover/success
rootUrl/recover/resend#
rootUrl/recover/resend
rootUrl/recover/success**

The behaviour is consistent for a particular call i.e. `router.navigate('recover/success')` the page is only routed once but for `router.navigate('recover/resend')` the page is always routed twice and I end up with `rootUrl/recover/resend#` in the url bar and then in history when I move to the next page. Please could you advise whether this is expected behaviour.

**Comment by krasimir** [comment]
That's interesting. Do you have a live version somewhere so I can debug? I'll suggest to grab the latest `5.0.1` version and see if that bug is fixed there.

**Comment by lesansley** [comment]
I can tunnel through to my localhost with ngrok. Where can I send you the details?

**Comment by krasimir** [comment]
Yep here info@krasimirtsonev.com

**Comment by lesansley** [comment]
krasimir, figured it out. The navigate was called from a link click and the A tag had href=#, but I had forgotten to include event.preventDefault() in the listener. Thanks for your time.
