### ISSUE TITLE
clean method breaks route

### ISSUE THREAD

**Issue by huevoncito** [krasimir/navigo#134]
@krasimir After passing through the `clean` method, the route gets an extra `/^/`  appended to it. The user expects http://myapp.com/about but instead they get http://myapp.com/^/about which is not very user-friendly and also breaks some other things in my app. Also, I see no need to for the extra `^`.

```
function clean(s) {
	  if (s instanceof RegExp) return s;
	  return s.replace(/\/+$/, '').replace(/^\/+/, '^/'); // < second replace causes the problem
}
```
Can't we just make it `return s.replace(/\/+$/, '').replace(/^\/+/, '/');` instead?

Thanks!
db

**Comment by krasimir** [comment]
@huevoncito are you using the `clear` method directly. I'm asking because I created this page:

```js
<!DOCTYPE html>
<html>
<head>
<script src="../navigo.js"></script>

<script>

  var router = new Navigo(null, false);

  router.on({
    '/:photoid': function (params) {
      console.log(params);
    }
  }).resolve();

  function goto(where) {
    router.navigate('/' + where);
    // router.resolve();
  }

  router.on({
    '/trip/:tripId/edit': { as: 'trip.edit', uses: () => {} },
  });

  console.log(router.generate('trip.edit', { tripId: 42 }));

</script>
<body>
  <a href="javascript: goto(10);">10</a><br />
  <a href="javascript: goto(20);">20</a><br />
  <a href="javascript: goto(30);">30</a><br />
  <a href="about" data-navigo>About</a><br />
</body>
</html>
```

And it all works fine with the latest 5.0.1 version. I didn't see any `^` in the routes.

**Comment by huevoncito** [comment]
No, I'm not calling it directly. My setup is like this:

```
router.on('about', function (params) { ...do stuff });
router.resolve();
```
When the content loads, I call `updatePageLinks()`, which attaches a listener to the links. That listener calls `self.navigate(clean(location));`, where `location === '/about'`, which is correct. However `clean` returns `/^/about`.

**Comment by krasimir** [comment]
Ouch ... yep, you are absolutely right. Just fixed it in `5.0.2` version. Let me know if it works:
![image](https://cloud.githubusercontent.com/assets/528677/26668318/dd235212-46b1-11e7-8241-149c1334246a.png)

**Comment by huevoncito** [comment]
@krasimir That does it. I'll pull from npm and confirm before closing.

**Comment by huevoncito** [comment]
Confirmed. We're good @krasimir . Thanks.
