### ISSUE TITLE
Nav if already at location

### ISSUE THREAD

**Issue by finppp** [krasimir/navigo#136]
It would be great to have a hook for if the target location is 'already' active eg

```
  .on(
    '/my-posts',
      function () {
          navHome()
          scrollTop()
    },
    already: function () {
      scrollTop()
    }
  })
```

As currently this will not call the .on function if you are already at /my-posts. Alternatively it would be great to have a function to enable re-triggering of the .on function

Thanks for all your help!

**Comment by lesansley** [comment]
This would be a very handy feature. Currently I am having to put in a work around to get this functionality.

**Comment by krasimir** [comment]
Yep, definitely. Will come the next couple of days.

**Comment by krasimir** [comment]
`5.1.0` released containing the already hook.

**Comment by finppp** [comment]
very quick, Thanks!
