### ISSUE TITLE
Generic hooks do not get route parameters

### ISSUE THREAD

**Issue by faunti** [krasimir/navigo#137]
Having read the documentation, I got the impression that generic hooks would receive paramteres sent to parameterized routes. This is the part that says it:

> Also notice that both hooks receive params in case they are attached to a parameterized route.

However, it does not work like I expected. Here is my code:

HTML:
`<a onclick="router.navigate('firstroute/foo/bar')">first</a>`

JavaScript:
```
router = new Navigo(null, true, '#!');

router.hooks({
        after: function (params) { console.log("after all: ",params) }
});
router.on({
        // 'view' is the id of the div element inside which we render the HTML
'firstroute/:test': () => { loadHTML('./templates/firstroute.html', 'view') },

router.resolve();
```

I debugged the issue and found out that in the _resolve_ function, when the function _manageHooks_ on line 339 was called, the parameters of the matched route are not sent. So, if the code looked like this, it would work:

```
manageHooks(function () {

    manageHooks(function () {

        m.route.route instanceof RegExp ? handler.apply(undefined, _toConsumableArray(m.match.slice(1, m.match.length))) : handler(m.params, GETParameters);
        }, m.route.hooks, m.params, _this2._genericHooks);
    }, this._genericHooks, m.params);
```

Only difference is sending  m.params at the very end.

**Comment by krasimir** [comment]
Very good catch. 5.2.0 now released containing your fix.

**Comment by philsbury** [comment]
@krasimir is there going to be a tagged [release](https://github.com/krasimir/navigo/releases) of this?

**Comment by krasimir** [comment]
It's done. I stopped tagging the releases because I was doing it only because of bower. However, I [read couple of articles](https://www.google.bg/search?q=is+bower+going+away&oq=is+bo&aqs=chrome.0.69i59j69i60j69i57j0l3.2494j0j1&sourceid=chrome&ie=UTF-8) that bower is going away and people encourage the community to use npm instead.

**Comment by philsbury** [comment]
@krasimir Thank you.

It's a debate that keeps coming up. I think a lot of people are still using it, especially for more CSS driven projects, but maybe it's time for me to make the switch to do everything via npm.

**Comment by krasimir** [comment]
Now, when you are rising this up makes me think that it's maybe too early to drop the tagging of the releases. I'll continue tagging the new versions (if I don't forget :) Probably have to automate it at some point)

**Comment by philsbury** [comment]
It's a tricky one, you'll never please everyone I suppose. If it can be automated then everyone's a winner! :)
