### ISSUE TITLE
[feature request] include a current route name in an object returned by the lastRouteResolved() method

### ISSUE THREAD

**Issue by wujekbogdan** [krasimir/navigo#144]
The `lastRouteResolved()` returns an object that contains just the `url` and `query` fields. It would be great if the route name was also included there.

At the moment it's doable, but requires accessing "private" `_routes` property (which is not an elegant solution).

``` javascript
var currentUrl = router.lastRouteResolved().url;
var currentRoute = router.helpers.match(currentUrl, router._routes);
var currentRouteName = currentRoute.route.name;
```

**Comment by krasimir** [comment]
It's one. `5.3.1` now contains `.name` property.

**Comment by wujekbogdan** [comment]
Great. Thank you!
