### ISSUE TITLE
Separation of Concerns

### ISSUE THREAD

**Issue by hanoncs** [krasimir/navigo#145]
I was going to use this in a project that does not have webpack. Can I ask why the base lib/navigo.js is a webpack module? Do you have the vanilla js version on a different branch?

**Comment by krasimir** [comment]
The https://github.com/krasimir/navigo/blob/master/lib/navigo.js file is just fine for vanilla js apps. That's because

```
(function webpackUniversalModuleDefinition(root, factory) {
	if(typeof exports === 'object' && typeof module === 'object')
		module.exports = factory();
	else if(typeof define === 'function' && define.amd)
		define("Navigo", [], factory);
	else if(typeof exports === 'object')
		exports["Navigo"] = factory();
	else
		root["Navigo"] = factory();
})(this, function() {
```
sends `this` as a root which if loaded on page via script tag is the `window` object. So `window.Navigo` points to the library.
