### ISSUE TITLE
Change the URL without invoking the callback (pause)

### ISSUE THREAD

**Issue by elibyy** [krasimir/navigo#147]
Hey there,
I Think you should add the ability to choose if `pushState` or `replaceState` will be used in pause mode.

Since there might be a time when you want to update the URL without resolving and allow the user to go back to the other URL, but then it should resolve the callback.

**Comment by krasimir** [comment]
@elibyy it's done I added a new method for your use case - `historyAPIUpdateMethod`. Check out the test to see how it works. https://github.com/krasimir/navigo/blob/9c11bcf9fa58bf08b109422e2ec4c2812fe7fa4f/test/spec/issues/147.spec.js

**Comment by elibyy** [comment]
@krasimir thank you very much for this addition, one more thing, the URL won't resolve on `history.back` since the other URL is set in `_lastRouteResolved`

**Comment by krasimir** [comment]
@elibyy hm ... can you come with a test case. I'm not sure that I understand.

**Comment by elibyy** [comment]
Yup. I have a flight results page and current search editor which allows you to change the itinerary, so i want that change to be reflected in the URL. So example URL
`/search?from=NYC&to=AMS`
Hope that clears it up

**Comment by krasimir** [comment]
Hm ... but as far as I can see `_lastRouteResolved` is set once the route is resolved. So is it like you are changing the URL but not not resolving?

**Comment by elibyy** [comment]
Yeah. I see no reason to re-render everything. But i want to fake a navigation so that it will respond on back press

**Comment by krasimir** [comment]
Hm ... that's a little bit of a design decision. I'll try to put that logic outside of Navigo because the `_lastRouteResolved` should be changed only if we have the resolving done. I'm not sure how you implemented your app but is it possible to allow the resolving just do nothing in the handler.

**Comment by elibyy** [comment]
@krasimir  sorry you are right, fixed it to be on the `before` hook

**Comment by krasimir** [comment]
👍
