### ISSUE TITLE
Way to check referring route

### ISSUE THREAD

**Issue by WilNichols** [krasimir/navigo#15]
Looking for a way to fire different functions on a given route, but only depending on which route was last visited. Is there already a way to do this?

**Comment by krasimir** [comment]
Hi @WilNichols,

nope currently there is no such functionality. I'm keen keeping libraries simple and single-purpose modules. The requested feature sounds like a custom app specific thing. I'll suggest to create a local variable and keep track of what is called lately. What you think?
