### ISSUE TITLE
Newest version doesn't work with my Parameterized URL

### ISSUE THREAD

**Issue by McLive** [krasimir/navigo#151]
I have this route: **/domain/1**

I'm using this code: 
`var router = new Navigo(root = null, useHash = false);

        router.on({
            '/domain/:id': function (params) {
                $.ajax({
                    type: 'GET',
                    url: '/domain/' + "1" + '/json/get-records',
                    datatype: "json",
                    contentType: "application/json charset=utf-8",
                    success: function (data) {
                        //domain.records(data[0].fields);
                    }
                }).always(function () {
                    //website.loading_columns(false);
                });
            }
        }).resolve();`
But it simply doesn't run that ajax call. I tried an older version I still have on my computer and that code does work pretty fine. (https://dr0p.it/9lk_)

What am I doing wrong?

**Comment by krasimir** [comment]
Can you try without a slash in front - `domain/:id`. Or maybe set the root to `/`.

**Comment by McLive** [comment]
With root = `null`
`/domain/:id` and `domain/:id` doesn't work

With root = `/`
`/domain/:id` doesn't work

`domain/:id` works!

Thank you :+1:
