### ISSUE TITLE
[BUG] generic leave hook not being called

### ISSUE THREAD

**Issue by elibyy** [krasimir/navigo#152]
all over the script there's calls to[`_callLeave`](https://github.com/krasimir/navigo/blob/master/src/index.js#L438)

but there's no call to the generic leave

**Comment by krasimir** [comment]
Sorry, what you mean by `generic leave`.

**Comment by elibyy** [comment]
leaving any route

**Comment by krasimir** [comment]
A generic `leave` is not supported at the moment.

**Comment by krasimir** [comment]
This is now supported into the new 8.0.0 version. As of today it is still not released. Soon this will happen. In the meantime if anyone is interested (3+years after this issue is lastly commented) use the navigo@beta version.

**Comment by krasimir** [comment]
Here's the commit that covers this functionality with a unit test https://github.com/krasimir/navigo/commit/75f1a89e6865275a8bfedb21898e2eb4c071fbbb
