### ISSUE TITLE
Documentation of routes order confusing

### ISSUE THREAD

**Issue by crazyshot** [krasimir/navigo#153]
The order of routes adding **do matter**. The URL which is added earlier and matches wins. 
...
Have in mind that the order of the added routes using this method **does not matter anymore**. However, if we add series of routes by calling on multiple times we should consider the order of the calls.

**Comment by crazyshot** [comment]
I think route depth significance should also be documented.

**Comment by krasimir** [comment]
Good spot. The README is changed.
