### ISSUE TITLE
extractGETParameters doesn't care for #

### ISSUE THREAD

**Issue by elibyy** [krasimir/navigo#155]
Hey there,

if you are using real URL's and not via hash the url might be /some/route#popup
but `popstate` event is still triggered and the match for current route is not matched ` GETParameters === this._lastRouteResolved.query`
because `this._lastRouteResolved.query === '/some/route'` and `GETParameters = '/some/route#popup'`
and it should be ignored IMO

Thanks

**Comment by krasimir** [comment]
This is now fixed in version 8.0.0. It is not published at the moment officially but it is accessible via `yarn add navigo@beta`.
