### ISSUE TITLE
Example with working history?

### ISSUE THREAD

**Issue by maximilianberndt** [krasimir/navigo#156]
I've built my site with navigo and everything works fine, except when I go back manually, my site breaks. Eg. pressing the back button on my browser or swiping to the right on my phone.

Is there an example with a working history?

**Comment by krasimir** [comment]
Hello,

Thank you for using Navigo.
Can you please post an example of your route definitions? What you mean by "breaks"?

**Comment by maximilianberndt** [comment]
Ok so I just realized what the problem is.

In my JS file I have an array that looks like this and holds the information about what elements should be displayed:

`var pages = [
  {
    path: "weave",
    position: -10,
    title: "Weave",
    subtitle: "Augmented<br>Fitness<br>Device",
    subtitle2: "2017",
    navClose: false,
    navNumber: 1,
    displayViewProject: "block",
    displayBackButton: "none",
    displayLangButton: "block",
    displayFooter: "none"
  },`

By using a global position I keep track on which page I am currently on. When using the back button this variable is not being updated.

**Comment by maximilianberndt** [comment]
Ok, solved by detecting ajax requests:

`_send = XMLHttpRequest.prototype.send;
XMLHttpRequest.prototype.send = function() {

    /* Wrap onreadystaechange callback */
    var callback = this.onreadystatechange;
    this.onreadystatechange = function() {             
         if (this.readyState == 4) {

            console.log("ajax request");

         }

         callback.apply(this, arguments);
    }

    _send.apply(this, arguments);
}`

from this thread: https://stackoverflow.com/questions/10783463/javascript-detect-ajax-requests

**Comment by krasimir** [comment]
I'm glad that you solved your problem.
