### ISSUE TITLE
Using Navigo with /

### ISSUE THREAD

**Issue by Didexe** [krasimir/navigo#159]
I am trying to set up my app to use Navigo with / instead of #. I am initializing the router with:
`const router = new Navigo(null, false)`
`const router = new Navigo('/', false)`
`const router = new Navigo(null, false, '/')` 
but none of these works. What is the correct way to do it?

A second issue is when I try to navigate to the home page after login with:
`router.navigate('#home')` but it just adds it to the current route and it becomes /#login#!home
What is the correct way to do it?

Another issue is when I manually reload any page it stays on the same page but loads the home page content. My routes are as follows:
`router.on({`
      `'admin': () => showAdminPage(),`
      `'login': () => showLoginPage(),`
     `'signup': () => showSignupPage(),`
     `'logout': () => logoutUser(),`
     `'home': () => showHomePage(),`
     `':category': (params) => showCategoryPage(params),`
     `':category/:post': (params) => showPostPage(params),`
    `})`
    `.resolve();`

**Comment by surmind** [comment]
try this:
`const router = new Navigo()`

**Comment by krasimir** [comment]
a) If you don't wanna use hash based routing but the history API use `const router = new Navigo()`
b) It should be `home` (without `#`). If you make it work with the history API is again just `navigate('home')`
c) Calling resolve means getting the current URL and try matching it to some of the registered routes. If you open manually `example.com/home` then you'll probably see the home page. If that's not the desired behavior try adding slashes in front of your route definitions. Like for example `admin` becomes `/admin`

**Comment by Didexe** [comment]
Thanks!

**Comment by TheMangoTrain** [comment]
Hey, this helped me too.

I wanted "/page" type of routes (aka history.state method), not "#page" or "#!page" (aka hash-bang method). There was no clear direction to make this happen on first install.

Most important, besides the ABC steps above, you cannot test the history.state method when directly opening the html file in your local web browser... browsers will throw a security error. You must open it via an HTML server *somewhere*, whether it's a local server or online. Conversely, the hash-bang method DOES work locally when opening the HTML file directly. This threw me off initially.

So:

Define the router like:
`const router = new Navigo()`

Define routes like:
```
router.on({
  // 'view' is the id of the div element inside which we render the HTML
  'firstroute': () => { loadHTML('./templates/first.html', 'view') },
  'secondroute': () => { loadHTML('./templates/second.html', 'view') },
  'thirdroute': () => { loadHTML('./templates/third.html', 'view') }
});
```

And do work and test in an actual HTML server, as opening an HTML directly in the browser (via file:// url) won't work.

It might be useful to have direction on the Navigo github home page, "How to setup for history.state method".

thx!

**Comment by tirtha4** [comment]
Can't use the history API even after using `const router = new Navigo()`

Is there any other work around?

**Comment by Allakazan** [comment]
i used  ´const router = new Navigo()´ , still don't working with /

**Comment by Allakazan** [comment]
That's my code:

``` 
router.notFound(function () {
    // called when there is path specified but
    // there is no route matching
  });
```
