### ISSUE TITLE
Route fires twice

### ISSUE THREAD

**Issue by JeffBurrows** [krasimir/navigo#16]
I have this:

```
router.on('/pub/:pub', function (params) {
		console.log("route 2");
		gotoPageTwo(params.pub);
	});
	router.on('/', function (params) {
		gotoPageOne();
	});

```
When I am on "route 2" page and refresh, the route then fires twice.

Any ideas?

**Comment by krasimir** [comment]
Every call of the `on` method [triggers](https://github.com/krasimir/navigo/blob/master/src/index.js#L119) the routes resolving. Can you please use the following syntax so you have only one check:

```js
router.on({
  '/pub/:pub': function (params) {
    console.log("route pub");
  },
  '/': function (params) {
    console.log("default");
  }
});
```
