### ISSUE TITLE
extractGETParameters return Object

### ISSUE THREAD

**Issue by emiliogrv** [krasimir/navigo#161]
Hi, I have an idea of return Object instead of string, like as:

               function extractGETParameters(url) {
                    let query = {}
                    let temp

                    url = url.split(/\?(.*)?$/).slice(1).join('').split('&')
                    url.forEach(function (item, index) {
                        temp = item.split('=')
                        query[temp[0]] = temp[1]
                    })

                    return query;
                }

What do you think?

**Comment by krasimir** [comment]
Thanks for the suggestion. That's how it works now in the latest version 8.0.0.

```js
const router = new Navigo('/');

router.on('/user/:id/:action', ({ data, params, queryString }) => {
  console.log(data); // { id: 'xxx', action: 'save' }
  console.log(params); // { m: "n", k: "z" }
  console.log(queryString); // "m=n&k=z"
});

router.resolve('/user/xxx/save?m=n&k=z');
```

P.S.
version 8.0.0 is not released officially yet but you can try the beta release - `yarn add navigo@beta`.
