### ISSUE TITLE
Route is not resolved when only using query parameter in URL

### ISSUE THREAD

**Issue by mr678** [krasimir/navigo#162]
Hi,
I'm using ` "navigo": "^5.3.2"`.

I have following code:

    var router = new Navigo(null, true, '#!');
    router.on({ '/home': function (query) { 
         console.log('router->on query:', query); 
         mainApp.loadCtrl(HomeCtrl, query)
      }
    });

Calling `http://localhost:3000/#!/home` works - route is found.
Calling `http://localhost:3000/#!/home?q=test` is not working - route is not found.

If I use a param, like in the example on github project page, it's working:

    router.on({ '/home/:useless': function (params, query) { 
         console.log('router->on query:', query, 'params', params); 
         mainApp.loadCtrl(HomeCtrl, query)
      }
    });

Calling `http://localhost:3000/#!/home/x` is working!
Calling `http://localhost:3000/#!/home/x?q=test` is working!

If I have just a query param without parameterized URLs, the URL is not resolved.

Do you have any idea what I'm doing wrong?

Thanks,
Matthias

**Comment by Datamance** [comment]
Same exact issue over here!

**Comment by krasimir** [comment]
@mr678 @Datamance can you please try 5.3.3 version.

**Comment by mr678** [comment]
@krasimir works! :-) Thank you so much for providing a fix so fast 👍
