### ISSUE TITLE
Global before hook except for 1 page

### ISSUE THREAD

**Issue by ultimate-tester** [krasimir/navigo#163]
I would like to use the global before hook to check if I have a valid login session:

```
router.hooks({
        before: function (done, params) {
            if (global.sessionId === -1) {
                router.navigate('/login/');
                return;
            }

            done();
        }
    });
```

This creates an infinite loop, because even on the login page the sessionId is -1. Since I want my full website to be protected by this sessionId check, I would like to know how I can have this global hook for every route except for the /login/ route. Thanks in advance!

**Comment by krasimir** [comment]
With the latest 8.0.0 release you'll be able to do the following:

```js
router.hooks({
    before: function (done, match) {
      if (window.sessionId === -1 && match.url !== "login") {
        console.log("redirect to login");
        router.navigate("/login");
        return;
      }
      done();
    },
  });
```

The second argument of the hook is a [Match](https://github.com/krasimir/navigo/blob/big-rewrite/DOCUMENTATION.md#resolving-routes) object. You can use its `url` field to check what's the path that matched.

P.S.
as of today version 8.0.0 is not released officially. You could have the beta one by running `yarn add navigo@beta`.
