### ISSUE TITLE
URL with query string not working on root

### ISSUE THREAD

**Issue by klbytec** [krasimir/navigo#165]
I saw this issue [https://github.com/krasimir/navigo/issues/122](https://github.com/krasimir/navigo/issues/122) was closed in May. I was using an older version (from June maybe) and now upgraded to version 5.3.3 and the similar problem is happening to me except reversed.

I set:
`var router = new Navigo(null, false); router.on({ '/hello/': function (params, query) { console.log("query="+query); }}).resolve();`

I am using Chrome. With the above setting, using the old version, the path `/hello/` works but `/hello/?q=1` won't resolve.  However, using version 5.3.3, the path `/hello/` stopped working but `/hello/?q=1` worked.  I am not using navigate, I am putting the urls in the browser window and hit enter/reload.  They both should load the same page, just that page optionally takes the GET parameters to do some ajax calls.

In the browser with url that has query string, in browser console I put in `router.resolve("/hello/?q=1")` and it returned "query=1". So it seems ok.

Then there is another post I read and I tried: `new Navigo(location.origin, false);`
It worked for both above, but it caused another problem because I have two routers, one doesn't use hash and one uses hash. 

`var router2 = new Navigo(null, true);router2.on({'/*': function () {console.log('my single page app');}}).resolve();`

 So when navigate using the router using hash, my path becomes `/hello/?q=1#/mypage/` while I expect it to be `/hello/#/mypage/`

Can someone please help me with what the proper way is to set it so a page can work with and without query string?  Thanks!

**Comment by klbytec** [comment]
After trying some more with version 5.3.3, I found out that one simple slash in the setting for the paths made a whole difference.  My problem was from doing this:

`'/hello/': {`
`            as: 'front-page.hello', uses: function () {`
`                console.log('1');`
`                initFront();`
`        }},`
`'/': {`
`            as: 'front-page', uses: function () {`
`                console.log('1');`
`                initFront();`
`        }}`

So with the above:

'/hello/' resolves for:
http://mysite.com/hello/?q=1


'/' resolves for:
http://mysite.com/
http://mysite.com/?q=1
http://mysite.com/hello/


That made no sense, so now change from `/hello/` to `/hello`:

'/hello' resolves for:
http://mysite.com/hello/
http://mysite.com/hello/?q=1


'/' resolves for:
http://mysite.com/
http://mysite.com/?q=1

Everything is good.

Is this how it's supposed to be?  If there is a caveat/comment or documentation about this, If so then I apologize for not seeing it.

**Comment by krasimir** [comment]
In the latest v8.0.0 the problem is solved. Not officially released but you can get it via `npm install navigo@beta`.
