### ISSUE TITLE
Subroutes does not work

### ISSUE THREAD

**Issue by mggrand** [krasimir/navigo#166]
I have got a very simple route definition but somehow "subroutes" does not work. Assuming I have got this index.html file:

`<a href="first" data-navigo>First</a>`
`<a href="second" data-navigo>Second</a>`
`<a href="third" data-navigo>Theard</a>`
`<a href="/Offer/test" data-navigo>Test1</a>`
`<a href="/Offer/test2" data-navigo>Test2</a>`
`<div id="view"></div>`
`<script src="js/navigo.js"></script>`
`<script src="scripts.js"></script>`

and my scripts.js looks like this:
`router = new Navigo("http://localhost/");`
` router.on({`
`    '/Offer/test': function (params) {`
`        $id('view').innerHTML = 'offer test';`

`    },`
`    '/:action': function (params) {`
`        $id('view').innerHTML = params.action + ".html" ;`
`    },`
`    '/Offer/:action': function (params) {`
`        $id('view').innerHTML = 'offer '+ params.action + ".html" ;`
`    }`
`});`

So when I load the page in the browser everything is fine. Then I click on the first link and the browser displays "first.html" which is also correct. After that I click on Test1 and the location of the url changes to "http://localhost/Offer/test", everything is fine. But now, when I click again on "First" the url changes to "http://localhost/Offer/first".

I tried to remove the "/" in the a tags as well as in the route configuration. Also i tested the same procedure without providing a root url. Same behavior.

Any idea how I can solve this problem?

**Comment by shoxv** [comment]
I believe version 5 broke or changed something with subroutes. might want to switch to version 4xx for now till @krasimir comments.

**Comment by shoxv** [comment]
You actually want the / in the a tags e.g. '/first'

**Comment by krasimir** [comment]
@mggrand is what @shoxv suggested fixed the issue?

**Comment by mggrand** [comment]
As I sad in one of my last sentences, I‘ve tried the routes with a slash and without one. Both did not work for me. Thank you

**Comment by krasimir** [comment]
@mggrand a 6.0.0 version released. Can you please try it out. It should fix your problem.
