### ISSUE TITLE
Parameterized routes do not work without the root route.

### ISSUE THREAD

**Issue by shoxv** [krasimir/navigo#167]
Since version 5.3, parameterized routes don't work if a root route isnt there. For example:

/products/:id

wont work if there isn't already a route named

/products

This used to work previous to version 5.

**Comment by krasimir** [comment]
Good catch. I'll investigate.

**Comment by krasimir** [comment]
@shoxv can you please try with the latest `5.3.3` version. I think it may be fixed there. Just added a test and it passed.

**Comment by shoxv** [comment]
@krasimir I did try with 5.3.3, still getting the issue.

I tried to set up some kind of fiddle but it's too difficult due to routing, so I just recorded a video. Hope it helps illustrate the issue. Could be something wrong with my specific setup?
[navigo_testcase.zip](https://github.com/krasimir/navigo/files/1481226/navigo_testcase.zip)

**Comment by krasimir** [comment]
I just reproduced the _bug_. It is the same issue as in https://github.com/krasimir/navigo/issues/111 When we initialize Navigo without a root it tries to find it on its own. That process depends on the added routes. It works in your case when you have two routes and Navigo has enough information to find out the `root`. But once you remove it it thinks that the route is `http://localhost:9019/products` and can not resolve `products/:id`. So initialize Navigo with:
```js
const router = new Navigo('http://localhost:9019/');
```

**Comment by shoxv** [comment]
gotcha, thanks man!
