### ISSUE TITLE
How to tell navigo to wait?

### ISSUE THREAD

**Issue by jjones3535a** [krasimir/navigo#168]
I want to configure navigo to wait for Firebase to login (or logout) before rendering any route.

I've seen navigo has a before hook, but it seems this is an immediate callback, and I haven't quite figured out how I would make react-router wait until firebase triggers an firebase.auth().onAuthStateChanged(...) event.

Does navigo  include some functionality to handle such cases?

**Comment by krasimir** [comment]
Well, the before hook accepts a `done` method. You handle your async logic and call `done` after that. Isn't it this working? If so, can you please post an example of your code here.
