### ISSUE TITLE
Named routes and URL generation

### ISSUE THREAD

**Issue by daviestar** [krasimir/navigo#17]
Hey

I love this router and have used it on a lot of small projects with no issues, thanks!  I'm now scoping a larger project, and there's one thing stopping me from using it there (well two related things).  

Some example routes:

```javascript
const trip = new TripController();
router.on({
  '/trip/:tripId/edit': trip.edit,
  '/trip/create': trip.create,
  '/trip/:tripId': trip.show,
  '/trip': trip.index
});
```
An example for a named route API (using [Laravel 5.2 API](https://laravel.com/docs/5.2/routing#named-routes) as inspiration):
```javascript
const trip = new TripController();
router.on({
  '/trip/:tripId/edit': {as: 'trip.edit', uses: trip.edit},
  '/trip/create': {as: 'trip.create', uses: trip.create},
  '/trip/:tripId': {as: 'trip.show', uses: trip.show},
  '/trip': {as: 'trip.index', uses: trip.index}
});
```
Then using the custom names, we don't need to hardcode URLs in th views:
```html
<a href="{{ router.generate('trip.show', {tripId: 6}) }}">...</a>
```

**Comment by krasimir** [comment]
Nice idea and definitely possible. I'll try implementing it during the weekend.

**Comment by krasimir** [comment]
It's done. Version `1.3.0` released. I followed your API proposal. It's added to the README [here](https://github.com/krasimir/navigo#named-routes).

**Comment by daviestar** [comment]
Thanks!  Very small and elegant solution!

**Comment by daviestar** [comment]
I've been implementing the naming/generate pattern and so far it's working great.

It's lead me to another idea though, let me know what you think:

Since I'm making a SPA with a server behind, I have GET routes that Navigo controls, and another set of routes for talking to the server using GET/POST/PUT/DELETE, for example:

```javascript
/**
 * Store a newly created resource in storage.
 * @param  tripId : string
 * @param  lngLat : array
 * @param  time : int
 */
store({tripId, lngLat, time}) {
  api('post', 'api/trip/'+tripId+'/locations', {lngLat, time}, response => {

    //

  });
}

form.on('submit', store);
```
Keeping all the routes in one place (via Navigo `on()`) and generating them when necessary would be great for this scenario too, but you wouldn't want them to be accessible in the browser address bar.

So what I thought was, these routes could have `as: 'name'`but no callback `uses: handler` (or possibly `private: true`?), so trying to visit them in the address bar, or clicking on a link would do nothing, but you could still use the `generate('name', params)` functionality.

Good idea?  Too far?

**Comment by daviestar** [comment]
Ok, I have been working on this and given it a lot more thought.

I like that Navigo has no concerns about AJAX method, but a lot of server-side routes are the same but with different methods.  The best API for this kind of thing I could come up with:
```javascript
router.private({
  'api.trip.update': {uri: '/api/trip/:tripId'},
  'api.trip.destroy': {uri: '/api/trip/:tripId'},
  'api.trip.show': {uri: '/api/trip/:tripId'},
  'api.trip.store': {uri: '/api/trip'}
});
```
Matching these routes: https://laravel.com/docs/5.2/controllers#restful-resource-controllers

**Comment by daviestar** [comment]
I made tiny extension which fits my needs:
```javascript
import Navigo from 'navigo';
import assign from 'object-assign';

/**
 * Private routes map
 * @param map
 */
let privateRoutes = {};
Navigo.prototype.private = (map) => {
  privateRoutes = assign(privateRoutes, map);
};

/**
 * Router singleton
 * @returns object
 */
const router = new Navigo();
export default router;

/**
 * Uri generator
 * @returns uri
 */
export function route(name, data = {}) {
  let uri = router.generate(name, data);
  if(!uri && privateRoutes[name]) {
    for(var key in data) {
      uri = privateRoutes[name].replace(':' + key, data[key]);
    }
  }
  return uri;
}
```
routes.js:
```javascript
router.on({
  '/trip/create': {as: 'trip.create', uses: trip.create},
  '/trip/:tripId/edit': {as: 'trip.edit', uses: trip.edit},
  '/trip/:tripId': {as: 'trip.show', uses: trip.show},
  '/trip': {as: 'trip.index', uses: trip.index}
});

router.private({
  'api.trip.destroy': '/api/trip/:tripId'
});
```
some-view.jsx:
```jsx
import React from 'react';
import {route} from '../helpers/router';

export default () => (
    <a href={route('trip.show', {tripId: 6})}></a>
);
```
some-other-place.js:
```
import {route} from '../helpers/router';
const uri = route('api.trip.destroy', {tripId: 6});
```

**Comment by krasimir** [comment]
Kudos for extending Navigo. Even though it seems logical I'll probably not add this to the library. It's because this is covering kinda custom case. For me the client-side router is a single-responsibility thing and I'll probably not use it for a back-end related task. What I can do in such cases is probably define the routes in a configuration place and then pass the configuration to these both places.

**Comment by daviestar** [comment]
Yeah, after thinking it's great to decouple different parts of my SPA by responding just to routes, I'm now finding it's pretty limited - you can't really pass any other parameters around other than the URL (of course).

So in the end I agree that this has a limited use case.  Cheers.
