### ISSUE TITLE
Is it possible to make routes case insensitive?

### ISSUE THREAD

**Issue by seanhak** [krasimir/navigo#170]
How can I setup so all routing is handled lowercase so I dont have to worry about variants.

I want /shop/, /shOp/ & /SHOP/ to use the same handler.

Thanks

**Comment by FRSgit** [comment]
Hey,
Please have a look here, 2 lines above "Tests" headline - [https://github.com/krasimir/navigo#tests](navigo github main page).

Hope I've helped!

**Comment by krasimir** [comment]
Yep @FRSgit is right. You may use `Navigo.MATCH_REGEXP_FLAGS = 'i'`.
