### ISSUE TITLE
Using "#!" is deprecated

### ISSUE THREAD

**Issue by vikramdurai** [krasimir/navigo#171]
<https://webmasters.googleblog.com/2015/10/deprecating-our-ajax-crawling-scheme.html>

**Comment by krasimir** [comment]
Good point.

**Comment by ultimate-tester** [comment]
As far as I can see, they are deprecating their advice. They are not advising anything new, meaning: As long as the site allows its Javascript files and stylesheets to be indexed, it will be indexed fine. You don't have to follow the strict /#!/ anymore, but could also completely omit it.. Navigo should be fine continue to use it as standard.
