### ISSUE TITLE
/area/:id doens't work

### ISSUE THREAD

**Issue by heitorfm** [krasimir/navigo#173]
I´m trying to use the url path parameter, but in all cases that i have a variable in the parameter Navigo doesn't recognize the url, and doesn't do the route. So Navigo always choose the default mapping.
The navigate method works, but when i hit the url in the browser it doesn't.

```
let router = new Navigo();
    router.on({

            "/area/:id": function (params) {
                   mountPage(params.id);
            },
     });
        router.on(function () {
            console.log("default")
            mountDefault();
        });

    router.resolve();
```

The url that i´m trying is:
http://localhost:8080/area/fin

I´ve tryed without the port number, but same result

The version that i´m using is the master, but i tryed the:
https://cdn.jsdelivr.net/npm/navigo@6.0.0/lib/navigo.min.js

With last firefox and crhome presenting the same behavior

Just found out that if i hit this url:
http://localhost:8080/area/:id
Navigo finds the right mapping ...

**Comment by krasimir** [comment]
Can you please initialize the Router with
```
let router = new Navigo('http://localhost:8080');
```
I want to confirm something.

**Comment by heitorfm** [comment]
yep, it worked !!

**Comment by krasimir** [comment]
That's something I have to address soon but in the mean time the router works better when there's root set up.

**Comment by justinffs** [comment]
I am having this issue too, seems like a legit bug is there a reason it is closed?
Also is this documented in the README?

**Comment by krasimir** [comment]
Just update the README and now contains this:

> The constructor of the library accepts three argument - `root`, `useHash` and `hash`. The first one is the main URL of
your application. If you call the constructor without parameters then Navigo figures out the root URL based on your routes. However, this proves to lead to bugs so I strongly recommend to set a `root` value.

The thing is that this _guessing_ bit doesn't work if you have just a few routes. We can't just pick the current one because you may visit the page within a nested URL. So the `root` must be set in order to get Navigo working properly. In the future version this will be a mandatory parameter and you'll simply see an error.

**Comment by justinffs** [comment]
Just a thought ... why not use regex to get the first part or the url and default the root to that?
Something simple like?
```
/^(https?)://[^\s/$.?#].*?\/`/
```

Or there is `window.location.origin` although [older browsers don't support it](https://developer.mozilla.org/en-US/docs/Web/API/Window/location#Browser_compatibility) but a [polyfill would be simple](https://tosbourn.com/a-fix-for-window-location-origin-in-internet-explorer/).

```
if (!window.location.origin) {
  window.location.origin = window.location.protocol + "//" + window.location.hostname + (window.location.port ? ':' + window.location.port: '');
}
```

**Comment by krasimir** [comment]
That's because people (including me) use Navigo in a nested URL like `http://site.com/myproduct/app/` and the root for the router should be `http://site.com/myproduct/app` not `http://site.com`.
