### ISSUE TITLE
Handler ignored if hooks.already is the only hook

### ISSUE THREAD

**Issue by ze6ke** [krasimir/navigo#174]
I think that I understand the intended usage correctly.  I created a route that has a handler, but doesn't have either before or after handlers.  The primary handler is never called.  Looking at the manage hook code, it looks like it needs one more else statement after the after handler.

Here's my test case that wasn't behaving correctly.
```
router.on('/page.html/', handler, {already:alreadyHandler})
```

This is the manageHooks code as it currently stands.
```
function manageHooks(handler, hooks, params) {
	  if (hooks && (typeof hooks === 'undefined' ? 'undefined' : _typeof(hooks)) === 'object') {
	    if (hooks.before) {
	      hooks.before(function () {
	        var shouldRoute = arguments.length > 0 && arguments[0] !== undefined ? arguments[0] : true;
	
	        if (!shouldRoute) return;
	        handler();
	        hooks.after && hooks.after(params);
	      }, params);
	    } else if (hooks.after) {
	      handler();
	      hooks.after && hooks.after(params);
	    }
	    return;
	  }
	  handler();
	};
```
I think that adding this last else block would fix it and not have unintended side effects.
```
else if (hooks.after) {
	      handler();
	      hooks.after && hooks.after(params);
	    }
else //neither before or after was declared on this set of hooks, so we should call the handler normally {
	      handler();
}
```

**Comment by pastaclub** [comment]
Same problem for `leave` hook (#182)
The solution provided by @ze6ke will fix both.

**Comment by krasimir** [comment]
@ze6ke @pastaclub thank you for the suggestions. Indeed that was a bug. I think both issues may be solved by the new 7.0.0 version. Can you please try it out and let me know.

**Comment by pastaclub** [comment]
I tested this one as well, it's also working now (in my implementation).

**Comment by ze6ke** [comment]
Same for me.  Thanks for the fix.

Also, I didn't get a chance to mention it before.  Thanks for the library and the writeups.  Those were good reads.
