### ISSUE TITLE
Print in chrome

### ISSUE THREAD

**Issue by theeedannyd** [krasimir/navigo#175]
Hi,

When I press print in chrome, the app refreshes and the the print window disappears. I believe this to be a routing issue but dont know how to fix it.

Any idea at all?

Many thanks

**Comment by DeDu** [comment]
Does not happen in my app. Are you sure it's navigo?

**Comment by theeedannyd** [comment]
My humble apologies, it was a strange bug, navigo was my last resort but I
worked it out. Thanks

**Comment by krasimir** [comment]
No worries.
