### ISSUE TITLE
On first-loading, do not trigger matched route

### ISSUE THREAD

**Issue by TheMangoTrain** [krasimir/navigo#177]
Hello,

Is there a way to configure Navigo to ignore a matched route on initial page loading?

For example:

I have an SPA, and the server also sends out fully-rendered pages. Essentially this means I have multiple entry points into my SPA.

Given the following route "articles/bob/456"... if I enter that directly into the browser, the server sends a fully rendered page, and it's the content the user should see; no ajax/navigo needed until they interact with the page.

However, Navigo recognizes that route on the page load. The route gets matched right away and Navigo does it's thing.

So what I end up seeing is a flash of content... for a moment I see the initial server-rendered content... then when Navigo kicks in, it see's the matched route, and re-renders the content. Ultimately I do want the Navigo functionality as part of the SPA, but only when the user starts interacting with the page ie clicking on a link.

I believe this issue might be on the same topic, yes no? https://github.com/krasimir/navigo/issues/64

**Comment by krasimir** [comment]
Can you please try to not call the `resolve` method when you are on the client.
```js
router
    .on({
      '/:photoid': function (params) {
        console.log(params);
      }
    })
    .on({
      '/trip/:tripId/edit': { as: 'trip.edit', uses: () => {} },
    })
    .resolve(); // <---- kill that on the client side
```
This is what kicks the default url check. So if you run it when server-side  and don't when you are on the client it should behave as you described.

**Comment by TheMangoTrain** [comment]
That works! thanks
