### ISSUE TITLE
replaceState

### ISSUE THREAD

**Issue by individual8** [krasimir/navigo#18]
Is there a way to replace the current state, instead of just push via navigate()?

For changing language I'm looking for such functionality, since changing language is not really navigating away from the current content.

**Comment by krasimir** [comment]
@individual8 just released a new version `2.0.1`. Can you please check this solution https://github.com/krasimir/navigo#pausing-the-router

**Comment by individual8** [comment]
Thx for the update, @krasimir.

It generally seems to work the way intended. I think one issue's still that you're adding that "paused" navigate() to the list of routes. Hence, it's breaking browser's back history.

**Comment by krasimir** [comment]
I see. That's because we are using `pushState` to change the URL. If we use `window.location.href` we'll reload the page. If we use hashes then will be possible to avoid that.

But to be honest I would prefer to have that in the history.

**Comment by individual8** [comment]
Wouldn't something like this solve that?
`overwrite: function overwrite(path, absolute) {
      path = path || '';
      if (this._ok) {
        history.replaceState({}, '', (!absolute ? this._getRoot() + '/' : '') + clean(path));
        this.pause(true);
        this.resolve();
        this.pause(false);
      } else if (typeof window !== 'undefined') {
        window.location.href = window.location.href.replace(/#(.*)$/, '') + '#' + path;
      }
      return this;
    }`

**Comment by krasimir** [comment]
So maybe it's a matter of using `replaceState` instead of `pushState` because
> history.replaceState() operates exactly like history.pushState() except that replaceState() modifies the current history entry instead of creating a new one. Note that this doesn't prevent the creation of a new entry in the global browser history.

**Comment by individual8** [comment]
Not sure why, but it seems that `2.0.1` won't resolve '*' (Home) anymore btw.

**Comment by krasimir** [comment]
Can you try with `2.0.3`. It [uses](https://github.com/krasimir/navigo/blob/master/lib/navigo.js#L162) `replaceState` if the router is paused.

**Comment by individual8** [comment]
Works the way intended, thank you.

**Comment by hirasso** [comment]
Hi there, I would need the `replaceState` option without navigo being paused, I have a scrollSpy on my site that should change the url with events being fired on scroll, but if the user would hit the back button he should not have to go through all the entries.
