### ISSUE TITLE
Refresh current page

### ISSUE THREAD

**Issue by elrapha** [krasimir/navigo#180]
Is it  possible to refresh the page you are already on by navigating to the same url. 
Or trigger a page refresh

**Comment by krasimir** [comment]
Hello,

What's your server setup? Is it a node app or it is served by apache? Are you pointing all the request to the same index file.

**Comment by elrapha** [comment]
Well i am using hash urls. Much like the last one there (same index file) so i just need the page to refresh when I navigate to the same page.

**Comment by krasimir** [comment]
Do you have that page somewhere online so I can see how it works.

**Comment by elrapha** [comment]
I managed to figure it out. Instead of navigating to the same url, I just call the page rendering function that is called by the router at that url.  Then the page refreshes fine. 

I think you misunderstood my question though. What i was saying was that i call router.navigate("mypage") then i make some api calls which should affect the data on the current page. These changes are only visible after a page refresh. but when i call router.navigate("mypage") again, the page does not refresh (and rightfully so since i am already on that link). So what i do instead is just call the page rendering function directly
