### ISSUE TITLE
For a route, handler does not get called but hook gets called

### ISSUE THREAD

**Issue by pastaclub** [krasimir/navigo#182]
```
    router.on('/sim', ()=>{
      console.log('enter sim');
    }, {leave: ()=>{ 
      console.log('leave sim');
    }});
```
When navigating to /sim, the handler ('enter sim') does not get called, but when navigating from /sim to another route, leave gets called.

Am I doing something wrong or is this a bug?

**Comment by pastaclub** [comment]
Also enter does not work, while leave works:

```
    router.on('/sim', ()=>{}, {
      enter: ()=>{ console.log('enter sim'); },
      leave: ()=>{ console.log('leave sim'); }
    });
```

**Comment by pastaclub** [comment]
This is another effect of the bug pointed out in issue #174

**Comment by krasimir** [comment]
Thanks for rising this up. The new 7.0.0 version will probably indeed fix this one too. Can you please try it out.

**Comment by pastaclub** [comment]
I tried it and I can confirm it's fixed now. Thank you!
