### ISSUE TITLE
An export assignment cannot be used in a module with other exported elements after update 4.0.4

### ISSUE THREAD

**Issue by VsLoureiro** [krasimir/navigo#183]
I Started having this error after 4.0.4 update.

ERROR in [at-loader] ./node_modules/@types/navigo/index.d.ts:62:1 
      TS2309: An export assignment cannot be used in a module with other exported elements.

**Comment by dancespiele** [comment]
@VsLoureiro sorry I was working with it, try to update it now, the version 4.0.5 works fine,

**Comment by VsLoureiro** [comment]
@dancespiele Yes it works fine now! Thanks!
