### ISSUE TITLE
Try to understand methods to continue to work in \@types for navigo

### ISSUE THREAD

**Issue by dancespiele** [krasimir/navigo#185]
I would like to understand some methods how works and what is the the type values expected to add to \@types/navigo (right that I have to change the version to 6):

could someone show me please some examples with the methods `off()`, `.updatePageLinks()`, `historyAPIUpdateMethod` and the type of value for `off()`, `getLinkPath`, `historyAPIUpdateMethod`?

when is the `already` hook executed? because I test the hooks but `already` never is executed

**Comment by dancespiele** [comment]
I request new changes in @types, I think that everything is typed. Finally I understood the methods `updatePageLinks()` and `getLinkPath`, but I continue don't understand the methods off(), `historyAPIUpdateMethod()` and `disableIfAPINotAvailable()`. Supposedly when I change the history method to replaceState `historyAPIUpdateMethod('replaceState')` and execute `disableIfAPINotAvailable()` it should disable the routers but I continue have access to them:

```
it('has to disable the routers', (done) => {
            router.pause()
            router.historyAPIUpdateMethod('replaceState');
            router.disableIfAPINotAvailable();
            router.resume();
            router.navigate('/');
            setTimeout(() => {
                const element = document.getElementsByTagName('h1')[0];
                expect(element.textContent).has.not.to.be.equal('Hello world');
                done();
            });
});
```
The test fail because I have still access to this path. Also happen with `off()`:

```
it('has to remove a router', (done) => {
            router.pause();
            router.off({
                '/child/:number?answer=42': { 
                    as: 'child', uses: (params, query) => {
                        Object.assign(testPage2.state, params);
                        render(testPage2.view, testPage2.state);
                    } 
                }
            });
            router.resume();
            router.navigate('/child/6');

            setTimeout(() => {
                const title = document.getElementsByTagName('h1')[0];
                if(title) expect(title.textContent).has.not.to.be.equal('Seriously 6');
                done();
            })
})
```
Surely I don't understand it. Because of this my comment here. 
Anyway good job @krasimir

**Comment by krasimir** [comment]
Hey, sorry for the delay. 

* The `off` method is suppose to do what `on` does. I.e. remove a route listener.
* `historyAPIUpdateMethod` is here because a developer came with the case where `pushState` method of the [history API](https://developer.mozilla.org/en-US/docs/Web/API/History_API) is not quite ok. He wanted to use `replaceState`. So if it happens that this is your case too you can set it here and the router will use that instead of the default `pushState`.
* `disableIfAPINotAvailable` is designed to stop the router only if the [history API](https://developer.mozilla.org/en-US/docs/Web/API/History_API) is not available in the browser.

In your first test you are just changing the API method that the router uses but the whole API is still there so the router is still working. In the second example you have to provide the same route + the same handler to make it work. For example:

```js
router.on('/path', handler);
router.off('/path', handler);
```

**Comment by dancespiele** [comment]
@krasimir I make this test:

```
it('has to remove a router', (done) => {
            router.pause();
            router.on('/example', (params, query)=> {
                render(testPage4.view, testPage4.state);
            });
            router.resume();
            router.pause()
            router.off('/example', (params, query)=> {
                render(testPage4.view, testPage4.state);
            });
            router.resume();
            router.navigate('/example');

            setTimeout(() => {
                const title = document.getElementsByTagName('h1')[0];
                if(title) expect(title.textContent).has.not.to.be.equal('Hello brother');
                done();
            })
        });
```
the on is the same than off but I have still access to the path.
About the `historyAPIUpdateMethod` and `disableIfAPINotAvailable` could you provide how I could test them please?

**Comment by krasimir** [comment]
As of version 8.0.0 Navigo has its types bundled into the library. Also the library is written in TypeScript.

P.S.
Version 8.0.0 is not officially released but can be installed via `npm install navigo@beta` or `yarn add navigo@beta`. Migration guide is available here https://github.com/krasimir/navigo/blob/big-rewrite/CHANGELOG.md#migration-guide and the new documentation here https://github.com/krasimir/navigo/blob/big-rewrite/DOCUMENTATION.md.
