### ISSUE TITLE
IE9: weird navigation, possible solution inside

### ISSUE THREAD

**Issue by EdwinHauspie** [krasimir/navigo#189]
In IE9, pushstate is not available, and function _navigate: function (path, absolute)_ causes weird behaviour when **not** using a hash.

When I want to go to "/contact", it will go to "#/contact" and doesn't take into account if you are not using the hash.

I think the solution must be (line 194 in source code):

window.location.href = window.location.href
          .replace(/#$/, '')
          .replace(new RegExp(this._hash + '.*$'), '') + **(this._useHash ? this._hash : '')** + path;

Thank you

**Comment by handijk** [comment]
The hash is a requirement to fake pushState functionality in IE9, so not using the hash and supporting IE9 is not an option at all.

**Comment by krasimir** [comment]
Yep, I agree with @handijk.
