### ISSUE TITLE
Any reason for replacing href attribute in binded links?

### ISSUE THREAD

**Issue by individual8** [krasimir/navigo#19]
You replace hrefs with `javascript:void(0);` although `e.preventDefault()` is used. 
Is there a reason for doing so?

**Comment by krasimir** [comment]
Do you mean when you set a `data-navigo` attribute to some `<a>` tag. If yes, we are doing this so the link become a JavaScript only. When we use hashes we don't want to change the actual page.

**Comment by individual8** [comment]
I see. Doesn't `e.preventDefault()` hinder the browser anyway to follow the href target?

I'm thinking it could be worth to leave the href in its original state for people to open it in new tab or for copying.

**Comment by krasimir** [comment]
Yep, you are right. `2.0.4` version released. It only attaches an event handler.
