### ISSUE TITLE
stop routing

### ISSUE THREAD

**Issue by peppeg85** [krasimir/navigo#190]
hello, i need to check if an operation is done, if not i need to remain in the page and don't resolve the route, i've tryed this:
https://github.com/krasimir/navigo/pull/154
but resolve(false) goes loop;
is there a way to stop the routing?
here is my code
`    leave: function (params) {
            console.log("leave");
            if(stop==0){
              router.resolve(false);
            }
          }`

**Comment by krasimir** [comment]
In general such situations should be solved outside of Navigo. Navigo as a router shouldn't be involve in such decisions. There is some API to help with this but if it doesn't cover your case I'll suggest to do your logic upfront. 

I'm not sure how you trigger the page update but if it is a link then simply do like so:

```
<a onClick={ goToPage() }>go to another page</a>

function goToPage() {
  if (myWorkIsDone) {
    router.navigate('/that/other/page');
  } else {
    // sorry you have to wait
  }
}
```

**Comment by peppeg85** [comment]
i use a unique back button and in the router i have a variable updated with the parent directory for each page, so when i press the back button it routes to the parent page. is there also a way to prevent the back button of the browser?

**Comment by krasimir** [comment]
Nope, you can't workaround the back button of the browser. I guess you have to write a better logic in your app.

**Comment by peppeg85** [comment]
it could be workarounded with the window beforeunload event, and it works but only on the page refresh, because with the router only in case of refresh the page unloads all the resources

**Comment by krasimir** [comment]
@peppeg85 this library got re-written. Here's the new documentation https://github.com/krasimir/navigo/blob/big-rewrite/DOCUMENTATION.md. Since this is a 2+ years old issue I'm gonna close it. Please comment below if you still have the case.
