### ISSUE TITLE
Initial state issue

### ISSUE THREAD

**Issue by SagarNaliyapara** [krasimir/navigo#192]
Looks like initial state doesn't work properly,

if i'm at home page with url - '/' and i redirect manually to 'user/slug' and changing url with this,

`window.history.pushState(null, null, '/user/slug')` and it change url but in user page if i click back then it doesn't work.

same thing happen for all url with initial state back button not working all other state works well.

**Comment by krasimir** [comment]
Navigo uses `popstate` event to understand that there is a change in the URL. That event is fired only if the user interacts manually with the buttons of the browser. Using `window.history.pushState` doesn't trigger any logic in the router so it doesn't know that the URL is changed. I'll advice you to use `.navigate()` or call `.resolve()` every time after you do `window.history.pushState`.
