### ISSUE TITLE
Url with only slug doesn't work

### ISSUE THREAD

**Issue by SagarNaliyapara** [krasimir/navigo#193]
If i use url like this 
```
    routes['search/:query'] = function(params) {
        let page = new SearchPage(params.query);
        pageStore.showPage(page);
        page.showSearchMenu(params.query);
    }; // WORKS
```
then this one works but if i use as following it doesn't work,

```
    routes[':query'] = function(params) {
        let page = new SearchPage(params.query);
        pageStore.showPage(page);
        page.showSearchMenu(params.query);
    }; // NOT WORKING - This one redirecting me to Home Page
```

**Comment by krasimir** [comment]
There is a new version 8.0.0 where this works and it is covered with a unit test https://github.com/krasimir/navigo/blob/big-rewrite/src/__tests__/basic.spec.ts#L239-L246

P.S.
Version 8.0.0 is not officially released but can be installed via `npm install navigo@beta` or `yarn add navigo@beta`. Migration guide is available here https://github.com/krasimir/navigo/blob/big-rewrite/CHANGELOG.md#migration-guide and the new documentation here https://github.com/krasimir/navigo/blob/big-rewrite/DOCUMENTATION.md.
