### ISSUE TITLE
Setting root doesn't work.

### ISSUE THREAD

**Issue by 0x00000F5C** [krasimir/navigo#195]
As documented, I set a root when initiating the library
`new Navigo(location.origin + "/", true, "#!");`

But whenever I use the .navigate() method, it will always append new hash to existing path rather than appending it to root.

e.g.
`new Navigo("http://localhost/", true, "#!");`
from `http://localhost/test` clicked `.navigate("#!/something")` I get `http://localhost/test#!/something` rather than `http://localhost/#!/something`

**Comment by krasimir** [comment]
That is correct. I mean your example illustrates how Navigo should work. The reason of this behavior is that you are mixing the two types of routing. Passing `true` as second arguments means that you wanna use a hash-based routing while `/test` is using the history api type of routing. So you either go with `http://localhost/#!/test` or `http://localhost/test` but say `.navigate('something')`. Also when you are calling `navigate` you don't have to add `#!`.

**Comment by 0x00000F5C** [comment]
I see, I mistaken what was said in the documentation.

I'm closing the issue.
