### ISSUE TITLE
Is there a way to run reload?

### ISSUE THREAD

**Issue by killmenot** [krasimir/navigo#196]
@krasimir Hi,

Thanks for the nice lib.

Is it possible to run reload for router to re call routing logic. Example:
```
router.navigate('/users'); # -> API.getUsers() called, ui rendered with users
API.deleteUser(123); # User clicks a button, some API method called
router.reload(); # -> to back to the step 1 above and then update ui
```

**Comment by killmenot** [comment]
The only way I found that allows me to do a reload is the following:

```js
const currentUrl = router._lastRouteResolved.url
router._lastRouteResolved = null;
router.navigate(currentUrl);
```
But this solution has issues with `leave` [logic](https://github.com/krasimir/navigo/blob/master/src/index.js#L434-L440)

**Comment by krasimir** [comment]
Hey,

I'll suggest to shift this concerns out of the router. I mean at the end you have functions/handlers that Navigo fires right. So why not define the handlers as named functions and call them when after you update the data:

```
function showUsers() { ... }
router.on('/users', showUsers);

// later on
router.navigate('/users');
API.deleteUsers(123);
showUsers();
```

Following this approach you'll decouple the rendering of the routing.

**Comment by killmenot** [comment]
@krasimir Yes, it also works but require me to update the code. Thank you.

**Comment by cb109** [comment]
Wrapping @killmenot approach into a more convenient method. Using a 'leave()' with this worked for me.

```javascript
Navigo.prototype.forceNavigate = function(path, absolute) {
  if (absolute === undefined) {
    absolute = false;
  }
  this._lastRouteResolved = null;
  this.navigate(path, absolute);
}
```

**Comment by makveli** [comment]
Sorry i really don't understand why not implement a router.reload() function,,, ? Congratulations this is amazing project.
