### ISSUE TITLE
Retrieve params within a route

### ISSUE THREAD

**Issue by s43** [krasimir/navigo#197]
Hello Krasimir,

First of all, much thanks for the awesome work on Navigo, I how simple it handles things !

I'd like to know if there's a way to retrieve params within a route ( ex. product/:id ), I'd like to do it using just Navigo Methods ( If it's possible, and I doubt it cause I searched within the code and nothing appears to handle such a case… correct me if I am wrong ).

I'd sort it out myself with some additional JS, if this isn't an existing feature I'd be glad to share my thoughts about it …

Thanks in advance for your reply.

**Comment by krasimir** [comment]
Hello,

yep, there is such a feature - [parameterized urls](https://github.com/krasimir/navigo#parameterized-urls).
