### ISSUE TITLE
Absolute Path vs Relative Path

### ISSUE THREAD

**Issue by individual8** [krasimir/navigo#20]
Another issue I found is the use of relative paths vs. absolute paths.

You declare links in data-navigo attributed links with relative paths (eg. "about"). The router declares "/about" though. Somehow the link still trigger the particular route, but end up in doubled slashes in the address bar (eg. somedomain.com//about).

**Comment by krasimir** [comment]
Can you please try with the new `2.0.5` version. I think the problem is reproducible if the `root` passed to Navigo ends up with `/`.

**Comment by individual8** [comment]
In my case, I didn't define `root` specifically.

`2.0.5` seem to work though.
