### ISSUE TITLE
Child paths inside parent paths

### ISSUE THREAD

**Issue by jfftck** [krasimir/navigo#200]
It would be great if this was bound to an instance of a child router.

```javascript
router
  .on('/player/:id', function (params, query) {
    // Get player information 
    this.render(function () {
      // Display player information
    })

    this.onRender('/stats', function () {
      // Using the information from the parent we can look up the stats of the player
    })
  })
```

So, route `/player/joe` would give you details on that player and display the contents of the `this.render(...)`, but `/player/joe/stats` would skip the first render method and display the contents of the `this.onRender('/stats', ...)` method. By using the power of closures, it would allow much smaller code and keep from creating helper functions for the routes that have a parent and child relationship.

Also, the onRender method is just a shortcut to doing the following:
```javascript
this.on('/stats', function () {
  this.render(function () {
    // Display stats
  })
})
```

**Comment by jfftck** [comment]
The other option is to pass in the router as a parameter, so it can work with es2015+ arrow functions, like this:
```javascript
router
  .on('/post/:id', router => {
    // Get post
    const id = router.params['id']
    // Fetch the post data, unless child route does not use this data then fetch in the render
    router.render(() => {
      // Display post
    })

    router.onRender('/comments', () => {
      // Display comments
    })
  })
```

Notice how all the render methods don't get the router passed in since they are for displaying the contents and not resolving routes.

**Comment by krasimir** [comment]
Interesting suggestions. I'm now in a process of rewriting Navigo. I'll consider the examples above. Thanks.

**Comment by krasimir** [comment]
Hey @jfftck,

I was thinking a lot how to provide such functionalities but every time when I tried became so convoluted. The main issue is to protect the router from re-registering the same routes. Also it kinda pushes the library to rendering concerns which is not the overall idea of the project. Sorry, but this time I'll park this feature.
