### ISSUE TITLE
Mounting to an element?

### ISSUE THREAD

**Issue by nedpals** [krasimir/navigo#201]
Hi, just a quick question. I'm coming from making apps using traditional client-side routers where there is a mounting point where I can only render it on a portion of a page. My question is, does Navigo have this? Skimming the whole docs seems nowhere to be found (or I must have just crossed it). If not do you have any plans for it? Thanks.

**Comment by krasimir** [comment]
Hey, sorry, there is no such concept in the current version of Navigo. I'm currently rewriting the library and I'll definitely do that for React based apps.

**Comment by nedpals** [comment]
Oh okay thanks. Looking forward for the rewrite :smiley:
