### ISSUE TITLE
Accessing elements in view after navigation

### ISSUE THREAD

**Issue by maximilianberndt** [krasimir/navigo#202]
I am trying to add a class to access the loaded elements in the view div after navigation. It works fine on the initial load but after navigating I can't access them anymore. Is there a hook that tells me when the content is fully loaded and parsed?

These are my current hooks:

```
router.hooks({
  before: function(done, params) { 
  	done(); 
  },
  after: function(params) {
	$( document ).ready(function() {
		$('.animate').each( function(){
			console.log(this);
		});
	});
  }
});
```

**Comment by krasimir** [comment]
Hey, I'm afraid that this is not a router concern. You have to deal with the situation using jQuery's API.

**Comment by maximilianberndt** [comment]
Thanks! I was able to select the elements using plain javascript. Not sure why jquery is not working.
