### ISSUE TITLE
Improvement: Leave hook handler needs passing done callback

### ISSUE THREAD

**Issue by kostyanet** [krasimir/navigo#205]
Leave hook handler needs passing done callback the same way it's being passed into the enter hook handler. This one is needed to prevent leaving pages containing unsaved form data, etc.

**Comment by krasimir** [comment]
Good suggestion. I'll add it to my list for the rewrite of the library which is happening now.

**Comment by krasimir** [comment]
Navigo has been re-written and in the latest version 8.0.0 the `latest` hook accepts a function that allow us to block (or completely prevent) the leaving of a route. Documentation [here](https://github.com/krasimir/navigo/blob/big-rewrite/DOCUMENTATION.md#hooks).

P.S.
Version 8.0.0 is not officially released but can be installed via `npm install navigo@beta` or `yarn add navigo@beta`. Migration guide is available here https://github.com/krasimir/navigo/blob/big-rewrite/CHANGELOG.md#migration-guide and the new documentation here https://github.com/krasimir/navigo/blob/big-rewrite/DOCUMENTATION.md.
