### ISSUE TITLE
Preventing url change on href

### ISSUE THREAD

**Issue by leonardorame** [krasimir/navigo#208]
Hi, I would like to know if it's possible to do some action when a user clicks on some `<a href...>`, but avoid changing the url in the browser.

I thougth this could be done with an `before` hook and `done(false);` but it still let the browser change the url.

**Comment by krasimir** [comment]
Hello,

how’s your link looks like? 

Best regards

**Comment by krasimir** [comment]
There is a new release 8.0.0 coming soon. In there you'll be able to do the following:

```html
<a href="/foo/bar" data-navigo data-navigo-options="updateBrowserURL:false, updateState: false>my link</a>
```

Which will only call your route handler without updating the browser URL and the internal state of the router.

P.S.
Version 8.0.0 is not officially released but can be installed via `npm install navigo@beta` or `yarn add navigo@beta`. Migration guide is available here https://github.com/krasimir/navigo/blob/big-rewrite/CHANGELOG.md#migration-guide and the new documentation here https://github.com/krasimir/navigo/blob/big-rewrite/DOCUMENTATION.md.
