### ISSUE TITLE
How to check a url match to any routes?

### ISSUE THREAD

**Issue by hotcacao** [krasimir/navigo#209]
Hello everyone,

First of all, thank you for your great project very much.

Unfortunately I can not find out any way to check a url that matches the any routes from an instance of Navigo router. However, I think that there must be a way that Navigo can verify matching between routes and urls.

So, can you export to a new method similar:

> // Init router
> var router = new Navigo();
> router.on("/app/:appId", function(){});
>
> router.match("/app/123"); // ==> true or route details
> router.match("/apps/456"); // ==> false or null

Thanks in advance.

**Comment by xwisdom** [comment]
Hi,

Try using the resolve() method:

> `var result = router.resolve(url);`

**Comment by hotcacao** [comment]
Hi @xwisdom 

_**router.resolve(url)**_ means to redirect to the _**url**_  if the _**url**_  is existed in the configuration.

What I mentioned the in previous post is how to check whether the _**url**_ existed in the configuration or not.

So your code does not help me much.

**Comment by krasimir** [comment]
Navigo got re-written (version 8.0.0) and now this is possible via a method called `match`. For example:

```js
const r: Navigo = new Navigo("/");

r.on("/user/:id", () => {});

console.log(r.match("/nope"));
// result: false

console.log(r.match("/user/xxx/?a=b"));
// result:
//   {
//     data: {
//       id: "xxx",
//     },
//     params: { a: "b" },
//     queryString: "a=b",
//     route: {
//       handler: [Function],
//       hooks: undefined,
//       name: "user/:id",
//       path: "user/:id",
//     },
//     url: "user/xxx",
//   }
```

P.S.
Version 8.0.0 is not officially released but can be installed via `npm install navigo@beta` or `yarn add navigo@beta`. Migration guide is available here https://github.com/krasimir/navigo/blob/big-rewrite/CHANGELOG.md#migration-guide and the new documentation here https://github.com/krasimir/navigo/blob/big-rewrite/DOCUMENTATION.md.
