### ISSUE TITLE
Adding a route by starting "'#" and Parameterized

### ISSUE THREAD

**Issue by milmaj** [krasimir/navigo#210]
I have 3 following urls:

domain.com/@username
domain.com/@username/:someOtherParameter
domain.com/@username/:someOtherParameter/edit

How can I let navigo handle this kind of url, recognize the '#'-starting part and make username a parameter. 

```
router
  .on('/(@):user/:id/edit', function (params, query) {
    // If we have http://site.com/@user/xxx/edit parameters should be:
    // params.user = user
    // params.someOtherParameter = xxx
  })
  .resolve();
```

**Comment by krasimir** [comment]
There is a new release navigo@beta (beta version of the new 8.0.0) where the following applies:

```js
router
  .on("/@:user/:id/edit", (match) => {
    console.log(`edit=${JSON.stringify(match.data)}`);
  })
  .on("/@:user/:id", (match) => {
    console.log(JSON.stringify(match.data));
  })
  .on("/@:user", (match) => {
    console.log(JSON.stringify(match.data));
  })
  .resolve();
```

Which in case of

* `/@krasimir/xxx/edit` prints `edit={"user":"krasimir","id":"xxx"}`
* `/@krasimir/xxx` prints `{"user":"krasimir","id":"xxx"}`
* `@krasimir` prints `{"user": "krasimir"}`


P.S.
Version 8.0.0 is not officially released but can be installed via `npm install navigo@beta` or `yarn add navigo@beta`. Migration guide is available here https://github.com/krasimir/navigo/blob/big-rewrite/CHANGELOG.md#migration-guide and the new documentation here https://github.com/krasimir/navigo/blob/big-rewrite/DOCUMENTATION.md.
