### ISSUE TITLE
Deepest routes not being respected first

### ISSUE THREAD

**Issue by MartinGeldart** [krasimir/navigo#212]
I'm a GitHub newbie and hope I'm not wasting anybody's times here if this turns out to be a me problem.

I have this router setup:

```
this.Navigo.hooks({
    before: (done, params) => {
        // some tomfoolery
        done();
    }
});

this.Navigo.on({
    '/:region/travel': (params) => {
        // import Travel module
        // some nonsense
    },
    '/:region/travel/car': (params) => {
        // import TravelByCar module
        // some nonsense
    }
)};

this.Navigo.resolve();
```

Navigating to `/london/travel/car` unfortunately triggers the route for `/london/travel`. I navigate using this `Navigo.navigate('/london/travel/car')`. However, if I navigate to that route using the browser's address bar, the correct route is triggered, which just adds to my confusion.

I have tried reordering the routes so the deepest is declared first but that doesn't work and according to the docs it won't with this style of declaration.

Is this issue Navigo's or is it mine?

Navigo 6.1.0

**Comment by MartinGeldart** [comment]
The more research I do on this issue, the more convinced I am that what I'm trying to achieve is referred to as 'nested routes' - a feature that is not supported by Navigo. Could somebody confirm this?

**Comment by krasimir** [comment]
Can you try declaring the two routes in a separate `.on` call.

**Comment by MartinGeldart** [comment]
I just tried declaring the routes separately as you suggested but I get the same result; navigating to `/london/travel/car` triggers both routes.

```
this.Navigo
    .on('/:region/travel/car', (params) => {
        console.log("Route: /region/travel/car");
        // stuff
    })
    .on('/:region/travel', (params) => {
        console.log("Route: /region/travel");
        // stuff
    });
```

**Comment by MartinGeldart** [comment]
Following up;

I thought I would change
