### ISSUE TITLE
Force reload

### ISSUE THREAD

**Issue by yellow1912** [krasimir/navigo#213]
Would be nice to be able to force reload of the current state even if the route stays the same, there are several use cases for this especially when you need to perform the steps inside the specific state again.

**Comment by krasimir** [comment]
Is this helping https://github.com/krasimir/navigo/issues/196#issuecomment-368788107

**Comment by krasimir** [comment]
In the new version 8.0.0 we'll have an `already` hook:

```js
function aboutHandler(match) {
  console.log("About matched");
}
router
  .on("/about", aboutHandler, {
    already: aboutHandler,
  })
```

So if you `navigate` to the same route `/about` the `aboutHandler` function will be fired again.

P.S.
Version 8.0.0 is not officially released but can be installed via `npm install navigo@beta` or `yarn add navigo@beta`. Migration guide is available here https://github.com/krasimir/navigo/blob/big-rewrite/CHANGELOG.md#migration-guide and the new documentation here https://github.com/krasimir/navigo/blob/big-rewrite/DOCUMENTATION.md.

**Comment by badeendjuh** [comment]
I used the global already hook to accomplish the re-execution of the current route like so:

```
router.hooks({
    already: () =>{
        router.getRoute(document.location.pathname).handler();
    }
})
```
