### ISSUE TITLE
No #, no work

### ISSUE THREAD

**Issue by neomicho85** [krasimir/navigo#214]
Do I miss something?

```
<script>
    router = new Navigo(null, false);
    router.on({
      'about': () => { console.log('about'); },
      'home': () => { console.log('home'); },
      'contact': () => { console.log('contact'); }
    });
    router.resolve();
  </script>
```
I don't want to use hash (# or #!) I just want some thing like this: http:// [site-url:port]/about
But that says: The requested URL /navigo/about was not found on this server.
navigo/about doesn' exists, is right, but I just want that the console says 'about' and not redirect to other page, I was specting that navigo resolve that URI. How can I use navigo to do that?

**Comment by neomicho85** [comment]
I'm using **Webpack** + **Node** + **Vanilla Javascript**. No server side language like PHP, or Ruby. There is any configuration in node that you know a need to do to redirect all the request to my index file?
All the project run under **http://localhost:8080** in developer, but in production all the project will run under **https://site-url/customer/**.

**Comment by krasimir** [comment]
Is it like you have an express-like:
```
app.all('*', handler);
```

**Comment by neomicho85** [comment]
No, I'm not using Express. Do you recommend me to use it with navigo?

**Comment by krasimir** [comment]
Actually it doesn't matter as long as all the requests go to the same page where navigo operates. Navigo is a client-side library. It doesn't work on the server yet. You mention `The requested URL /navigo/about was not found on this server` which makes me think that your server-side server code is not catching the URL and it is not serving your html (where navigo operates)

**Comment by neomicho85** [comment]
In my WAMP, I use the **.htaccess** you have in the example folder:

> <ifModule mod_rewrite.c>
>   Options +FollowSymLinks
>   IndexIgnore */*
>   RewriteEngine On
>   RewriteCond %{REQUEST_FILENAME} !-f
>   RewriteCond %{REQUEST_FILENAME} !-d
>   RewriteRule (.*) index.html
> </ifModule>

And everything work as I need. Thx krasimir. My only problem is with my **node** project and the configuration in my **webpack-dev-server**

**Comment by krasimir** [comment]
I see. I'm not sure how `webpack-dev-server` deals with routing. I have the feeling that `http://localhost:9000/something/else` is just not opening your `index.html`.

**Comment by neomicho85** [comment]
Already fixed, in **webpack-dev-server** I just add this
```
module.exports = {
  devServer: {
    historyApiFallback: true,
  },
```

> When using the HTML5 History API, the index.html page will likely have to be served in place of any 404 responses

And everything works perfect.
Thanska a lot krasimir for your time, explanation and help

**Comment by krasimir** [comment]
👍
