### ISSUE TITLE
Non hash routing does not work

### ISSUE THREAD

**Issue by FaBeyyy** [krasimir/navigo#216]
Im trying to use non hash based routing the following:

```javascript
export const router = new Navigo();

router
    .on('/test', function () {
        // display all the products
        new App();
    })
    .resolve();
```

but this still only works when accessing `'#/test'`

**Comment by neomicho85** [comment]
https://github.com/krasimir/navigo/issues/214

**Comment by krasimir** [comment]
Navigo got re-written and it doesn't support hash based routing. I think the problem described in the first post here was wrong initialization of the router. Or maybe testing in an old browser. Anyways in the new version 8.0.0 there is no hash based routing.

P.S.
Version 8.0.0 is not officially released but can be installed via `npm install navigo@beta` or `yarn add navigo@beta`. Migration guide is available here https://github.com/krasimir/navigo/blob/big-rewrite/CHANGELOG.md#migration-guide and the new documentation here https://github.com/krasimir/navigo/blob/big-rewrite/DOCUMENTATION.md.
