### ISSUE TITLE
Navigate Hooks

### ISSUE THREAD

**Issue by tonxxd** [krasimir/navigo#217]
Hi,
Navigo is great!

I was wondering if it was possible to add hooks to the navigate method. 
Something like
`router.navigate(route, absolute, {
   before: () => {},
   after: () => {}
})`

or simpler
`router.on(route, async handler() {})`

and .navigate method return handler itself
`.navigate = () => {
  //...
  return handler()
}`
`await router.navigate(route, absolute)
  //... 
`

It would be useful when route handler is an async function and you want to call an action after route has changed and handler has resolved.

**Comment by krasimir** [comment]
I prefer to follow more declarative approach. I don't plan to add hooks to the `navigate` or `resolve` methods. Sorry.

P.S.
by the way, Navigo is re-written. There is a new version 8.0.0. Not officially published but it is accessible via `npm install navigo@beta`.
