### ISSUE TITLE
Request: a way to disable hash usage at all

### ISSUE THREAD

**Issue by fourpixels** [krasimir/navigo#22]
Hi there,
I just stumbled upon this lightweight router library and I'm pretty delighted of how it works. There's only one problem I'm having:

If the browser does not support `pushState`, the library falls back of using hashes as links. I think it would be nice to have the option to disable that **at all**, because in most cases that means doubling the logic for routing (especially in backend) - with and without hashes.

I also don't like the idea of my old browser checking five times a second what's the url (I mean I really won't need that, not that it's bad as an idea).

I don't know what's the best scenario for doing it - provide another parameter, add public method, I don't know. But I think it would be pretty nice if it can work.

Поздрави :)

**Comment by krasimir** [comment]
Definitely a valid argument. I'll make the change and will let you know.

Поздрави приети :)

**Comment by krasimir** [comment]
Can you please try the new `2.1.0` version. It now has `router.disableIfAPINotAvailable()` method. Call it when just after (or before) the definition of the routes.

**Comment by fourpixels** [comment]
Hi again,
Sorry for the late reply. Honestly, I didn't test it with any old browser as I don't have time now, but I tried using the new function (without the check :-$) and it worked pretty fine. I guess if `pushState` is not supported the fallback will work out pretty well.

Thanks for the prompt fix!

**Comment by joakimbugge** [comment]
Have you considered making disableIfAPINotAvailable() an option property instead? I guess I will have to call this method immediately after instantiation, it may just as well be a constructor parameter/option property.

**Comment by fourpixels** [comment]
I also think providing it as a parameter (even in `opts` param) is better, but I guess we have to think of backward compatibility. And providing every new change as a new parameter will make things look ugly at the end :)

So I would chose opts/settings param with different keys which can be further updated, but it will break older versions, so it's not my call :)

**Comment by krasimir** [comment]
I think that having `disableIfAPINotAvailable` method that does the job is kinda more flexible. That's because the developer decides when to trigger this feature. If it is passed along with the configuration means that the library will trigger the check and will disable the router. So the control is not exactly in the developer's hands.
