### ISSUE TITLE
Selector for data-navigo not specific enough

### ISSUE THREAD

**Issue by weisborg** [krasimir/navigo#220]
Nothing life changing or anything, but recently had an issue where we converted anchor tags to buttons.  Whoever did it forgot to remove data-navigo, so updatePageLinks was trying to get href on a button and throwing weird errors about getting replace for null.  Most of our newer apps just have #! and such in the href and don't need data-navigo anymore, or we have made them buttons to do other things then call .navigate...but some old apps still used it.  The selector could use an a in it to limit to anchor tags.

**Comment by krasimir** [comment]
Thanks. It's fixed and covered with a unit test [here](https://github.com/krasimir/navigo/commit/ab2da713593fd8defc607cf6e92468dec260d676). That's in the newest 8.0.0 version.

P.S.
Version 8.0.0 is not officially released but can be installed via `npm install navigo@beta` or `yarn add navigo@beta`. Migration guide is available here https://github.com/krasimir/navigo/blob/big-rewrite/CHANGELOG.md#migration-guide and the new documentation here https://github.com/krasimir/navigo/blob/big-rewrite/DOCUMENTATION.md.
