### ISSUE TITLE
Navigating to root route not working

### ISSUE THREAD

**Issue by marcohamersma** [krasimir/navigo#222]
Hey, 
In our app I'm trying to navigate away from a route and back to the root (/), but I cannot find a way to do it that will cause the right handlers to fire (I need the UI to react to this transition).

I've added this route to the configuration like this: 
`router.on({ as: 'root', uses: doStuff })`

It doesn't get added to `router._routes` because there's a [conditional preventing that](https://github.com/krasimir/navigo/blob/master/src/index.js#L197-205). 

Even triggering a navigation to `/` doesn't have any effect, because as far as navigo goes it's not an actual route.

Is there a correct way of doing this?

**Comment by krasimir** [comment]
So, just to clarify: you are at let's say `/products/category/43` and you want to reach `/`?

**Comment by marcohamersma** [comment]
Yeah, exactly 🙂

**Comment by krasimir** [comment]
Did you try to add your route with `.on('/', yourHandlerHere)` and then use `navigate('/')`?

**Comment by marcohamersma** [comment]
Ah I just noticed the code I put into the initial post was incorrect ( I loosely paraphrased it from my code, but didn't check up). 

That said, adding the `/` in a separate call seems to have worked, but I could have sworn that I had tried that before 🤔
