### ISSUE TITLE
extra slash when force reload using navigate

### ISSUE THREAD

**Issue by marioz82** [krasimir/navigo#223]
@krasimir Hi,

First of all thanks for the nice lib.

I need to force reaload after post operation.
Snippets from my code are:

```
router = new Navigo(window.location.origin, true, '#!');
//	router = new Navigo();
  lastViewVisited='';
  
  var navigoResolve = router.resolve.bind(router);

router.on({'
/page1': () => { $(function(){
    	//some stuff...
}); }
  });

//the event which needs reload
$(document).ready(function() {
//some stuff ...
router.navigate('/page1');
});
```
The url is 
http://localhost:8080/#!/page1

the url is not working due to the extra slash.

Any ideas about what is my mistake?

Thanks

**Comment by krasimir** [comment]
Is it working if you say `router.navigate('page1');`?

**Comment by marioz82** [comment]
No, nothing happens. I've inserted some debug messages and i verified that the router is not called.

In the sidebar of my application, for href link, I use <a href="page1" data-navigo> and works correctly.
The problem is only with navigate.

**Comment by krasimir** [comment]
Navigo just got rewritten and I know that this is two years old issue, but I'll kindly ask to try with the new version. Which by the way doesn't support hash based routing anymore. I'll close this issue for the time being. Let me know if you need to reopen it.

P.S.
Version 8.0.0 is not officially released but can be installed via `npm install navigo@beta` or `yarn add navigo@beta`. Migration guide is available here https://github.com/krasimir/navigo/blob/big-rewrite/CHANGELOG.md#migration-guide and the new documentation here https://github.com/krasimir/navigo/blob/big-rewrite/DOCUMENTATION.md.
