### ISSUE TITLE
New parameter on Generic Before hook

### ISSUE THREAD

**Issue by sipmann** [krasimir/navigo#224]
I would suggest add one more parameter to the generic before hook with the "current url" value. This way we can do checks BEFORE a specific url get loaded.

```javascript
router.hooks({
    before: function (done, params, url) {
        if (url === 'private')
            done(false);

        done();
    }
});
```

**Comment by krasimir** [comment]
Hey,

can you try using `router. lastRouteResolved()`? I think it is what you need.

**Comment by sipmann** [comment]
Sup,
I could be wrong (i'm don't have access to the code), but I tried this and the first call always get "null" as a result. Latter I'll try to post some code.

**Comment by sipmann** [comment]
Yeap, following the test I did and the console.log print `null`. What I want to do, is check if is `url === 'login'` and `!isAuthenticated()` return done(true); 
Right now, to work, i just have to put the login in a separated file.

```javascript
let router = new Navigo(null, false);

router.hooks({
  before: function(done, params) {
    console.log(router.lastRouteResolved());

    if (!isAuthenticated()) {
      done(false);
      //window.location.href = '/login.html';
    } else
      done();
  }
});

router.on('/tickets', () => loadContent('tickets').then(() => ticketsController()))    
  .on('/', () => loadContent('dashboard').then(() => dashboardController()))
  .on(() => loadContent('dashboard').then(() => dashboardController()))
  .resolve();
```

**Comment by krasimir** [comment]
Hm ... for the very first time I think it is fine to be `null`. Is it always `null` even you navigate through other pages.

**Comment by sipmann** [comment]
Well, then ty :)
