### ISSUE TITLE
absolute link URL data-navigo not correct

### ISSUE THREAD

**Issue by masihjahangiri** [krasimir/navigo#225]
Thank you for your library.
when use data-navigo for absolute link like `<a href="http://example.com/x/y" data-navigo>y</a>` URL Not set correctly.
if current url is 'http://example.com/x' when clicked on above link URL will change to 'http://example.com/x/http://example.com/x/y'.

**Comment by masihjahangiri** [comment]
easy way to solve this by jquey:
```
$('a[data-navigo-masih]').on('click',function (e) {
        e.preventDefault();
        router.navigate($(this).attr('href'), true);
});
```

**Comment by krasimir** [comment]
Hello,

well, I would suggest to avoid adding `data-navigo` to absolute URLs. I mean if you don't want to have a link processed by the library you should not add the attribute to the tag. Is there any specific reason for having both - absolute URL and `data-navigo` attribute?

**Comment by krasimir** [comment]
I'll stick to my suggestion (two years ago) :) and will add that if you want to have a bug-free experience with Navigo you should use just `/x` instead of `http://example.com/x`. I'll close the issue. Let me know if you still need assistance and I'll reopen it.

**Comment by masihjahangiri** [comment]
Thanks @krasimir
