### ISSUE TITLE
When entering directly into a page /bike/1234 the root Url isn't calculated correctly

### ISSUE THREAD

**Issue by pjfsilva** [krasimir/navigo#226]
I understand it's very clearly stated you should manually set the root url for Navigo to work properly but I still feel this can be improved or it's a bug.

So basically I have a router with routes:
```` 
router
    .on({
        'bike/:id': function (params) {
        },
        'homepage': function () {
        },
        '*': function () {
        }
    });
````

The problem I detect is if go directly to `http://localhost/bike/123` Navigo doesn't calculate the root URL properly so it falls into the '*' route. 

If I add another 'fake' route: `bike` then root URL can be properly calculated from that route and everything works as expected so that's why I'm thinking this can be improved and is indeed a bug.

I narrowed it down to this line:
````
function root(url, routes) {
  var matched = routes.map(function (route) {
    return route.route === '' || route.route === '*' ? url : url.split(new RegExp(route.route + '($|\/)'))[0];
  });
```` 

Because the result is that when this works there is one matched link that correctly says `http://localhost`and when it doesn't work it just returns the full `http://localhost/bike/123` url.

**Comment by pjfsilva** [comment]
Just guessing from that RegExp I think there may be 2 issues:

1) Routes still keep the placeholders for params: `bike/:id` so that route will never match the URL. maybe we should replace all placeholders with something like `(.*)`
1) 
`"http://localhost:9000/bike/123".split(new RegExp("bike/"))` -> split works
`"http://localhost:9000/bike/123".split(new RegExp("bike/($|\/)"))` - split stops working

So that ($|\/) at the end breaks when tested routes have a '/', not sure what was the intent of that last part in the regexp.

**Comment by krasimir** [comment]
I know that this is a two years old issue but I'll kindly ask to try with the latest `navigo@beta` version. It is a complete rewrite of the route and I think this is not happening there.

P.S.
I'll close the issue. Let me know if you need any help and will reopen it.
