### ISSUE TITLE
All request redirected to default path.

### ISSUE THREAD

**Issue by ghost** [krasimir/navigo#227]
I am using navigo on NodeJS and all of my requests redirecting to default path (`'*'` or `'/'`). In HTTP Request Handler Function i am calling `router.navigate(path).resolve()`. If i calling `navigate(path)` without `resolve()` - router ignored. How to solve this problem?

P.S.
All routes i defined in router.js

```
var router = new Navigo();

router.on(
{
   /* ----- PAGE ------------------------------------- */
    '/page/:name': function(params, query)
    {
      content.load('page', params.name);
    },

  /* ----- TAG ------------------------------------- */

    '/tag/:name': function(params, query)
   {
        content.load('tag', params.name);
    },

  /* ----- FEED ------------------------------------- */

  '/feed/:id': function(params, query)
   {
       content.load('feed', params.id);
    },

    /* ----- INDEX ------------------------------------- */

    '/': function(params, query)
   {
       content.load('index');
    },
})


/* ----- 404 -------------------------------------- */

.notFound(function(query)
{
	content.load('404');
});
```

**Comment by krasimir** [comment]
Navigo is not made to work under Node unfortunately. It is just for the browser which I'll fix in the next big release.

**Comment by krasimir** [comment]
> the next big release

That moment came (finally). The version 8.0.0 is here and could be installed via `npm install navigo@beta`. The following works:

```js
const Navigo = require("navigo");

const express = require("express");
const app = express();
const port = 3000;

app.get("*", (req, res) => {
  function render(content) {
    res.header("Content-Type", "text/html");
    res.send(content);
  }
  const router = new Navigo("/");
  router
    .on("page/:name", (match) => {
      render(match.data.name + " page");
    })
    .on(() => {
      render("home page");
    })
    .notFound(() => {
      render("not found page");
    });

  router.resolve(req.originalUrl);
});

app.listen(port, () => {
  console.log(`Example app listening at http://localhost:${port}`);
});
```

Of course there is some room for improvements. Like for example create the router only once. But I think you'll get the overall idea.

P.S.
Version 8.0.0 is not officially released but can be installed via `npm install navigo@beta` or `yarn add navigo@beta`. Migration guide is available here https://github.com/krasimir/navigo/blob/big-rewrite/CHANGELOG.md#migration-guide and the new documentation here https://github.com/krasimir/navigo/blob/big-rewrite/DOCUMENTATION.md.
