### ISSUE TITLE
Link href is not updated when it's dynamic

### ISSUE THREAD

**Issue by fourpixels** [krasimir/navigo#23]
I'm using Navigo with dynamic links - I have a simple href link with `data-navigo` attribute. When I click it, everything works out well, I get new data from the server.

But then I **update** the href attribute, using something like:

```js
$('#link').attr('href', '/new/value');
```

Unfortunately this does not work properly. I first tried calling `updatePageLinks`, which is not documented but it's available as a function. It kind of works, but it attaches a lot of listeners to the very same link, because old ones are not cleared. I guess it just fires up a lot of redirects and I end up on the right one, I don't know (didn't investigate it too much).

I think the location property should be checked inside the click listener, instead before that:

```js
updatePageLinks: function updatePageLinks() {
    var _this = this;

    if (typeof document === 'undefined') return;
    this._findLinks().forEach(function (link) {
        var location = link.getAttribute('href'); // do NOT use this one, as it's set only once
	
        link.addEventListener('click', function (e) {
            if (!_this._destroyed) {
                e.preventDefault();
                //_this.navigate(clean(location)); // don't use pre-saved location
                // get one each time the link is clicked
                // it's slower, but more robust and works for dynamic href changes
                // I found out that pathname is the actual href
                // as href gets transformed to the real address
                // ex: href="/test" -> e.currentTarget.href = "www.example.com/test"
                _this.navigate(clean(e.currentTarget.pathname));
            }
        });
    });
}
```

I can make PR if you find this helpful :)

**Comment by fourpixels** [comment]
Any news? :)

**Comment by krasimir** [comment]
Sorry, for some reason the first email from GitHub ended up in my junk folder. I would love to see a PR. If not I'll prepare one next week (Monday).

**Comment by krasimir** [comment]
Can you please try the new `2.1.1` version.

**Comment by fourpixels** [comment]
Yeah I forgot about the multiple listeners added :-$
Works like a charm now - thanks!

**Comment by huevoncito** [comment]
I was still having this problem, even on the new version. Submitted #28, which fixed it for me by moving `link.hasListener = true` outside of the event handler. Hope that helps.

**Comment by krasimir** [comment]
#28 merged in.
