### ISSUE TITLE
Current URL not checked

### ISSUE THREAD

**Issue by Ealireza** [krasimir/navigo#235]
Very bad bad situation of current page add in history again

for example 
<a href="a" data-navigo>aaaa</a>
<a href="b" data-navigo>bbbb</a>

there is two link
when i click on aaaa
it work , 
but if i click it again , it not check last state , where we are and ...
it add to history  [back / next]

**Comment by krasimir** [comment]
With the new version 8.0.0 you can prevent the "adding to history" situation by using the `historyAPIMethod` option of the `navigate` method.

```js
router.navigate('/new-page', { historyAPIMethod: 'replaceState' });
```

```html
<a href="/new-page" data-navigo data-navigo-options="historyAPIMethod: replaceState">click me</a>
```

P.S.
Version 8.0.0 is not officially released but can be installed via `npm install navigo@beta` or `yarn add navigo@beta`. Migration guide is available here https://github.com/krasimir/navigo/blob/big-rewrite/CHANGELOG.md#migration-guide and the new documentation here https://github.com/krasimir/navigo/blob/big-rewrite/DOCUMENTATION.md.
