### ISSUE TITLE
Navigo is not a constructor

### ISSUE THREAD

**Issue by modwebpl** [krasimir/navigo#237]
window.Navigo = require('navigo');

let router = new Navigo(location.origin, false, '#');

router.on('/test', () => {
  console.log('test');
}).resolve();

console.log show error: "Navigo is not a constructor" what's wrong ?

**Comment by kevinsimper** [comment]
Hi @modwebpl, you didn't load the library properly :)

**Comment by Roba1993** [comment]
Hi @modwebpl,

load the router like the following and it should work:
`let router = new Navigo.default(location.origin, false, '#');`

**Comment by krasimir** [comment]
Hm ... that's a bit weird. I guess @kevinsimper is right.

@modwebpl do you still have the problem. Let me know and I'll reopen the issue.

**Comment by egorshulga** [comment]
`"esModuleInterop": true` in tsconfig.json – that's the thing that fixed this issue in my setup with webpack + typescript (ts-loader)
