### ISSUE TITLE
Route not matching when first segment of the URL is a parameter

### ISSUE THREAD

**Issue by logan2z** [krasimir/navigo#242]
I'm new to Navigo so maybe I'm missing something obvious, but I'm registering a route with a parameter like this:

    var router = new Navigo(null);

    router.on("/:name", function(params) {
        console.log("name =", params.name);
    }).resolve()

When I navigate to http://localhost/foo the function that is registered to handle the route is never called.  I would expect the function to be called and for params.name to have the value 'foo'.  If I just hard-code a route like '/foo' the function is called.  I noticed that none of the parametrized route examples have a parameter in the first segment of the route so perhaps this is not supported for some reason.

**Comment by krasimir** [comment]
Can you try initializing with `new Navigo('/')`

**Comment by logan2z** [comment]
Thanks, that helped a bit, but I'm still seeing some unexpected behavior.  For example,

    var router = new Navigo('/')

    router.on(":x/:y", function(params) {
        console.log("params =", params);
    })

With a URL of http://localhost/foo/bar I get the expected result

`
params = {x: 'foo', y: 'bar'}
`

But with a URL of http://localhost/foo I get

`
params = {x: 'localhost', y: 'foo'}
`

I would expect something like 

`
params = {x:'foo', y: undefined}
`

I don't expect the hostname to ever be assigned to one of the parameters.  

Is this working as designed?

**Comment by logan2z** [comment]
I must be misunderstanding how to configure the router.  For example, If I do

` 
router.navigate('/x/y')
`

 the router is trying to change the URL to http://x/y rather than http://localhost/x/y.

I fear I'm configuring the router incorrectly.

**Comment by logan2z** [comment]
Can anyone suggest what I might be doing wrong, or is this a bug in Navigo?

**Comment by krasimir** [comment]
Can you prepare a simple example and upload it somewhere.

**Comment by logan2z** [comment]
> Can you prepare a simple example and upload it somewhere.

The example is pretty much just what I posted earlier:

    var router = new Navigo('/')

    router.on(":x/:y", function(params) {
        console.log("params =", params);
    })

With this configuration and the URLs I posted above, I'm seeing the unexpected behavior I described.

**Comment by marklundin** [comment]
Did you manage to find a fix for this @logan2z Im getting exactly the same issue

**Comment by krasimir** [comment]
@logan2z @marklundin  can you try the latest version 8.0.0. This should working there.

P.S.
Version 8.0.0 is not officially released but can be installed via `npm install navigo@beta` or `yarn add navigo@beta`. Migration guide is available here https://github.com/krasimir/navigo/blob/big-rewrite/CHANGELOG.md#migration-guide and the new documentation here https://github.com/krasimir/navigo/blob/big-rewrite/DOCUMENTATION.md.

P.S.S
I'm trying to start fresh on the new version 8.0.0. If you try it and still doesn't work let me know and I'll reopen the issue.
