### ISSUE TITLE
Navigating to the root url in the html template demo

### ISSUE THREAD

**Issue by chungvle** [krasimir/navigo#248]
In the html template demo, the root url in my case is localhost:8080. When I typed localhost:8080/foo in the address bar, I got the same default page which is fine. But in that case I'd like to reset the url to localhost:8080. 

I tried using router.navigate(window.location.origin) but it doesn't work (I get localhost:8080/foo/#!localhost:8080) Setting absolute path doesn't work either. Is it possible to do this with #! in navigo? Thanks.

**Comment by krasimir** [comment]
Hey @chungvle,

I decided to support only the next version of Navigo. Which is 8.0.0 and it will be released on the first days of 2021. That new version doesn't support the hash based routing. Only absolute paths. So, can you try with that version by installing it via `npm install navigo@beta`. You should simply use `router.navigate('/')`.

P.S
I'm trying to start fresh on the new version 8.0.0. If you try it and still doesn't work let me know and I'll reopen the issue.
