### ISSUE TITLE
How to add a confirm prompt before leave?

### ISSUE THREAD

**Issue by lxuanchengdx** [krasimir/navigo#250]
We're having to add confirmation before leaving, I see that `Navigo` has the `before`, but it's not receiving event.

Is there an alternative solution for this?

**Comment by krasimir** [comment]
I'll suggest to use the newest 8.0.0 beta version. There is a `leave` hook that accepts a callback. 

```js
router
  .on(
    "/about",
    (match) => {
      render("About");
    },
    {
      leave: (done) => {
        if (confirm("You are about to leave the About page. Are you sure?")) {
          done();
        } else {
          done(false);
        }
      },
    }
  )
```

When the user lands on `/about` and tries to go out will see that confirmation window. The router does nothing until you call the `done` function. (the full example [here](https://github.com/krasimir/navigo/tree/big-rewrite/examples/250))

P.S.
Version 8.0.0 is not officially released but can be installed via `npm install navigo@beta` or `yarn add navigo@beta`. Migration guide is available here https://github.com/krasimir/navigo/blob/big-rewrite/CHANGELOG.md#migration-guide and the new documentation here https://github.com/krasimir/navigo/blob/big-rewrite/DOCUMENTATION.md.
