### ISSUE TITLE
404 route isnt working

### ISSUE THREAD

**Issue by theboardio** [krasimir/navigo#251]
Hello community :)

This is my router configuration

// getElementById wrapper
function $id(id) {
  return document.getElementById(id);
}

// asyncrhonously fetch the html template partial from the file directory,
// then set its contents to the html of the parent element
function loadHTML(url, id) {
  req = new XMLHttpRequest();
  req.open('GET', url);
  req.send();
  req.onload = () => {
    $id(id).innerHTML = req.responseText;
  };
}

// use #! to hash
router = new Navigo(null);
router.on({
  '/': () => { loadHTML('/templates/web/home.html', 'loadrouter'); },
  'pricing': () => { loadHTML('/templates/web/pricing.html', 'loadrouter'); },
  'dash/home': () => { loadHTML('/templates/dash/login.html', 'loadrouter'); },
  'dash/user/login': () => { loadHTML('/templates/dash/login.html', 'loadrouter'); },
  'dash/user/signup': () => { loadHTML('/templates/dash/signup.html', 'loadrouter'); }
});

// set the 404 route
router.notFound((query) => { loadHTML('/templates/errors/404.html', 'loadrouter' });

router.resolve();

The problem is: If i access to a not existent route, the router loads de home.html template instead the 404.html template.
Am i doing something wrong? Anybody can help me?

Thanks!!

**Comment by krasimir** [comment]
I'm not sure which version you are using but there is a new one 8.0.0 where this problem doesn't happen. If possible migrate to it and test there. 

P.S.
Version 8.0.0 is not officially released but can be installed via `npm install navigo@beta` or `yarn add navigo@beta`. Migration guide is available here https://github.com/krasimir/navigo/blob/big-rewrite/CHANGELOG.md#migration-guide and the new documentation here https://github.com/krasimir/navigo/blob/big-rewrite/DOCUMENTATION.md.
