### ISSUE TITLE
Pausing when useHash == true

### ISSUE THREAD

**Issue by orty** [krasimir/navigo#252]
Hi,

I was wondering if Navigo was able to be paused/resumed when initialized with `useHash = true`.
So far, by my testing, it apparently is not the case, could you confirm or give me a workaround maybe ?

Thanks a lot.

**Comment by krasimir** [comment]
Hey,

I stopped supporting/developing the 7th and below versions of this library. It is fully rewritten now and I could say that the pausing/resuming there is replaced by an option in the `navigate` method. There is no hash based routing too. Sorry if you can't migrate to the newest one but I'm not planning to work on bugs that are attached to the old source code.

If you want to use Navigo 8.0.0 the piece of documentation that you need is here https://github.com/krasimir/navigo/blob/big-rewrite/DOCUMENTATION.md#navigating-between-routes

P.S.
Version 8.0.0 is not officially released but can be installed via `npm install navigo@beta` or `yarn add navigo@beta`. Migration guide is available here https://github.com/krasimir/navigo/blob/big-rewrite/CHANGELOG.md#migration-guide and the new documentation here https://github.com/krasimir/navigo/blob/big-rewrite/DOCUMENTATION.md.
