### ISSUE TITLE
Question: How do you make RegExp route params available in hooks

### ISSUE THREAD

**Issue by rjgamble** [krasimir/navigo#253]
Given the following route config, how would I obtain the `id` and `action` params in the `before` and `after` hooks?

```JS
// e.g. /user/42/save
this._router.on(
        /user\/(\d+)\/(\w+)\/?/,
        {
            as: 'userWithIdAndAction',
            uses: (id, action) => { debugger; /* id=42, action=save */ }
        },
        {
            before: (done, params) => { debugger; /* params is null here */ },
            after: (params) => { debugger; /* params is null here */ }
        });
```

**Comment by krasimir** [comment]
Hey @rjgamble,

there is a new version of Navigo - 8.0.0. The route definition there is a bit different but it provides a way to fetch the data that you need.

```js
function handler(match) {
  console.log(match);
}
function before(done, match) {
  console.log(match);
  done();
}
function after(match) {
  console.log(match);
}
router.on(/user\/(\d+)\/(\w+)\/?/, handler, {
  before,
  after,
});

router.navigate("/user/42/save");
```

The `match` in the two hooks and the handler is equal to:
```json
{
  "data": [
    "42",
    "save"
  ],
  "url": "user/42/save",
  "queryString": "",
  "route": {
    "name": "/user\\/(\\d+)\\/(\\w+)\\/?/",
    "path": {},
    "hooks": {}
  },
  "params": null
}
```

P.S.
Version 8.0.0 is not officially released but can be installed via `npm install navigo@beta` or `yarn add navigo@beta`. Migration guide is available here https://github.com/krasimir/navigo/blob/big-rewrite/CHANGELOG.md#migration-guide and the new documentation here https://github.com/krasimir/navigo/blob/big-rewrite/DOCUMENTATION.md.
