### ISSUE TITLE
Top-level router hooks not working

### ISSUE THREAD

**Issue by rjgamble** [krasimir/navigo#257]
I'm just working through the migration to v8.0.1 and I'm experiencing an issue where the top-level `before` and `after` hooks are not being called prior to the individual route lifecycle being invoked. Here is an example of my initialisation:

```js
let router = new Navigo('/');

router.hooks({
            before: (done, match) => { debugger; /* never gets hit */ },
            after: (match) => { debugger; /* never gets hit */ }
        });

router.on({
            '/foo': {
                as: 'fooRoute',
                uses: (match) => { debugger; },
                hooks: {
                    before: (done, match) => { debugger; done(); },
                    after: (match) => { debugger; }
                }
            }
        });

router.resolve();
```

I'm unable to hit the top-level `before` or `after` router hooks either coming directly in on `/foo` or using `.navigate('/foo')` 

Have I set this up incorrectly?

**Comment by rjgamble** [comment]
On inspection of the source, am I correct in thinking that if I supply hooks in my route definition, this will overwrite any generic hooks I've defined against the router?

```js
routes.push(createRoute(p, handler, hooks || genericHooks, name));
```

**Comment by krasimir** [comment]
@rjgamble you are absolutely right. I assumed that this is the expected behavior. In a sense of the library offers generic hooks applied to all routes and specifically opens a door to set custom hooks for individual routes. What is your expectation and use case?

**Comment by rjgamble** [comment]
@krasimir I'd like to do both. I have a set of tasks I need to perform for _every_ route that is resolved as well as specific tasks for individual routes. 

You may recall our email discussion about this a few weeks ago. We use the generic `before` hook to determine a subsequent component router to handle the route lifecycle methods specific to the area of the application you're in. From our email exchange:

>Named routes: We have many component areas within our application and we used named routes in the hooks and route handlers to call a factory that produces a component router that we can pass all of the route variables to, to process. This keeps our main router class simple and only responsible for detecting, registering and resolving routes. What happens with that route information is then up to the responsibility of the component router. 
>
>We make use of the global before hook to challenge the resolved route and work out which component handler we need.

Here is our implementation of the generic `before` hook in v7:

```js
    _onRouteFound = (done, params) => {
        let resolvedRoute = this._router.lastRouteResolved();

        if (resolvedRoute && this._componentRouters.has(resolvedRoute.name)) {
            this._currentComponentRouter = this._componentRouters.get(resolvedRoute.name);
        } else {
            this._currentComponentRouter = this._componentRouters.get('base');
        }

        done();
    }
```

Please let me know your thoughts on this?

**Comment by krasimir** [comment]
Yep. That makes sense. Actually if I fix this I'll open a door for another feature that I'm struggling with. I'll keep you posted.

**Comment by krasimir** [comment]
Hey @rjgamble,

There is a new `8.2.0` version that respects the existence of generic hooks and bundles them together with the route specific hooks. The order of execution is first the generic one then the one defined in the route. The unit test for this change is [here](https://github.com/krasimir/navigo/blob/master/src/__tests__/hooks.spec.ts#L372-L414):

```js
const whatHappened = [];
const r: NavigoRouter = new Navigo("/");
const createHooks = (prefix) => ({
  before(done, match) {
    whatHappened.push(prefix + "before");
    done();
  },
  after() {
    whatHappened.push(prefix + "after");
  },
  already() {
    whatHappened.push(prefix + "already");
  },
  leave(done) {
    whatHappened.push(prefix + "leave");
    done();
  },
});

r.hooks(createHooks("generic_"));

r.on("/foo/bar", jest.fn(), createHooks("route_"));

r.navigate("/foo/bar");
r.navigate("/foo/bar");
r.navigate("/boo");

expect(whatHappened).toStrictEqual([
  "generic_before",
  "route_before",
  "generic_after",
  "route_after",
  "generic_already",
  "route_already",
  "generic_leave",
  "route_leave",
]);
```

So basically we have the following invocation:

```
"generic_before",
"route_before",
"generic_after",
"route_after",
"generic_already",
"route_already",
"generic_leave",
"route_leave",
```

Can you try on your side and let me know if it works as expected.

**Comment by rjgamble** [comment]
Hi @krasimir Thank you for taking a look at this and getting back to me. I've updated to 8.4.1 today and I can see that both generic and route specific hooks are executing and in the order you've specified above. 

Can I ask, did you intend to change the order the after hooks are executed in? 

In v7 it goes:
> generic before -> route specific before -> route handler -> route specific after -> generic after

In v8 it goes:
> generic before -> route specific before -> route handler -> generic after -> route specific after

**Comment by krasimir** [comment]
@rjgamble the hooks in the new implementation are array of functions. So the order of execution follows the fifo principle. Because the generic hooks are added first into the array they are executed first. Is this causing a lot of issues on your side.

**Comment by rjgamble** [comment]
@krasimir understood. 

It did cause an issue initially because I had some logic in the generic `after` hook to tidy up some temporary cache data that was stored for the duration of the route lifecycle however I have made changes to work around it. 

If you intend to keep it the way it is is v8 i.e. FIFIO, please feel free to close this issue.

**Comment by krasimir** [comment]
Yep. Sorry, that's an essential design decision that I did to support some features in [navigo-react](https://github.com/krasimir/navigo-react).
