### ISSUE TITLE
Navigo 7.1.3 available on NPM, but not in changelog or Github repo

### ISSUE THREAD

**Issue by Visnetje** [krasimir/navigo#258]
As seen at https://www.npmjs.com/package/navigo/v/7.1.3 , there's a 7.1.3 version available.

What are the changes?
And why was this version skipped from the changelog or Github repository?

Thanks, @krasimir !

**Comment by krasimir** [comment]
Sorry @Visnetje, just updated the changelog. I really don't know how this happened but 7.1.3 was released by accident. It contains a small change in the README + a useless "examples" folder from the new 8.0.0 version.

**Comment by krasimir** [comment]
Oh wait wait wait ... Now I see. It's this:

```
This version just adds a the following warning to the library:
console.warn("Navigo router library will have soon a major upgrade to version 8.0.0. If you don't have time for such migration please stick with the latest 7.1.2 version. To avoid seeing this message set a strict 7.1.2 in your package.json file.");
```

But of course I messed up the release and forgot to ignore the `examples` directory when switching branches.

**Comment by Visnetje** [comment]
Alright, @krasimir , thanks for clearing that up. :)

Thanks for your work on the 8.x rewrite!
