### ISSUE TITLE
Allow conditional 'navigo-data' attribute for the '<a href="">' element

### ISSUE THREAD

**Issue by stepanjakl** [krasimir/navigo#263]
Hello,

Firstly, thank you for the great library! The new version (v8) looks very good so far.

Currently, I am facing an issue where sometimes I want to pass a full url e.g. `https://github.com/` to the `href=''`  tag without Navigo's support. Other times I want to pass a local path e.g. `path/somewhere` and enable Navigo's functionality by adding `navigo-data` attribute.

I am using Navigo in conjuntion with Alpine.js and thought I would be able to do something like this `<a href="https://github.com/" navigo-data="!this.isUrl">` where `isUrl = true`.

Maybe there is a way to do this that I don't know about, please advise.

P.S. I know I could probably achieve this conditionally, either with `navigate()` function or conditioning the element (`<a href='https://'>` vs. `<a href='/' navigo-data>`), but wondering if this could this be a feature?

Thank you ✌️

**Comment by krasimir** [comment]
Hey,

what we can do is to read the value of `data-navigo`. I mean the library to use those links as _Navigo_ links only if the attribute is there and its value IS NOT `"false"`. So:

```html
<a href="https://site.com/" data-navigo="false">click me</a>
```

will be ignored by the library. What you think?

**Comment by stepanjakl** [comment]
Absolutely, that would work great!:)

However (and I don't need this at the moment), what if the `data-navigo` attribute changes its state to `true`, then I presume the Navigo instance would not reactively turned on for that element?

**Comment by krasimir** [comment]
Hm ... that's an interesting problem. In general Navigo doesn't know about the rendering layer. So, the bottom line is that you should call `router.updatePageLinks()` after you update the state.

**Comment by stepanjakl** [comment]
> Hm ... that's an interesting problem. In general Navigo doesn't know about the rendering layer. So, the bottom line is that you should call `router.updatePageLinks()` after you update the state.

Ahh, I didn't know about that method, that should be fine then.

**Comment by krasimir** [comment]
Well, `updatePageLinks` doesn't remove the listeners that are already attached to links. So, there is some work required to achieve what you want. It's on my list already.

**Comment by stepanjakl** [comment]
Also, I would put a condition that even if the `<a>` element has `data-navigo` attribute but `target` is set to `_blank` then still don't initialise Navigo (?)

**Comment by krasimir** [comment]
Makes sense yes.

**Comment by krasimir** [comment]
There is a new version `8.5.0` which:
* supports `"false"` as value of `data-navigo` attribute. In this case it skips the link and the link works as a normal one
* skips links with `target="_blank"`

Also have in mind that if some link is instrumented, or in other words wired to Navigo logic you can change its `data-navigo` value to `"false"` and call `router.updatePageLinks()`. This will remove the click listener and will make the link work as a normal link.

Let me know if it doesn't work as expected and I'll reopen the issue.
