### ISSUE TITLE
Destination route hooks being executed from navigate when callHandler is false 

### ISSUE THREAD

**Issue by rjgamble** [krasimir/navigo#265]
Hi @krasimir, following on from the issue I was seeing previously when using `navigate(route, options)` in a `before` hook. #262 

I have noticed that the `before` hook is being executed in the destination route when I use `router.navigate(route, options)` even when I set `callHandler` to `false`. Given the below example:

```js
const router = new navigo('/');

router.on({
    '/abc-1234': {
        as: 'routeA',
        uses: (match) => { console.log('Hit routeA handler.'); },
        hooks: {
            before: (done, match) => {
                console.log('Hit routeA before hook.');
                router.navigate('/item/abc-1234', {
                    historyAPIMethod: 'replaceState',
                    updateBrowserURL: true,
                    updateState: true,
                    callHandler: false,
                    force: false
                });

                done();
            },
            after: (match) => { console.log('Hit routeA after hook.'); }
        }
    }
});

router.on({
    '/item/abc-1234': {
        as: 'routeB',
        uses: (match) => { console.log('Hit routeB handler.') },
        hooks: {
            before: (done, match) => { console.log('Hit routeB before hook.'); },
            after: (match) => { console.log('Hit routeA after hook.'); }
        }
    }
});

router.resolve();
router.navigate('/abc-1234');
```

The output I'm seeing from this is:
```
Hit routeA before hook.
Hit routeB before hook. // <- Should I be seeing this?
Hit routeA handler.
Hit routeA after hook.
```

Notice, I only hit the `before` hook for routeB but not the `after` hook. 

What I am expecting to happen is here is that because I've set `callHandler` to `false`, I don't execute any of the route lifecycle for routeB.

**Comment by krasimir** [comment]
@rjgamble instead of restricting the hooks because `callHandler` is set to `false` I decided to introduce `callHooks` flag. This way we can still cover the case where your handler is not fired but the hooks are. So in your case:

```
router.navigate('/item/abc-1234', {
  historyAPIMethod: 'replaceState',
  callHandler: false,
  callHooks: false
});
```

You don't have to specify `force`, `updateBrowserURL` and `updateState` because their values are anyway `false`, `true` and `true`.

**Comment by krasimir** [comment]
New version `8.6.0`.

**Comment by rjgamble** [comment]
Hi @krasimir, thanks for taking a look. I upgraded to 8.6.3 and retested. It is working as expected when passing `callHooks: false`. 

Thanks for the tip regarding the default values for the other navigate options.
