### ISSUE TITLE
v8.7.1 Disabling no match warning doesn't stop the warning messages

### ISSUE THREAD

**Issue by richturner** [krasimir/navigo#267]
I've tried disabling the no match warning during initialisation but it doesn't seem to pay attention to the setting.

```
const router = new Navigo("/", {hash: true, noMatchWarning: false});
```

**Comment by krasimir** [comment]
Hey @richturner, can you please try with a `8.7.2` version. Should be fixed now.

**Comment by richturner** [comment]
Hi, thanks for the quick response. I can confirm that this is fixed now.
