### ISSUE TITLE
v8.7.1 Hash based routing resolves route twice

### ISSUE THREAD

**Issue by richturner** [krasimir/navigo#268]
I am trying to use the latest version with hash based routing like I did with previous versions but I've noticed some odd behaviour in that the route handler gets called twice for each `router.navigate` call with a no match found log message in between each call,

I put a hash change event handler on the window and can see that two events are created, so for example navigating from `/#/foo -> /#/bar` I see the following hash change events:

```
event1: oldURL=http://localhost:9000/#/foo, newURL=http://localhost:9000/#
event2: oldURL=http://localhost:9000/#, newURL=http://localhost:9000/#/bar
```

Seems that only one hash change should occur for a given route navigation and this doesn't really explain why I get two calls to the route handler, but hopefully it can shed some light on the problem.

I'm pretty sure it's not something funky in my code.

**Comment by krasimir** [comment]
Hey, can you please try version `8.7.3`. The bug should be fixed there.

**Comment by richturner** [comment]
Hey thanks for the quick response, I switched back to v7 as I was also having issues with replicating the old silent route navigation, when I get some spare time I'll definitely give it a try.

**Comment by krasimir** [comment]
Sounds good. Please reopen the issue if you need more assistance.
