### ISSUE TITLE
Leave hook not called on notFound-route

### ISSUE THREAD

**Issue by mritzerfeld** [krasimir/navigo#271]
A leave hook configured through the hooks object parameter for notFound() or addLeaveHook(`__NOT_FOUND__`) is not called when navigating away to another existing route on v8.8.x. Other hooks like before or after however are called.

```
const test = new Navigo('/');

test.on('existing', () => console.log('route called'));
test.notFound(() => console.log('not found'), {
    leave: (done) => {
        console.log('leave hook called');
        done();
    }
})

test.navigate('/non-existent');
test.navigate('/existing');
```

**Comment by krasimir** [comment]
@mritzerfeld can you please try the latest `8.8.3`. The problem should be fixed there.

**Comment by mritzerfeld** [comment]
@krasimir
Once again many thanks for your quick response. 8.8.3 fixes the issue.
