### ISSUE TITLE
Incorrect route matching with subfolder root

### ISSUE THREAD

**Issue by stepanjakl** [krasimir/navigo#275]
Hello Krasimir,

I deployed a site on Github Pages inside a subfolder and set Navigo's root to that subfolder i.e. `new Navigo('/bohemica-studio-website')`.

I am getting a wrong match for Navigo links when the `href` path is (correctly) set to `"bohemica-studio-website/en/projects/branding"`. The matching route should be `bohemica-studio-website/:language/projects/:name`, but it ends up being `bohemica-studio-website/*`.

Interestingly, when I call the `router.match('bohemica-studio-website/en/projects/branding')`, I get the correct route. Same, when I set the link without the root path i.e. `"en/projects/branding"`

![Screenshot 2021-02-20 at 11 16 08](https://user-images.githubusercontent.com/47005900/108594053-9008ec00-736f-11eb-9b31-595aaebc2f8e.png)

Maybe, there is some wrong deployment setting, but I feel that Navigo is being fed the right data, so it's likely an internal issue. What do you think?

Thank you ✌️

P.S. Everything works fine on localhost when the root path is set to `'/'`

**Comment by krasimir** [comment]
Hey,

if you ser a specific path as a root of your app you should skip it when writing URLs in the `a` tags. For example your tag should look like:

```
<a href="/en/projects/branding" data-navigo>link</a>
```

The router knows that you mean `/bohemica-studio-website/en/projects/branding` because it has `bohemica-studio-website` as a root.

**Comment by stepanjakl** [comment]
Okay, thank you for the answer.

Then, I believe that the `router.generate()` function creates url string with the root, which subsequently can't be used for the link. 

Moreover, if you take away the root path, then it can be a bit confusing for the user in the browser .e.g.:

1. what the user sees:
<img width="142" alt="Screenshot 2021-02-20 at 15 24 07" src="https://user-images.githubusercontent.com/47005900/108601146-04a15200-7393-11eb-97b2-59139ab20828.png">

2. what the user should actually see:
<img width="286" alt="Screenshot 2021-02-20 at 15 24 24" src="https://user-images.githubusercontent.com/47005900/108601149-0703ac00-7393-11eb-83e9-fbf56eee083f.png">

(I know, it's a minor detail)

**Comment by krasimir** [comment]
I'm a bit confused what is the expected behavior. Can you share a URL or even if possible a codesandbox. You can use this as an example https://codesandbox.io/s/navigo-example-jrui8

**Comment by stepanjakl** [comment]
Essentially, I create a path via `router.generate('branding')` that I can then input inside `<a href='...'>`. However, currently I get `bohemica-studio-website/en/projects/branding` instead of `en/projects/branding` which, like you said, doesn't work for the navigo link as it contains the root folder.

I think it would make more sense for the link to include the full path with the root as mentioned in the previous post. E.g. `<a href='bohemica-studio-website/en/projects/branding'>` rather than `<a href='en/projects/branding'>`

I could probably just take the root off the generated path programatically... I am just thinking out loud here :)

The site is still WIP, but I am happy to share it at a later date (I think you'll find it interesting anyway as I use Navigo for an internationalisation system, including language change for the url path).

**Comment by krasimir** [comment]
I see @stepanjakl. I would rather patch the generate method so it returns the path without app than forcing the full url path on the links. Conceptually the idea of Navigo is to be an app oriented. It shouldn't know about the rest of the world. So I'll probably provide an additional argument to the generate function which will strip the root.

**Comment by mrdaliri** [comment]
Hi @krasimir,
I'm having the same problem after upgrading to v8 from v7: links with href generated by `router.generate()` are not correctly handled by Navigo. If I drop `data-navigo` they work fine, but I'll lose the SPA feature.

**Comment by krasimir** [comment]
@stepanjakl @mrdaliri can you please try the latest 8.9.0 version. It accepts a third argument of the `generate` method.

```javascript
router.generate(
  "route-name",
  { data: 'foobar' }, // this cloud be null
  { includeRoot: false } // false means "Don't include the root"
)
```

**Comment by stepanjakl** [comment]
I swapped the project a custom domain (and root folder), so I cannot test it. But it looks good and would consider it fixed👍
