### ISSUE TITLE
Hooking up <a /> tags without the navigo-data attribute

### ISSUE THREAD

**Issue by schotime** [krasimir/navigo#280]
Is there away to do this automagically as a convention or just do all `<a />` tags that use relative urls because I'd rather not have to specify this everywhere?

**Comment by krasimir** [comment]
That's a good suggestion for a new router conifg. I'll implement.

**Comment by krasimir** [comment]
Hey @schotime,

There is a new 8.10.0 version. You can now use:

```js
const router = new Navigo("/", { linksSelector: "a" });
```

which will basically select all the links on the page. No matter if they have `data-navigo` attribute or not.

**Comment by schotime** [comment]
awesome!! thx
