### ISSUE TITLE
Routes without # and server reload

### ISSUE THREAD

**Issue by teawithfruit** [krasimir/navigo#282]
Hey,

I'm using navigo for a long time. Thank you for creating such a good library!
But these days I got a problem. I have the idea to use client side routes without a hash and without a fully site refresh.
Here an example:

```
<a href="/auth/sign">Register</a>
```

If I click on that register link, the page is fully reloaded.
What I like to do is, to click on that link without a reload. I would like to set some options, which will prevent a server reload.
I've tried many ways. Also with ```data-navigo-options```, but until now I didn't found a way.

Is that possible and if yes, can you give me a hint how to do that?
I'm using the newest version (8.9.1).

Thanks!

**Comment by krasimir** [comment]
Hey,

did you try with `<a href="/auth/sign" data-navigo>Register</a>`. Here's the relevant section in the docs https://github.com/krasimir/navigo/blob/master/DOCUMENTATION.md#augment-your-a-tags

**Comment by teawithfruit** [comment]
Thanks for the quick reply.
Why I have not seen that, I also do not know. :see_no_evil:
