### ISSUE TITLE
{ linksSelector: "a" } loop

### ISSUE THREAD

**Issue by MustafaHi** [krasimir/navigo#288]
```js
var router = new Navigo('/', { linksSelector: "a" });

router.on({
    ':page/:*': function(param) {
        console.log("ROUTER: :page/*");
        console.log("PARAM : " + JSON.stringify(param));
        loadDocument(param);
    },
    ':page': function(param) {
        console.log("ROUTER: :page");
        console.log("PARAM: " + JSON.stringify(param));
        Navigation.querySelector('a').click();
    },
    '*': function() {
        console.log("ROUTER: *");
        Navigation.querySelector('a').click();
    }
}).resolve();
```

When the route is not a full document URL I call `Navigation.querySelector('a').click();`  to navigate to document,

this works fine except when I use `{ linksSelector: "a" }` it results in a loop, and the browser stops it with the exception
```
Uncaught RangeError: Maximum call stack size exceeded          updateBrowserURL.ts:15
```

**Comment by krasimir** [comment]
Well, that's expected because inside `:page` you are again clicking the link. Also in `*`. So it seems that your user clicks a link but inside the handler you are clicking the link again.

**Comment by MustafaHi** [comment]
This happens because Navigo is applying `{ strategy: 'ALL' }`, even though it's not provided.
( when using `{ linksSelector: "a" }`)

So It can be solved by providing `{ strategy: 'ONE' })`
Or replacing last function `*` with `/`, so it doesn't match.

**Comment by MustafaHi** [comment]
This happens because Navigo is applying `{ strategy: 'ALL' }`, even though it's not provided.
( when using `{ linksSelector: "a" }` )

So It can be solved by providing `{ strategy: 'ONE' }`
Or replacing last function `*` with `/`, so it doesn't match.
