### ISSUE TITLE
onpopstate event

### ISSUE THREAD

**Issue by daviestar** [krasimir/navigo#29]
Hello,

Is it possible to latch onto the `window.onpopstate` event Navigo uses for forward/back buttons?  I can use it easily enough, but then navigo stops working :)

I have a page transition in this project, so it's not possible to re-render the menu in this case. I'm manually updating the `.active` class on the menu with jQuery, which works fine, except for the forward/back browser buttons.

Was thinking a custom event could be fired onpopstate with the `window.location.pathname` passed to it, but interested in your thoughts.

Thanks.

**Comment by krasimir** [comment]
Hey,

I'm not sure that I understood the issue. Do you want to subscribe for the onpopstate event?

**Comment by daviestar** [comment]
Sorry I wrote that not long after I woke up :)

Yes, I need to do something when the URL changes (update active class in menu), which I can mostly do with a click event, except for browser forward/back buttons.

Cheers.

**Comment by krasimir** [comment]
Well, Navigo aims to do only one thing - it reacts on URL changes. So, so I guess you may apply the logic in your route handlers like:
```js
router
  .on({
    '/products/list': function () {
      onRouteChange();
    },
    '/products': function () {
      onRouteChange();
    },
    ...
  })
```

**Comment by krasimir** [comment]
This will pollute your route handlers but can be solved with partial execution (or currying).

**Comment by daviestar** [comment]
Oh yes, of course you are right. D'oh!

Thanks again.
