### ISSUE TITLE
Cannot get rid of console warning regarding Navigo v8

### ISSUE THREAD

**Issue by hirasso** [krasimir/navigo#298]
Hi there,

first of all, thank you for this great library! I've been using it for years without problems.

Just a short question: How exactly do I get rid of this warning in my console?

> Navigo router library will have soon a major upgrade to version 8.0.0. If you don't have time for such migration please stick with the latest 7.1.2 version. To avoid seeing this message set a strict 7.1.2 in your package.json file.

I tried changing this in my `package.json`:

```json
"navigo": "^7.1.2",
```
to this:
```json
"navigo": "7.1.2",
```
, but the log persists. I also tried deleting my `package-lock.json`, my bundler [parcel](https://parceljs.org/)'s `.cache` directory, reinstalling all `node_modules`, but without luck. Looking at the source, it doesn't seem to check anything except if a console exists in the code (`navigo.js`, line 14):

```javascript
if (typeof console !== "undefined" && !!console.warn) {
  console.warn("Navigo router library will have soon a major upgrade to version 8.0.0. If you don't have time for such migration please stick with the latest 7.1.2 version. To avoid seeing this message set a strict 7.1.2 in your package.json file.");
}
```

**Comment by krasimir** [comment]
I'll suggest to delete again node_modules folder, package-lock.json and your yarn.lock files.
