### ISSUE TITLE
Refresh handling

### ISSUE THREAD

**Issue by tylerl0706** [krasimir/navigo#3]
I didn't really know where to go for a question, so I just opened an issue. Feel free to close.

How do you handle when a user refreshes the page... by accident? I find myself getting a 404.
##### Before refresh
<img width="317" alt="screen shot 2016-01-06 at 10 45 25 pm" src="https://cloud.githubusercontent.com/assets/2644648/12164170/6ea6b102-b4c8-11e5-8a18-a7303f64e0b0.png">

##### After refresh
<img width="417" alt="screen shot 2016-01-06 at 10 54 27 pm" src="https://cloud.githubusercontent.com/assets/2644648/12164179/7a4935ca-b4c8-11e5-8773-0f39661e46eb.png">

**Comment by krasimir** [comment]
Can you please give a little bit more details about the code that you are using. 
* How did you reach the `/test1` route. Is it via Navigo's `navigate` method. If yes what are your registered routes.
* Is the backend a nodejs app. If yes then do you forward every request to your index. 

My assumption is that your backend is not forwarding all the request to the same html content. If that was the case then you have to see your main html content (at least). [Here](http://krasimirtsonev.com/blog/article/deep-dive-into-client-side-routing-navigo-pushstate-hash#client-side-routing-is-not-exactly-only-client-side) is an article that describes why you have to forward all the request to the same html file. It's kinda critical to make the client-side routing works.

**Comment by tylerl0706** [comment]
I immediately thought about that, once I finished writing but I couldn't respond until now. You are absolutely right. All requests must be forwarded to the same html file, otherwise client-side routing just will not work. In my example, I didn't have that forwarding. I was simply using SimpleHTTPServer to test.

**Comment by krasimir** [comment]
:+1:
