### ISSUE TITLE
navigo.min.js:1 Uncaught SyntaxError: Unexpected token <

### ISSUE THREAD

**Issue by 960Design** [krasimir/navigo#30]
Single routing paths work perfectly, such as: http://domain/classes
Whenever I try to 'stack' routes or just add a single forward slash '/' after the route I get this error, such as http://domain/classes/ or http://domain/classes/students

I'm just building a simple example testing if navigo is something that would work for me.  Followed the examples, built a very simple html5 ( valid testing cleared ) page.

Any ideas would be appreciated!

**Comment by krasimir** [comment]
Hey @960Design,

1. Did you setup your backend so every url points to your index file.
2. Can you provide an example (url or the exact code)

**Comment by 960Design** [comment]
Here's the code, non working in the bin:
https://jsbin.com/lasecehoya/edit?html,js,output

Here's the .htaccess 
<ifModule mod_rewrite.c>
  Options +FollowSymLinks
  IndexIgnore */*
  RewriteEngine On
  RewriteCond %{REQUEST_FILENAME} !-f
  RewriteCond %{REQUEST_FILENAME} !-d
  RewriteRule (.*) index.php
</ifModule>

If that doesn't make enough sense for you, I'll host the code.
Thank you for your time!

**Comment by krasimir** [comment]
I cloned your bin to this one https://jsbin.com/xaqoyag/edit?html,js,output and started investigating. The only one issue that I found was that jsbin was unable to load Navigo because jsbin was using `https` but the link to Navigo `http`. Once I change that I got everything working.

**Comment by 960Design** [comment]
Try here...
http://960design.com/dev/

Open the console... manually add classes into the url... console should display 'classes...'
Now manually add /test or just a single forward slash.  Check the console for errors:
"anyscript.js:1 Uncaught SyntaxError: Unexpected token <"

**Comment by krasimir** [comment]
I see. The problem is that on `/classe/test` there is a file `js/anyscript.js` which is not accessible. The server in this case responds with your `index.html` and the browser tries to parse it. That's why it says `Unexpected token <` because that's what it sees first - an HTML. I'll suggest to use absolute URLs for your assets. So instead of `js/anyscript.js` try `/dev/js/anyscript.js` and it will work.

**Comment by krasimir** [comment]
*(That's by the way one of the drawbacks of the URLs that change with `pushState`. The paths to external resources should be absolute because according to the server that's a new path.)*

**Comment by 960Design** [comment]
Awesome!  That was it!!  Just needed to use absolute urls exactly as you stated.  Thank you very much for the router and the assistance!
