### ISSUE TITLE
how to configure for changes in address bar

### ISSUE THREAD

**Issue by tpezzelle** [krasimir/navigo#311]
i'm implementing in a vanilla js/html/css site and can't seem to navigo to respond at all to physically entered address locations that do have routes.... get a page not found error.  i've looked high and low through the docs and it seems like it should be happening automatically, but is not.

router.navigate is working
a href="/mypath" data-navigo  is working
back/forward buttons working

i'm sure i've missed something, just can't seem to see it

**Comment by krasimir** [comment]
Hey @tpezzelle,

Navigo is a client side router and as such is designed to work only in the browser. I have the feeling that you are mixing it with the idea of server-side routing like the one that express (for example) provides. With Navigo, all your server-side routes should point to a single file. After that the Navigo will handle the path.

**Comment by tpezzelle** [comment]
thanks for the response - it got me to thinking about "server-side routes"....  i interpreted that as "addresses processed by the server in an attempt to resolve a request".... which got me thinking about IIS (my deployment world) rewrite rules.  

found this very helpful bit by Matt Burke:

https://www.mattburkedev.com/iis-rewrite-rule-for-single-page-apps/

it doesn't apply specifically to navigo... but it works very nicely!  all i had to do is add a call in my startup script that processes the window.location.path and then implements navigo against that path.  now i can enter addresses or navigate with links and they resolve as desired.

**Comment by tpezzelle** [comment]
By the way....  really excellent tool!
