### ISSUE TITLE
Bind 'click' events on links to 'document'.

### ISSUE THREAD

**Issue by mrself** [krasimir/navigo#33]
When binding an event to links at start it will not catch clicks on links which are loaded later. For example if I load a new template with links, router will not change the url properly.

I think it would be better to bind event to document:

```
$(document).bind('click', '[data-navigo]', function() {
  // do stuff
}
```

**Comment by krasimir** [comment]
Well, together with the page change Navigo makes sure that the links have `e.preventDefault()` so when the user clicks them only the JavaScript bit is fired. Even if we attach an event handler to the `document` object we still have to go through the binding process so we get that `preventDefault()` call. 

I think a proper approach here should be to fire `updatePageLinks` on the Navigo instance once your view is rendered. The router don't have this knowledge so we can't do that automatically. 

P.S.
`updatePageLinks` is not documented, sorry. Will add this to the README now.

**Comment by colin-aarts** [comment]
Actually, you can preventDefault from a delegated listener just fine. Since I don't like Navigo's implementation, I'm using this (I simulate a popstate event and call `resolve` from the popstate handler, but you would do whatever there):

```livescript
document.add-event-listener 'click', (e) ->
	el = e.target
	if el = find-capture-link el
		e.prevent-default!
		trigger-popstate! # Or whatever…

function find-capture-link el
	do
		return el if el.has-attribute 'data-capture-link'
	while el = el.parent-element
```

Other than that, I'm really digging Navigo though, nice work!

**Comment by krasimir** [comment]
@mrself I'm closing here but let me know if firing `updatePageLinks` didn't fix your issue and we'll reopen it.
