### ISSUE TITLE
Double event handler after updatePageLinks()

### ISSUE THREAD

**Issue by oomarsmanoo** [krasimir/navigo#34]
Hey, first of all thank you for this simplistic but very helpful router :)

I've got a problem where updatePageLinks doesn't work as intended in the minified version. It somehow adds multiple (in my case even different) click handlers to an <a> element with data-navigo attribute. I think it is because in the minified file link.hasListenerAttached isn't set to true correctly. The different click handlers could be because I'm exchanging the href attribute though...

In the non-minified version everything works fine though

**Comment by krasimir** [comment]
Hey, just built a new version 2.1.4. Can you please try the new files. They should be the same now.

**Comment by oomarsmanoo** [comment]
jep works, thank you :)

**Comment by krasimir** [comment]
👍

**Comment by oomarsmanoo** [comment]
Hey, got back to work today and found out that I must have missed something while testing and it is actually not working right :(
same problem as before - just this time both files are not working.
Found out that it's because the hasListenerAttached is assigned inside the click handler. This should have been fixed in [this](https://github.com/krasimir/navigo/pull/28) commit but didn't make it in the minified file which caused my problems in the first place. Now it was undone by the latest release altogether, so both files don't work correctly.

**Comment by krasimir** [comment]
Hm ... that's weird. I roll back the change in a new `2.1.5` version. Can you please try if it works now.

**Comment by oomarsmanoo** [comment]
Yep, working now, thanks a lot! :)
