### ISSUE TITLE
pushState - state object support

### ISSUE THREAD

**Issue by estrattonbailey** [krasimir/navigo#35]
Hey, thanks for the awesome library :)

Do you have plans to implement support for the state object param of `History.pushState()`? 

My current use case is to save scroll position between pages. The site I'm working on is fully AJAXed so I can persist a variable with the scroll position between page transitions. But, if a user reloads the page, the previous scroll position is lost. So then if they hit the back button, the page scrolls back to the top regardless of where they were previously.

Seems like the cleanest way to do it would be to just push a state object along with the route to `router.navigate(path = '', state = {}, absolute = false)`. I'm happy to open a PR if you like this idea, or defer to you if you already have this feature in the works.

**Comment by krasimir** [comment]
Hey,

I never hit that use case. Happy to accept a PR fpr such feature though.

**Comment by krasimir** [comment]
Hey @estrattonbailey,

I'm trying to clean up old issues. So, is there any development around your idea. For me it seems like the desired behavior, i.e. keeping the state, should be done outside of the router. What's your motivation about sending it to Navigo. Is it that you want to receive the state in your handler?

**Comment by estrattonbailey** [comment]
Hey @krasimir, apologies on never coming back to close this, thanks for your follow up. 

I worked with a forked Navigo with state previously, but in hindsight it makes more sense to just use `history.replaceState()` to track stuff like scroll position. The little [library](https://github.com/estrattonbailey/operator.js) I was working on actually uses that method now, and works pretty well. 

Thanks for you lib! Great stuff 👌
