### ISSUE TITLE
demo with hash routes

### ISSUE THREAD

**Issue by mckennatim** [krasimir/navigo#38]
When using the demo site everything works as expected using the history api. But when you click the "hashed based routing" box in the upper right (and even after refresh) you get 

http://work.krasimirtsonev.com/git/navigo/#about
http://work.krasimirtsonev.com/git/navigo/#usage
http://work.krasimirtsonev.com/git/navigo/#download
ok 
but then
http://work.krasimirtsonev.com/git/navigo/testing (quickly replaces #test)
and from then on the hash is after /testing 
http://work.krasimirtsonev.com/git/navigo/testing#download
http://work.krasimirtsonev.com/git/navigo/testing#usage

That doesn't seem right.

**Comment by krasimir** [comment]
I should kill that page. The version of Navigo is not up-to-date + the tests there exercise the library and they change the URL several times using both modes of Navigo. When the tests finish I try returning the page to its initial state but it looks like I failed at this.
