### ISSUE TITLE
Got error when get path more then one.

### ISSUE THREAD

**Issue by antana013** [krasimir/navigo#40]
Hi,

I have a problem when I used your lib. when I need to set path more then one i got error message in console like this
`bundle.js:1 Uncaught SyntaxError: Unexpected token <`

this is my code 
```
const Navigo = require('navigo');
var router = new Navigo();
router.on({
  'path/to/some/where'  : () => {
    console.log('path/to/some/where');
  },

  '/'       : () => {
    console.log('Home');
  },
});
router.resolve();
```

this is .htaccess
```
<ifModule mod_rewrite.c>
  Options +FollowSymLinks
  IndexIgnore */*
  RewriteEngine On
  RewriteCond %{REQUEST_FILENAME} !-f
  RewriteCond %{REQUEST_FILENAME} !-d
  RewriteRule (.*) index.html
</ifModule>
```

`localhost` page ware working fine BUT `localhost/path/to/some/where` got error I told you above.

**Comment by krasimir** [comment]
Something is not ok with your server. The error that you are talking about is displayed when the browser serves html where should be javascript. Can you please try using absolute URLs for your assets. Like instead of `<script src="./js/app.js"></script>` you type `<script src="http://site.com/js/app.js"></script>`

**Comment by antana013** [comment]
@krasimir Ohhhh, It's because of javascript include path the same as you told me. :))
before :
`<script src="/assets/bundle.js" type="text/javascript"></script>`
after : 
`<script src="http://localhost/assets/bundle.js" type="text/javascript"></script>`

Thank you so much. 👍

**Comment by krasimir** [comment]
You are welcome.
