### ISSUE TITLE
Callback don't fire if navigating between some URL and `/`, but URL is changing

### ISSUE THREAD

**Issue by hudochenkov** [krasimir/navigo#41]
The bug is reproducing here with Navigo 2.3.0:

https://jsbin.com/ximekug/edit?html,js,output — source code
https://output.jsbin.com/ximekug/ — there you can see URL changing

With each click text under the list should change according to link.

Steps to reproduce:

1. Click “Task 1” → correct
2. Click “Home” → correct
3. Click “Task 1” → fail

URL changed, but text under the list didn't.

Also can be reproduced this way:

1. Click “Task 1” → correct
2. Click back button in a browser → correct
3. Click forward button in a browser → fail

If we click “Task 1” → “Home” → “Task 2” → “Home” → “Task 1” → ... It works as expected.

**Comment by krasimir** [comment]
Hey, sorry for the delay. It's fixed in the new `2.3.1` version. Just double checked your jsbin. It works as expected.

**Comment by hudochenkov** [comment]
Thank you so much! Navigo is amazing, you did a great job!
