### ISSUE TITLE
All routes are greedy?

### ISSUE THREAD

**Issue by emflores** [krasimir/navigo#43]
Hi @krasimir - thanks for your work Navigo, really liking it so far.

I have encountered one issue that I wanted to raise , and that is that all routes seem to be greedy. Meaning that, given a route of `/foo`, the `findMatchedRoutes` function will return a positive match for the path `/foo/bar`, regardless of whether or not a wildcard is used. I believe this RegExp is to blame: https://github.com/krasimir/navigo/blob/master/src/index.js#L5.

Was this an intentional design decision? If not, I am happy to open a PR to fix this issue. Regardless, probably should add a spec to cover this case.

**Comment by krasimir** [comment]
That's a bug. So PR are welcomed. Feel free to submit some or I'll do it next few days.

P.S.
thanks for reporting

**Comment by Mevrael** [comment]
Hi I have 
```javascript
router.on('/', IndexPage).resolve();
```
however it is fired on every page, I've also tried without 1st param.

**Comment by krasimir** [comment]
@Mevrael can you please post all of your code. I mean the initialization of the router and all the attached routes.

**Comment by Mevrael** [comment]
Hi @krasimir 

Thank you for response. Here is my code. Basically I just started with only 1 route, I have a new page where I don't need what is happening on index but it is also executed.

Init with default settings.

```js
import Navigo from 'navigo/src/index';
import IndexPage from './pages/IndexPage';

const router = new Navigo;
router.on('/', IndexPage).resolve();
```

**Comment by krasimir** [comment]
Ok, but do you have anohter `.on` call?

**Comment by Mevrael** [comment]
No

**Comment by krasimir** [comment]
So you have an index page which is represented with `IndexPage`. You registered only this function to the router and nothing else. If you want to get another method fired you need to add another `.on` line with the appropriate route and function.

**Comment by Mevrael** [comment]
I don't want to register any other routes (for now), I just don't need to call my IndexPage function on every route /*

There is no specific logic on 2nd page, it just uses global plugins. But because IndexPage is called there I got some errors since 2nd page does not have those DOM elements and data from the index.

**Comment by krasimir** [comment]
I see ... then I'll suggest to organize your code like that so you don't have the router initialize on the second page at all.
