### ISSUE TITLE
The last param on parameterized routes also takes the query section of the url

### ISSUE THREAD

**Issue by panda01** [krasimir/navigo#47]
It seems to me that if you have something like 
```
Router.on('/foo/:foo/bar/:bar', (params) => {console.log(params)}.resolve();
```
And you navigate to /foo/4/bar/5?a=c 

params.bar will equal "5?a=c" as opposed to just 5.

**Comment by krasimir** [comment]
Can you please try the new `2.3.4` version. Should be [fixed](https://github.com/krasimir/navigo/commit/b1d7a989d37f03d7c81c0376230bc4132e297ea7#diff-277e1b0de0f676904bb46f6b48d2836fR299) now.

**Comment by panda01** [comment]
Word, looks good to me. Thanks a bunch man!
