### ISSUE TITLE
Lost query parameters

### ISSUE THREAD

**Issue by markcarver** [krasimir/navigo#49]
My original code just extracted any query parameters from the last `params` property that was resolved. I honestly thought that this was how it was designed to work... but w/e.

Since https://github.com/krasimir/navigo/commit/b1d7a989d37f03d7c81c0376230bc4132e297ea7#diff-1fdf421c05c1140f6d71444ea2b27638R95 query parameters are now completely lost (they're just stripped).

If Navigo is going to interfere with query parameters now, it should instead pass an additional parameter to the callback with the string it removed so applications that relied on it can upgrade, e.g.

```js
router
  .on('/user/:id/:action', function (params, query) {
    // ......................................^
  })
```

**Comment by krasimir** [comment]
@markcarver sorry for the delay answer. Have no idea how I missed your issue. That's a nice suggestion. I'll see how complex is the implementation.

**Comment by krasimir** [comment]
`3.2.0` released. It follows your suggestion -> https://github.com/krasimir/navigo#accessing-get-parameters
