### ISSUE TITLE
Router is not defined on empty path

### ISSUE THREAD

**Issue by cwetanow** [krasimir/navigo#50]
```
let router = new Navigo(null, false);

router
    .on('#/home', controllers.home)
    .on(() => {
        router.navigate("#/home");
    })
    .resolve();
```

When the path in the browser is empty I get the following error 
Uncaught (in promise) Error: (SystemJS) router is not defined(…)

Do you have any ideas why, the module is loaded with systemjs

**Comment by krasimir** [comment]
Hey, it's difficult to say why this is happening. I see that you define the router with `let`. Can you try using `var` and let us know if that helps.
