### ISSUE TITLE
navigate doesn't resolve if only querystring params have changed

### ISSUE THREAD

**Issue by johnwheeler** [krasimir/navigo#53]
Hello,

Thank you for Navigo. Forgive me if this is by design, but I noticed that changing just the querystring of a route and calling navigate does not resolve. I think this is a side effect from removeGETParameters that was introduced a few weeks ago. Is this a bug and if not, is there a workaround?

Thanks

**Comment by krasimir** [comment]
Can you please try the new `3.2.1`. It's addressing this bug.

**Comment by krasimir** [comment]
@johnwheeler let me know if the new version is not fixing your bug. For the time being I'll close this issue.
