### ISSUE TITLE
onhashchange for resolving

### ISSUE THREAD

**Issue by cloudever** [krasimir/navigo#55]
@krasimir maybe it's time to use **onhashchange** event instead of **setTimeout** for resolving the hash state, but keep last one in the code as a fallback?
Browser support [https://developer.mozilla.org/ru/docs/Web/API/WindowEventHandlers/onhashchange](https://developer.mozilla.org/ru/docs/Web/API/WindowEventHandlers/onhashchange)

**Comment by krasimir** [comment]
👍 good suggestion.

**Comment by krasimir** [comment]
`3.3.0` released.
