### ISSUE TITLE
Navigo triggers resolve for hash with hash navigation disabled

### ISSUE THREAD

**Issue by sergiovilar** [krasimir/navigo#57]
Hey, I'm having a problem with Navigo.

I have this url:
`http://localhost:3000/users/foo#section1`

In this page I have some tabs (section1, section0) when I click any of the tabs and the url changes to, for instance, `http://localhost:3000/users/foo#section1` Navigo triggers the resolve even with the hash navigation disabled.

**Comment by krasimir** [comment]
So is it like the URL is not changed but you get your handler called?

**Comment by sergiovilar** [comment]
@krasimir only the hash changes and still yet I get the route resolved.

**Comment by krasimir** [comment]
I see. That's a bug. I'll try providing a fix.

**Comment by sergiovilar** [comment]
@krasimir I have some use cases:
1. The url changes from a hash to another
2. The url changes from no hash to a hash
3. The url changes from a hash to no hash

**Comment by krasimir** [comment]
@sergiovilar can you please try `3.3.2` version.

**Comment by sergiovilar** [comment]
@krasimir Just readed your commit and tested here. The `*` handler still get triggered by hash change when hash navigation is disabled.

**Comment by sergiovilar** [comment]
`notFound` handler also gets resolved when I am in this url: `http://localhost:3000/some#tab1` and changes to `http://localhost:3000/stores#tab0`.

**Comment by krasimir** [comment]
@sergiovilar second try. Can you please the new 3.3.3 version.

**Comment by sergiovilar** [comment]
@krasimir works like a charm, thank you!

**Comment by JurajVajda** [comment]
Hi @sergiovilar what is your workaround this issue, i have the same problem.
