### ISSUE TITLE
Callback function on route change

### ISSUE THREAD

**Issue by luckyshot** [krasimir/navigo#6]
Is there a way to specify a callback function through Navigo any time the route changes?

**Comment by krasimir** [comment]
Actually, yes. It is possible. There is a `resolve` method which is called every time when the route is changed. You may overwrite it like so:
```js
// I assume that you have a `router` object
var router = new Navigo();
var navigoResolve = router.resolve.bind(router);

router.resolve = function () {
  console.log('custom stuff here');
  navigoResolve();
};
```
In this case you should see the `console.log` every time when the route is updated.

Let me know if that works for you.

**Comment by luckyshot** [comment]
Amazing, thanks a lot @krasimir, it works great.

**Comment by krasimir** [comment]
:+1:
