### ISSUE TITLE
Hash in URL becomes part of param

### ISSUE THREAD

**Issue by tnguyen14** [krasimir/navigo#61]
If I have the URL `https://mysite.com/page#`, and a route defined as `/:id`, then `params.id` is `page#`. Should it just be `page`? I.e. the `#` should not be considered part of the param?

I'm running into this issue because Chrome automatically appends `#` to my URL after redirecting from another page that has `#` in its URL

**Comment by krasimir** [comment]
Half a year later :) This is no more an issue. This line prevent such behavior https://github.com/krasimir/navigo/blob/master/src/index.js#L106

**Comment by volmus** [comment]
@krasimir two more years later:
How to handle URLs containing hashes?

e.g. `https://mysite.com/foo/foo-#-bar/bar`
This route is not recognized from following route:
router.on({"/foo/*/:id")
