### ISSUE TITLE
Include pause in navigate

### ISSUE THREAD

**Issue by tnguyen14** [krasimir/navigo#62]
Instead of having to `.pause` the router before `.navigate` in order to skip resolving, can the resolve/ paused state be passed in as a boolean to `.navigate()`?

For eg., instead of having to do
```router.pause(true);
router.navigate('/path');
router.pause(false);
```

It will just be 
```router.navigate('/path', false);```

I find the `.pause(false)` API to be extremely awkward.

**Comment by krasimir** [comment]
Well, I found `.pause(false)` a lot better then `.navigate('/path', false)` for a couple of reasons:
* It's explicit. Imagine that you are reading some code and you see `.pause(true)` and you think "Ok, we are enabling something here". Passing `false` to `navigate` doesn't give any knowledge what is this `false` about. 
* It's really weird that we on a flag using a method (`pause`) but turn it off using another method (`navigate`).

If that `pause(false)` seems awkward then maybe the whole idea of pausing seems awkward too but I'm not really keen to change the API.

**Comment by tnguyen14** [comment]
Thanks for the response.

I hear you on changing the API part. Something awkward might not be reason enough to change the API, but perhaps something you can keep in the back of your mind, and see if you'd want to include it in the next major release (that could be due to a different reason).

Also, instead of `.pause(true)` and `.pause(false`, perhaps you could consider something like `.pause()` and `.resume()`. They would do the same thing under the hood, but a bit easier to understand.

About being explicit - I agree with you about that. Though I think `.navigate('url', false)` is a good signal that something is different as well. Either case would require you to look back into the API doc to actually understand what it does.

I think it makes sense to keep `.pause()` if there are other use cases where it could be used. However, if switching `replaceState` with `pushState` for `navigate` is the only thing that it does, but to me it makes sense pull it into `navigate`, and name that flag `pushState`, instead of `pause`, which isn't immediately clear either.

When I was looking into this API, I wanted to find out how to do `replaceState`, and accidentally stumble upon `pause` by perusing the doc, as it wasn't immediately searchable.

**Comment by krasimir** [comment]
`3.5.0` is released. It contains a `resume` method which is the same as `pause(false)`. `pause` now called without any parameters is always equal to `pause(true)`. I like this suggestion. Thanks.

I see your points about `replaceState` and the unclarity around what `pause` is doing. I'll keep a note about that and I may indeed change the naming in some of the next releases.
