### ISSUE TITLE
Have title option for routes config

### ISSUE THREAD

**Issue by metame** [krasimir/navigo#65]
Browser history is helpful but would be better if there were optional custom titles for each route.  This would be a lightweight feature add-on but something very useful built-in to the router. Currently I change it in the route handler.  Since navigo is already handling history state, this might be something useful for others.  Is this something anyone else is interested in?  I'd be willing to make the changes if we could agree on a reasonable syntax.

**Comment by krasimir** [comment]
Do you mean something like [named routes](https://github.com/krasimir/navigo#named-routes)?

**Comment by metame** [comment]
Don't think so.  In this case, I'm talking about changing the Document Title, like with `document.title = 'Home Page'`.

**Comment by krasimir** [comment]
I see now. I would escape from putting such features in the router. For me seems like similar things are really context/domain specific and will only bloat the API. 

However, I may think for a plugin system or something like that where stuff get injected.

**Comment by TheMangoTrain** [comment]
OP mentioned changing page title within handlers. Below is a basic example for anyone needing it:

router.on({
        'find': () => {
            LoadFind()
        },
        'post': () => {
            LoadPost()
        },
        'event': () => {
            LoadEvent()
        }
    });



function LoadFind() {
    RouterLoadHTML('./templates/find.html', 'content');
    top.document.title = "MYWEBSITE - Find";
}

function LoadEvent() {
    RouterLoadHTML('./templates/event.html', 'content');
    top.document.title = "MYWEBSITE - Event";
}

function LoadPost() {
    RouterLoadHTML('./templates/post.html', 'content');
    top.document.title = "MYWEBSITE - Post";
}
