### ISSUE TITLE
Bower release version outdated

### ISSUE THREAD

**Issue by flibbertigibbet** [krasimir/navigo#66]
The latest version available for install via Bower is 3.0.0, but the latest release for install via npm is 3.5.0.

**Comment by krasimir** [comment]
Hey, good point. Just tagged the latest commit version with `3.5.0`. Shall I do something else or bower will take it from here.

**Comment by flibbertigibbet** [comment]
That did it, thanks!

I was going to mention maybe adding `version` to the bower.json, but apparently that gets ignored now, according to the [spec](https://github.com/bower/spec/blob/master/json.md#version).
