### ISSUE TITLE
Navigation not firing in IE 10+ when using back and forward buttons

### ISSUE THREAD

**Issue by hussainb** [krasimir/navigo#67]
Hello,

I have initialized navigo by passing the useHash as false and proper root value.
Works fine in browsers like Firefox and chrome etc but doesn't function in IE.

The URL changes but the .on callback function doesn't fire.

Thanks for the awesome and minimalist routing library.

**Comment by aziev** [comment]
I have similar problem. My code:
```javascript
router.on({
    '/': function(){
        console.log('navigated to /');
    },
    'category/:slug': function(params){
        console.log('navigated to /category/:slug');
    },
})
.resolve();
```
When I go to url `example.com/category/morning` it outputs 'navigated to /'.
This problem occures in Microsoft Edge, Safari (MacBook, iPhone 5s, iPhone 6), Chrome (iPhone 4)

**Comment by hussainb** [comment]
Further digging into it, I found that the back and forward buttons on IE gets messed up after using the router.navigate() method

**Comment by krasimir** [comment]
Hey, what's the version of IE that you are testing with.

**Comment by hussainb** [comment]
Its the latest IE Edge which comes installed with windows 10

**Comment by krasimir** [comment]
Ok, thanks. I'll investigate.

**Comment by hussainb** [comment]
I tried tracing it, not sure but I think the window.onpopstate event doesn't fire after calling router.navigate()

**Comment by krasimir** [comment]
@hussainb sorry for the delay. I finally managed to test it under IE 11. And it works pretty well [here](http://work.krasimirtsonev.com/git/navigo/). I was able to use both modes (with and without History API) + the back and forward buttons of the browser works. Can you please share your code and let me know if you have a proper [server-side](http://krasimirtsonev.com/blog/article/deep-dive-into-client-side-routing-navigo-pushstate-hash#client-side-routing-is-not-exactly-only-client-side) setup.
