### ISSUE TITLE
DOM7011: The code on this page disabled back and forward caching.

### ISSUE THREAD

**Issue by dvwright** [krasimir/navigo#68]
Hi, I am having issues with Navigo on IE 11. Chrome, Firefox, Opera, Safari all work as expected but Internet Explorer 11 is not rendering or navigating correctly. 

The above is listed as a warning so it shouldn't be affecting content rendering. The content will appear to load as expected, then this warning will appear in the console and the page will go blank. 

FWIW, the router is calling a method which get's it content from an ajax call. I will try to create a small example to recreate the issue. Has anyone experienced this issue? Ideas? Thank you

**Comment by krasimir** [comment]
Hey,

yep, a publicly available example will be fine because I just [tested](https://github.com/krasimir/navigo/issues/67) the library in IE11 and it worked well.

**Comment by dvwright** [comment]
Hi, here is a gist which demonstrates the issue. https://gist.github.com/dvwright/4982163aeb949d0d503c4c1ee6916c5f

**Comment by krasimir** [comment]
Thanks. I'm now able to reproduce it. I'll inform you when the bug is fixed.

**Comment by krasimir** [comment]
So it looks like I found where is the problem. When using an object notation syntax we get different results in different browsers. Here's what I mean:

In Chrome if you type
```
router.on({
  '': function() { ... },
  '/n': function() { ... },
  '/p': function() { ... },
  '/u': function() { ... }
})
```
You get the following order of route addition:
```
"/n"
"/p"
"/u"
""
```
While in IE11 (and Safari under Mac by the way) you get:
```
""
"/n"
"/p"
"/u"
```
So, what happen in your case is that the resolve method always matches the root route (`""` one). It doesn't reach the others and you get always `root` on the page. 

To solve the problem I'll suggest to use:
```
router
  .on('/n', function() { ... })
  .on('/p', function() { ... })
  .on('/u', function() { ... })
  .on('', function() { ... });
```
Notice that the empty string is at the end. The router resolves routes following the order of addition.

**Comment by dvwright** [comment]
So, the solution here (re-org routes) helped one of the issues I was having. I was just able to resolve the other issue and thought I would add the info here just in case someone else has a similar issue.

I am using jquery, binding to events and triggering navigation, such as:

```
    $(document.body).on('click', '#user', function(e) {
        e.preventDefault(); // <- This is essential!
        router.navigate('/user');
    });
```

the preventDefault is required, otherwise navigating like this was failing in IE11.
