### ISSUE TITLE
NotFound handler not happening correctly when actually refreshing the webpage

### ISSUE THREAD

**Issue by UsernamesAreOutdated** [krasimir/navigo#70]
I have configured my routing like this:

http://pastebin.com/n5MnDQGW

This works all good while using my website.
Declared url's work, home/root page works too. Even going to url's which are not routed are going to the not found handler just fine.
Except for when you then actually refresh the page (browser F5), then the non existent url just shows the home/root page.

Any idea?

**Comment by krasimir** [comment]
Can you please try 3.5.1 version. It should fix your problem.

**Comment by UsernamesAreOutdated** [comment]
It is OK now. Thanks!

**Comment by danazkari** [comment]
Hello, I'm on version 4.0.1 and I'm experiencing the same issue, notFound handler is not triggered when refreshing. Any pointers as to why that might be happening again?

![image](https://cloud.githubusercontent.com/assets/349542/22933532/7d3ba6ac-f291-11e6-885e-8968f33ce104.png)

Views is just an object where the keys are url routes and values are the function handlers for each route.

**Comment by krasimir** [comment]
@danazkari can you try adding the `on(() ...` and `.notFound(() ...` after `.on(Views)`.

**Comment by danazkari** [comment]
@krasimir just did, no dice. Also moved the order of default and notFound and nada.

**Comment by danazkari** [comment]
If it helps, whenever I load a non-valid URL and shows the homepage, if I navigate using the navigo js api to `/` (root), it shows me the 404 page. Seems like it's taking the first `wrong` url and using it as it's base for the SPA.

**Comment by krasimir** [comment]
Can you paste the initialization of the router.
