### ISSUE TITLE
when useHash = true, generate() should prefix # to returned route string

### ISSUE THREAD

**Issue by leeoniya** [krasimir/navigo#71]
@krasimir ping :)

**Comment by krasimir** [comment]
@leeoniya good catch! I'll try cleaning the issue here (in Navigo) this weekend.

**Comment by krasimir** [comment]
@leeoniya can you please try `4.0.0` version. It should fix the problem.

**Comment by leeoniya** [comment]
probably yes, though i've switched my own router that's closer to my preferred api.

thanks!

**Comment by UsernamesAreOutdated** [comment]
The minified file is outdated now, had to take non minified version for this to work.
