### ISSUE TITLE
unicode characters

### ISSUE THREAD

**Issue by hamed743** [krasimir/navigo#74]
is this working with unicode characters?

**Comment by krasimir** [comment]
Interesting. Can you come with a test case. I mean do you mean an unicode character in the name of the route?

**Comment by hamed743** [comment]
yes. i want unicode characters like arabic or hebrew in url.
somthing like this:
`router
  .on('/محصولات/list', function () {
    // display all the products
  })
  .resolve();`

**Comment by krasimir** [comment]
Yep, it's definitely working. I just added a test.
