### ISSUE TITLE
Support express-style regexp matching with named parameters?

### ISSUE THREAD

**Issue by lapinskicho** [krasimir/navigo#75]
Thanks for your module, it looks great.

I am evaluating Navigo and it supports paths like "/movies/:id(\\d+)' but looks like it does not support paths like '/movies/:genre(horror|romance)' (a choice of different strings) - which express supports by using [path-to-regexp npm package](https://github.com/pillarjs/path-to-regexp) .  I am trying to share my express route definitions with the front-end, it will save a lot of work to do a server-side route mapping to Navigo if the path matching mechanisms are consistent on both ends.

Not sure if it is a bug or it is not supported, or I just missed something in the syntax?

**Comment by krasimir** [comment]
Hm ... interesting. Definitely Navigo is not supporting your use case now. I'm a little bit surprised that `:id(\d+)` works. That part of the library is fairly complex and I prefer to keep it as it is. I'm planning to rewrite the library and will definitely use `path-to-regexp` module. Seems really nice.
