### ISSUE TITLE
Find wrong route in IE11

### ISSUE THREAD

**Issue by olofweb** [krasimir/navigo#77]
Hi, I have a problem on IE11 with your demo (http://work.krasimirtsonev.com/git/navigo/).

The function `match(url, routes)` call `findMatchedRoutes(url, routes)` and take the first element. But the order of elements is different depending of the browser.

In IE, "root" route is first but not in Chrome. So in IE, "root" route is always returned as matched route.

IE :
![ie](https://cloud.githubusercontent.com/assets/442596/22787856/00817b7a-eede-11e6-9bbf-e63f770b96f6.png)

Chrome :
![chrome](https://cloud.githubusercontent.com/assets/442596/22787857/008425c8-eede-11e6-8f04-cb59e2da6715.png)

**Comment by krasimir** [comment]
Fixed by #78.
