### ISSUE TITLE
Change url only after before hook done function is called

### ISSUE THREAD

**Issue by joaopmafra** [krasimir/navigo#79]
Hi,

If I have a route like this:
```
router
    .on('r1', {
        as: 'r1',
        uses: function () { ... },
        hooks: {
            before: function (done) {
                done(false);
            }
        }
    })
    .resolve();
```

and call `router.navigate("r1")`, the url is changed anyway. In the before hook, calling `done(false)` shouldn't prevent url from changing? Is there some way to accomplish that with your lib?

Thanks.

**Comment by krasimir** [comment]
That's definitely a valid argument. I'll prepare a PR.

**Comment by krasimir** [comment]
It looks like this feature is already there. I just made a test https://github.com/krasimir/navigo/commit/4ca151e63df350a47f0c0d73bab1679ef1e6b0c7

I'm really confused why is not working for you. Can you please try with the latest version.

**Comment by krasimir** [comment]
@joaopmafra ping me if the problem appears with the latest version.
