### ISSUE TITLE
Direct Links

### ISSUE THREAD

**Issue by shakna-israel** [krasimir/navigo#81]
I'm having some trouble. I'd like my users to be able to use direct links.

My server supports SPA by redirecting everything that isn't the root url to a 200.html page.

A direct link isn't running the route to render.

I've sort of got around it by doing:

```
window.onload = () ->
  ref = "/" + (location.pathname + location.search).substr(1)
  router.updatePageLinks()
  if ref != window.loaded
    router.navigate(ref)
```

And each route updates what window.loaded should be.

This gets the right page to render. However, the URL doesn't update.

Any thoughts?

Edit:

Minimal example [here](https://squishelsandme.surge.sh).

Click the link, click Test Link, and then click the title, and it works.

But, go [here](https://squishelsandme.surge.sh/post/2014-02-03/Humans), and click the title, the page re-renders... But the url bar doesn't update.

**Comment by Nyholm** [comment]
Did you try to enable hashes?

`var router = new Navigo(null, true);`

**Comment by krasimir** [comment]
Hey, sorry for the late reply @shakna-israel. Here are couple of things which I'm wondering:
* What's the browser that you are testing in?
* Is the page reloaded when you open the link or that's a SPA?
* By `But the url bar doesn't update.` do you mean that you don't get the new URL after calling the `navigate` method?

**Comment by flowen** [comment]
hi, I think I have a similar problem. I enabled hashes, but direct links don't work. I use the router to forward hashes to ajax calls to the Wordpress REST api. 

so for example:
router.on('front-end-dev', () => request('http://example.com/wp-json/v2/posts/', '#tmpl-fe'))
request() is a function that handles the ajax request to the url, then uses Handlebars to compile the results into #tmpl-fe. 

Anyhow, I don't think there's anything to fancy here. Clicking links in the nav works fine (I added data-navigo attr). But direct links simply don't work. A hard refresh (with the hash in the url) always sends me to the index.

**Comment by flowen** [comment]
I should add that the forward and back buttons work as expected (didn't do any deep testing)

**Comment by flowen** [comment]
@krasimir just a friendly bump :)

**Comment by krasimir** [comment]
Hey guys,

sorry for the ridicules delay. Can you please explain what you mean by *direct* links. Just as a reminder:
* If there's no `data-navigo` Navigo is not processing the link so clicking on those will probably force a page update
* If Navigo initialization runs and then you change DOM, i.e. add your links make sure that you call `updatePageLinks`. Otherwise Navigo will not process the links.

**Comment by flowen** [comment]
@krasimir you can see an example on my portfolio: flowen.me
if you press a link, you're forwarded to this for example: http://flowen.me/#!/creative-coding
But if you copy and paste this link into the browser, I'm redirected to the root page.

**Comment by krasimir** [comment]
@flowen can you please try calling `resolve` once you finish with the routes definition (I mean the `on` calls).

**Comment by flowen** [comment]
@krasimir ooohhh completely overlooked that. Thanks! fixed it for me!
