### ISSUE TITLE
It seems that url navigation is handled by the server, but not navigo. Page refreshes from server.

### ISSUE THREAD

**Issue by idchlife** [krasimir/navigo#83]
https://monosnap.com/file/fm5WTBNx7ygUHoPrDQoZJ2yGXFKFAr

Here is the video showing that whenever I navigate, I'm getting refreshed page from servers and after this navigo of course handles route. But it seems it does not work with history. Or am I missing something?

**Comment by krasimir** [comment]
Yep, that's exactly what happens in the video. Can you please post your code. I mean the initializing of the router and the routes. Also what's the output of this:
```js
!!(
  typeof window !== 'undefined' &&
  window.history &&
  window.history.pushState
)
```

**Comment by idchlife** [comment]
@krasimir it was my mistake actually. I did not know that every link has to be manually forced to do router.navigate (using react, so refreshing links for navigo is basically useless there, better to call .navigate in code)

Everything seems to work fine! Thanks!
