### ISSUE TITLE
Build error on master

### ISSUE THREAD

**Issue by Nyholm** [krasimir/navigo#84]
I cloned the repo, ran `npm install` and then `npm build`. I got no output. After that I did: 

```
[tobias@Tobias-MBP:xxxx/node_modules/navigo on master]
% WEBPACK_ENV=build ./node_modules/.bin/webpack
Hash: b8b3bb7531cc9e722568
Version: webpack 1.12.12
Time: 75ms
    + 1 hidden modules

ERROR in ./src/index.js
Module parse failed: /Users/tobias/Workspace/PHPStorm/nextlease/nextlease-embeddable-client/node_modules/navigo/src/index.js Line 341: Unexpected token
You may need an appropriate loader to handle this file type.
| };
| 
| export default Navigo;
| 
```

Using Node 6.10.0.

**Comment by krasimir** [comment]
Thanks for reporting. I'm planning some time today to cover last couple of issues.

**Comment by Nyholm** [comment]
Thank you. You are great!

I have a upcoming PR but I could not test it yet. I'll submit it as a WIP

**Comment by krasimir** [comment]
Hm ... just tested your scenario. Fresh clone `npm install` and then `npm run build`. I'm using node 6.7.0 and it works fine. Can you please try running `npm run build` instead of `npm build`?

**Comment by Nyholm** [comment]
Thank you. It is working.
