### ISSUE TITLE
Navigo.generate includes hash

### ISSUE THREAD

**Issue by Nyholm** [krasimir/navigo#87]
If one is using hashes the `router.generate('foo')` will include the hash. 

This means that: 
```js
router.navigate(router.generate('foo'));
// Navigates to `#url` which will be "www.example.com/##url"
```

Im not sure what the best solution is here. Either we remove the hash from `generate` or we make sure to trim it in `navigate`.

**Comment by krasimir** [comment]
Just released `4.3.3` that contains a fix for this issue.

**Comment by Nyholm** [comment]
Thank you. But please use PRs. That will mean I have a change to review your code.

**Comment by krasimir** [comment]
@Nyholm that's a very good point 👍
