### ISSUE TITLE
Is a .on() call needed for each path if you want to use hooks?

### ISSUE THREAD

**Issue by finppp** [krasimir/navigo#88]
Is there a way to list multiple paths without calling .on() for each?

Thanks

Also (unrelated),  in the readme it has this (under Hooks):

```
{
  before: function (done) { ... done(); }
  after: function () { ... }
}
```
is there meant to be a comma after 'before' line?
```
{
  before: function (done) { ... done(); },
  after: function () { ... }
}
```

**Comment by krasimir** [comment]
Yep, that's a typo in the README. As for the other question. Isn't it this:
```js
router
  .on({
    '/products/list': function () { ... },
    '/products': function () { ... },
    ...
  })
  .resolve();
```

**Comment by finppp** [comment]
Sorry, I meant can you use hooks with each route, without multiple .on calls.

e.g. something like this:
```
router
  .on({
    '/products/list': function () { ... }, {hooksObject1}
    '/products': function () { ... }, {hooksObject2}
    ...
  })
  .resolve();
```

**Comment by krasimir** [comment]
Ah I see. At the moment there is no such syntax and to be honest I'm a little bit reserved extending that bit of the library. The `on` method was patched multiple times just for syntax reasoning and it really gets messy.

**Comment by finppp** [comment]
Cool, thanks for the info!
