### ISSUE TITLE
Click handler...

### ISSUE THREAD

**Issue by chiefcll** [krasimir/navigo#9]
Like the simplicity of your router, but it would be nice to have a simple click handler to intercept `<a href='/route'>` clicks. Is that on the roadmap?

**Comment by krasimir** [comment]
@chiefcll That's actually a really good idea. I'll write here once the new version is released.

**Comment by krasimir** [comment]
@chiefcll there is a new `1.1.0` published. What I did is to provide a `router.link` method. It accepts a `path` and returns a full url. I was thinking generating a HTML link but decided to return url only. It's just more flexible and doesn't tight the consumer of the API to specific tag/markup.

**Comment by chiefcll** [comment]
I was describing something else where programmers could have standard html anchor tags and navigo would intercept click events, read the href and navigate based on that.  Something like what pagejs is doing:
https://github.com/visionmedia/page.js/blob/master/page.js#L541

**Comment by krasimir** [comment]
I see. That's also a good idea. I'll make this possible but not in the same way as it works in pagejs. I'm thinking about marking a link with `data-navigo` attribute. Fetching all the links and trying to guess what they do is a little bit too much for this project.

**Comment by krasimir** [comment]
@chiefcll It's done. There is a new `1.2.1` version released. All you have to do is to add `data-navigo` attribute to your links. For example:
```html
<a href="about" data-navigo>About</a>
```
That's how the [demo](http://work.krasimirtsonev.com/git/navigo/) works now.

**Comment by masihjahangiri** [comment]
> ```
> <a href="about" data-navigo>About</a>
> ```

Thank you for your library.
when use data-navigo for absolute link like <a href="http://example.com/x/y" data-navigo>y</a> URL Not set correctly.
if current url is 'http://example.com/x' when clicked on above link URL will change to 'http://example.com/x/http://example.com/x/y'.

**Comment by masihjahangiri** [comment]
> @chiefcll It's done. There is a new `1.2.1` version released. All you have to do is to add `data-navigo` attribute to your links. For example:
> 
> ```
> <a href="about" data-navigo>About</a>
> ```
> 
> That's how the [demo](http://work.krasimirtsonev.com/git/navigo/) works now.
Thank you for your library.
when use data-navigo for absolute link like `<a href="http://example.com/x/y" data-navigo>y</a>` URL Not set correctly.
if current url is 'http://example.com/x' when clicked on above link URL will change to 'http://example.com/x/http://example.com/x/y'.

**Comment by masihjahangiri** [comment]
> @chiefcll It's done. There is a new `1.2.1` version released. All you have to do is to add `data-navigo` attribute to your links. For example:
> 
> ```
> <a href="about" data-navigo>About</a>
> ```

Thank you for your library.
when use data-navigo for absolute link like `<a href="http://example.com/x/y" data-navigo>y</a>` URL Not set correctly.
if current url is 'http://example.com/x' when clicked on above link URL will change to 'http://example.com/x/http://example.com/x/y'.
