### ISSUE TITLE
How can I get the original url of the link what clicked

### ISSUE THREAD

**Issue by martonx** [krasimir/navigo#98]
Hi, I have this router:

this.router.on({
            '/Admin': (params, query) => this.loadPage(params, query),
            '/Admin/Test': (params, query) => this.loadPage(params, query)
        }).resolve();

In loadPage I would like to do an ajax GET request for the clicked link's url.

**Comment by martonx** [comment]
I added a PR for this too. https://github.com/krasimir/navigo/pull/101 I'm sure it is not the most elegant solution, but better then nothing, or better then other hacky solutions popped into my mind.

**Comment by krasimir** [comment]
`4.5.0` now contains `lastRouteResolved` that returns the latest matched URL.

**Comment by martonx** [comment]
Thank you!
