### ISSUE TITLE
Please make routes case insensitive

### ISSUE THREAD

**Issue by martonx** [krasimir/navigo#99]
```
this.router.on({
            '/Admin': (params, query) => this.loadPage(params, query),
            '/Admin/Test': (params, query) => this.loadPage(params, query)
        }).resolve();
```
This routing is working just for /Admin and / Admin/Test but not for /admin and /admin/test. As urls are caseinsensitive, please fix on handling routes.

**Comment by martonx** [comment]
I created a PR for this: https://github.com/krasimir/navigo/pull/100

**Comment by krasimir** [comment]
Thank you for the PR. I added this as a feature in the latest `4.4.0` release. Use 
```js
Navigo.MATCH_REGEXP_FLAGS = 'i';
```
